deployments/deployment.yaml
Definitely more to come in this area, but hms-content is the plugin name
that should hold tests for this service
=> Update iqe plugin name in deployment.yaml

Makefile, db/migrations/20220512132042_create_repository_configurations_table.up.sql, docs/docs.go, docs/openapi.json, go.mod, go.sum, pkg/api/api.go, pkg/api/repository.go, pkg/dao/interfaces.go, pkg/dao/repository.go, pkg/handler/api.go, pkg/handler/api_test.go, pkg/handler/repositories.go, pkg/handler/repository_test.go
Adds create endpoint for content source. Adds a 'dao' layer and 'api' package.
The 'api' package defines all the API request/response structs. For example, with create, when the handler gets a request, it binds it to the 'CreateRepository' struct in the 'api' package. Then, that struct is passed to the 'dao' package which interacts with the models and the database to the necessary items to the database.
To test you need to use the "x-hr-identity" header. You want a base64 encoded JSON that looks like: 
> "identity": {
"account_number": "12345",
"org_id": "54321"
}
Handling the account_number and org_id relies on this common package: https://github.com/RedHatInsights/platform-go-middlewares/tree/master/identity
TODO:
=> CONTENT-40: Create content source

.dockerignore, .github/workflows/content-sources-actions.yml, Makefile, README.md, build/Dockerfile, mk/alias.mk, mk/db.mk, mk/docker.mk, mk/go-rules.mk, mk/help.mk, mk/includes.mk, mk/meta-alias.mk, mk/meta-db.mk, mk/meta-docker.mk, mk/meta-general.mk, mk/meta-legacy.mk, mk/plantuml.mk, mk/printvars.mk, mk/projectdir.mk, mk/swag.mk, mk/variables.mk
A set of changes based on small snippets I had from other repos:
- Set default values for necessary variables in `mk/variables.mk`.
- Add generic rules to build golang binaries at `cmd/dir/**`, and other helper rules `tidy` and `vendor`.
- Add generic rule to generate diagrams from plantuml files at `docs/` directory.
- Install swag locally to the repository and add dependency in `openapi` rule.
- Add rules to start/stop postgres from a container (useful for developing from the workstation).
- Add generic rules to build and push container images.
- Set `help` as default rule, and generate help for the rules from the comments.
=> makefile:proposals for Makefile

mk/db.mk, mk/docker.mk
docker doesn't support 'container exists', so use inspect instead.
Docker and podman use different health text in inspect, so check both
=> Fix differences between podman and docker

cmd/dbmigrate/main.go, pkg/api/api.go, pkg/api/repository.go, pkg/dao/error.go, pkg/dao/interfaces.go, pkg/dao/repository.go, pkg/dao/repository_test.go, pkg/handler/api.go, pkg/handler/api_test.go, pkg/handler/repositories.go, pkg/handler/repository_test.go, pkg/models/repository_configuration.go, pkg/seeds/seeds.go
- Delete and List actions to the DAO layer.
- Additional error checking to Fetch/Update in the DAO layer.
- Rewrites the repository handler tests to use serveHTTP instead of context (because it feels less cumbersome)
- Org ID filters to all the queries that were missing them.
- Tests for verifying Org ID is correct when returning results from database and API
- IdentityHeader constant to api/api.go
- Rename collectionResponse -> setCollectionResponseMetadata
The TestList pagination tests in the handler tests are a bit tricky now because of the mocking. I'm not 100% sure they're still testing what they need to test.
=> CONTENT-56: Add list/delete dao layer and honor org id

.gitignore, .vscode/settings.json
- Set configuration for .gitignore
- For tests, set CONFIG_PATH to point out the current 'configs` direcotory
using the absolute workspace path.
=> proposal:configuration which allow to run and debug unit tests from VSCode

.github/workflows/title.yml, README.md
Changes the commit format such that:
* A jira card is now required
* You can use Refs or Fixes to indicate if a PR
is related to or fully fixes a card
* Adds a github action to validate PR Title
=> Refs 101: update commit format

api/docs.go, api/openapi.json, pkg/api/repository.go, pkg/dao/interfaces.go, pkg/dao/repository.go, pkg/dao/repository_test.go, pkg/handler/repositories.go, pkg/handler/repository_test.go
Adds:
1. Create returns api.RepositoryResponse object
2. With 201 status, create will return Location header with the url to the resource. I see many sources online saying this is part of the spec, so I thought we might want it.
Fixes:
1. Fetch spec success now says it returns api.RepositoryResponse object
2. Delete spec now says it returns 204 instead of 200
3. Spec examples for distributions_versions were being formatted strangely
old
```
"example": [ 
"['7'",
"'8']"
]
```
new (I think this is preferred?)
```
"example": [ 
"7",
"8"
]
```
=> Fixes 116: Add create response object and openAPI spec fixes

build/Dockerfile, cmd/dbmigrate/main.go, cmd/external-repos/main.go, db/migrations/20220512132042_create_repository_configurations_table.up.sql, deployments/deployment.yaml, mk/includes.mk, mk/meta-repos.mk, mk/repos.mk, pkg/dao/interfaces.go, pkg/dao/repository.go, pkg/dao/repository_test.go, pkg/external_repos/external_repos.json, pkg/external_repos/image_builder.go, pkg/external_repos/store.go, pkg/external_repos/store_test.go, pkg/external_repos/suite_test.go, pkg/handler/repository_test.go, pkg/models/repository.go
This adds a couple commands:
```
Manage external repo information
repos-download   Download external repo urls from Image Builder
repos-import     Import External repo urls from Image Builders into the DB
```
so you can run:
```
rm ./pkg/external_repos/external_repos.json    #clear out the existing cache
make repos-download  
```
the file should be recreated exactly
```
```
check your db and see the repos import:
```
select * from repositories ;
```
This also adds a "public" field to repositories, to mark repos that are available to all accounts, regardless of presence of repository_configuration
=> Fixes 90: commands to download and load external repos

deployments/deployment.yaml
The Clowder template require names for initContainers if more than one is specified
```
STDERR:
The ClowdApp "content-sources" is invalid: 
* spec.Deployments[0].PodSpec.InitContainers[0]: Forbidden: multiple initcontainers must have a name
* spec.Deployments[0].PodSpec.InitContainers[1]: Forbidden: multiple initcontainers must have a name
```
see the Clowder API [spec](https://redhatinsights.github.io/clowder/clowder/dev/api_reference.html#k8s-api-github-com-redhatinsights-clowder-apis-cloud-redhat-com-v1alpha1-initcontainer)
=> Fixes 134: Set names for init-containers and typo fix

api/docs.go, api/openapi.json, pkg/api/repository.go, pkg/dao/error.go, pkg/dao/interfaces.go, pkg/dao/repository.go, pkg/dao/repository_test.go, pkg/handler/repositories.go, pkg/handler/repository_test.go
Adds bulk create
**Example:**
POST `/api/content_sources/v1/repositories/bulk_create`
Body:
```
[
{
"name": "test1",
"url": "test1",
},
{
"name": "test2",
"url": "test2",
}
]
```
Response:
```
[
{
"error": nil,
"repository": {...repo}
},
{
"error":nil,
"repository": {...repo}
}, ...
]
OR when there's an error
[
{
"error": "error",
"repository": nil,
},
{
"error": nil,
"repository": nil,
},
]
```
Still needs
=> Fixes 96: Add bulk create

build_deploy.sh, mk/docker.mk, pr_checks.sh
Add a docker-login make target, for use in build_deploy.sh
build_deploy.sh will be used by appsre pipelines to push commits to
quay/redhat.io. The GH action building to quay can be removed (once
appinterface updates are accepted and repo created).
pr_checks leverages bonfire for PR image building, deployment, and test execution. appinterface pipeline definitions will execute this script against PRs.
=> Refs 105: Add pr_checks and build_deploy

deployments/deployment.yaml, pr_check.sh
The name should match the resourceTemplate component name in app-interface for consistent `bonfire deploy` and `bonfire deploy-iqe-cji` behavior.
=> Refs 105: Update clowdapp name

pkg/dao/repository.go, pkg/dao/repository_test.go, pkg/models/repository_configuration.go, pkg/models/rpm.go
Adds validation to updating repositories.
This could also be done using a `BeforeSave` hook that would run before both Update and Create, but keeping the hooks separate seems more future-proof to me.
=> Fixes 122: Add validation to Repository update

deployments/deployment.yaml
In the UI for the ephemeral environment, go to Workloads > Cron Jobs. Then you can see the log for the pod content-sources-backend-introspect-all, which will show introspection being completed.
=> Fixes 113: Daily cronjob to introspect-all

db/migrations/20220512132042_create_repository_configurations_table.up.sql, go.mod, go.sum, pkg/dao/interfaces.go, pkg/dao/public_repositories.go, pkg/dao/public_repositories_test.go, pkg/external_repos/introspect.go, pkg/external_repos/introspect_mocks_test.go, pkg/external_repos/introspect_test.go, pkg/models/repository.go
Adds
- A check before introspection to see if the repository revision number has changed. If not, don't introspect because it is assumed the repository hasn't changed since the last introspection. 
- If it has not changed, it won't error, just "successfully update 0 packages". 
- A "revision" column to the "repositories" table that saves the previous revision number.
I tested this by creating a yum repo locally and then serving it with apache. Then I could change the revision number to whatever I wanted.
Depends on this yummy PR: https://github.com/content-services/yummy/pull/6
~~To use this yummy PR, check it out locally and then add `replace github.com/content-services/yummy => path/to/local/yummy`, to `go.mod`, above `require`~~
Still needs:
=> Fixes 149: Check revision number before introspection

pkg/dao/repository_test.go, pkg/models/repository_configuration.go
on hooks you have to call SetColumn, you cannot just
update the attribute directly, even if it works for creation
=> Fixes 164: properly set versions when de-dupeing

pkg/dao/repository_test.go, pkg/dao/rpm_test.go, pkg/dao/suite_test.go, pkg/handler/repository_test.go, pkg/models/suite_test.go, pkg/seeds/seeds.go, pkg/seeds/seeds_test.go
- Update TestUpdateEmpty to make it more predictable.
- Fix TestSavePublicUrls test.
- Update TestUpdateBlank to make it more predictable.
- Update TestBulkCreateOneFails to make it more predictable.
=> Fixes 119: fix some tests failing on seeded database

.golangci.yaml, docs/openapi/Models/api.RepositoryResponseJSON.md, pkg/api/repository.go, pkg/dao/repository.go, pkg/handler/repository_rpm.go, pkg/handler/repository_test.go, pkg/models/repository_configuration.go
There were three fields I could find that were returning null:
1. The bulk create error field, when there's no error.
~2. The bulk create repository field, when there is an error.~ leaving out because it's not causing a CI failure and it's not a simple fix
3. The distribution versions field after a successful creation, if no versions were specified.
I changed these to:
1. empty string
~2. empty object~
3. empty array
=> Fixes 143: Remove null fields from api responses

mk/swag.mk
For now, to avoid breaking change in v1.8.5
I can't find a simple way to pin package versions with Go. go.mod doesn't work quite like a typical requirements file. It seems the two ways are to download the wanted version manually or keep the wanted version locally and replace the requirement with the local version.
=> Fixes 169: Use swag v1.8.4

.vscode/settings.json, api/docs.go, api/openapi.json, docs/openapi/Models/api.RepositoryValidationRequest.md, pkg/api/repository_parameters.go, pkg/dao/interfaces.go, pkg/dao/repository_config.go, pkg/dao/repository_config_test.go, pkg/handler/repositories_test.go, pkg/handler/repository_parameters.go, pkg/handler/repository_parameters_test.go
This adds the ability for the validation API to EXCLUDE the sent UUIDs from its name/url uniqueness check, thus allowing the ability to use this API to validate against within the repository edit screen. 
This solves the problem of false positive (where the uniqueness check would fail) when validating a repo effectively against itself or others in the edit group.
An example: 
Previously this: 
```json
[
{
"name": "google",
"url": "https://www.google.com"
// "uuid": "a68feaa3-9746-4719-8e33-3ff4688fed85",
},
{
"name": "apple",
"url": "https://apple.com", 
//  "uuid": "9d6fb177-ff10-41fc-81d4-ea12ae963042",
}
]
```
would result in:
```json
[
{
"name": {
"skipped": false,
"valid": false,
"error": "A repository with the name 'google' already exists."
},
"url": {
"skipped": false,
"valid": …
```
=> Fixes 159: Update validation API to support editing

api/docs.go, api/openapi.json, docs/openapi/Models/api.SearchRpmRequest.md, pkg/api/repository_rpm.go, pkg/dao/rpm.go, pkg/dao/rpm_test.go
This change will let to search rpm packages by specifying a list of repository_configurations uuids; it is combined as a logic or with the list of urls.
For /api/content_sources/v1/rpms/names route it will let to:
```json
{
"urls": ["https://MzjLlbBGbpZTNGIIVnoN.com/IuQyV"],
"uuids": ["98f88705-ba61-496f-9ed9-12268df2f790"],
"search": "a"
}
```
or
```json
{
"urls": ["https://MzjLlbBGbpZTNGIIVnoN.com/IuQyV"],
"search": "a"
}
```
or
```json
{
"uuids": ["98f88705-ba61-496f-9ed9-12268df2f790"],
"search": "a"
}
```
a list of urls or uuids should be present, or both, but not none of them.
List of changes:
- Update request structure.
- Update dao object to consider the list of uuids.
- Update tests.
- Update api documentation.
=> Fixes 162: Let search packages by uuid

mk/go-rules.mk
When a source code is updated or just touched, now `make build` and `make run` detect it has changed and the binaries are rerebuilt.
=> Fixes 172: fix make build and make run rules

pkg/dao/external_resource.go, pkg/dao/external_resource_test.go
and not just that the passed in url returns 2XX
=> Fixes 166: propery validate repomd exists

api/docs.go, api/openapi.json, cmd/external-repos/main.go, db/migrations/20220512132042_create_repository_configurations_table.up.sql, docs/openapi/Models/api.RepositoryResponse.md, pkg/api/repository.go, pkg/config/value_constraints.go, pkg/dao/repositories.go, pkg/dao/repositories_test.go, pkg/dao/repository_config.go, pkg/dao/rpm.go, pkg/dao/rpm_test.go, pkg/dao/suite_test.go, pkg/external_repos/introspect.go, pkg/external_repos/introspect_test.go, pkg/handler/repositories_test.go, pkg/models/repository.go, pkg/models/repository_rpm_test.go, pkg/models/repository_test.go, pkg/models/suite_test.go, pkg/seeds/seeds.go
Adds introspection status timestamps, status, and last error to repository. Updated on introspection and returned in list and fetch responses.
To test, create some repositories and list/fetch them. See the new fields. Then, introspect the repositories and list/fetch them again to see how the timestamps/error/status change.
=> Fixes 109: Store and return introspection status metadata

pkg/dao/interfaces.go, pkg/dao/rpm.go, pkg/dao/rpm_test.go, pkg/external_repos/introspect.go, pkg/external_repos/introspect_mocks_test.go
only once after each introspect-all.  Also makes a test a tad more readable IMO
=> Fixes 144: remove unused rpm entries more efficiently

pkg/api/api.go, pkg/dao/repositories.go, pkg/dao/repository_config.go, pkg/dao/repository_config_test.go, pkg/handler/api.go, pkg/handler/api_test.go, pkg/models/repository_configuration.go
Adds some logic for ordering the repository list response. 
Current sort_by parameters: 
- 	name  // Default
- 	url 
- 	distribution_arch 
- 	distribution_versions
-	package_count
-	status
All parameters can optionally add either ":asc" or ":desc"
A sort_by list is possible by using the following template when constructing the url params: 
.../content-sources/v1/repositories/?sort_by[]=status&sort_by[]=url:asc&sort_by[]=name:desc
this will construct a sql query as follows: status asc, url asc, name desc
For more information: [console doc sorting standardization](https://consoledot.pages.redhat.com/docs/dev/developer-references/rest/sorting.html)
=> Fixes 165: Set list default sort order (name asc)

pkg/dao/repositories.go, pkg/dao/repositories_test.go
The `Update` function in the repository dao was not working correctly when passed zero values. It would update the model with the zero values.
It may be best to have the [internal Repository object](https://github.com/content-services/content-sources-backend/blob/main/pkg/dao/repositories.go#L10) split into two the way that the RepoConfig layer has RepositoryRequest and RepositoryResponse. This way we can distinguish between what should be updated and what shouldn't be with `nil`. I can make a change like that here if we want.
For now I fixed this in the least disruptive way possible because it's blocking #92 
To test:
Introspect and repository and the Revision field should be saved correctly. Without this change, it would be blank.
=> Fixes 185: Save revision properly

pkg/seeds/seeds.go, pkg/seeds/seeds_test.go
Currently seed test is the slowest test file, taking over a second.  
Some of this is due to 'batch size' for inserting, and a desire to test a number greater than that.  
This ticket makes the batch size configurable so the seeding can test with a loweramount
=> Fixes 187: speed up seeds_test

cmd/external-repos/main.go, deployments/deployment.yaml, pkg/external_repos/external_repos.json, pkg/external_repos/introspect.go, pkg/external_repos/introspect_test.go
- It runs every 8 hours, starting at 0:00 hours.
- It executes for every repository with Status != 'Valid'.
- It does not execute for a repository with Status == 'Valid' hat was introspected into the last 24 hours.
- Unit tests for the above.
- Removed: Add livenessProbe to the pod job specification: it was stepped back.
=> Fixes 152: Smarter introspection job

pkg/config/config.go
Now when a successful request is made, there should be "debug" and/or "info" logs in the console. Previously, only errors were logged.
=> Fixes 202: Log info and debug requests

pkg/config/config.go, pkg/dao/repositories_test.go, pkg/dao/repository_config_test.go, pkg/dao/rpm_test.go, pkg/dao/suite_test.go, pkg/external_repos/store_test.go, pkg/external_repos/suite_test.go, pkg/models/repository_configuration_test.go, pkg/models/repository_rpm_test.go, pkg/models/repository_test.go, pkg/models/rpm_test.go, pkg/models/suite_test.go, pkg/seeds/seeds_test.go, pkg/seeds/suite_test.go
This PR makes it possible (in GoLand) to right-click on a testify-suite-using test file like `dao/repository_config.go`, click "Run", and only run the tests in that file.
This PR should get a review from both a GoLand user and a VSCode user. I'm not sure how it affects VSCode.
Also, I refactored the dao test suite to embedded a new `DaoSuite` type, which deduplicates some code. I did the same thing in the models test suite, but it's a more obvious change there.
=> Fixes 186: Refactor test suites to run individual test files

pkg/dao/interfaces.go, pkg/dao/repositories.go, pkg/dao/repositories_test.go, pkg/external_repos/introspect.go, pkg/external_repos/introspect_mocks_test.go, pkg/external_repos/introspect_test.go
Previously, zero values were being used to indicate that a field should not be updated on `dao.Repository`. For example, if `Repository.Revision == ""`, don't update. Theoretically, if a Revision number was actually `""`, this value could not be updated. 
This PR introduces a `RepositoryUpdate` structure that uses pointers for all values. Using this, `nil` indicates "do not update", so that `dao.Repository` can now be updated with zero values.
One way to test this would be to host a local yum repo where you can change the revision number. Try changing it then removing it and you should see it update in the database accordingly, after introspection.
=> Fixes 194: Update with zero values in repository dao

pkg/dao/external_resource.go, pkg/dao/repository_config.go, pkg/dao/repository_config_test.go, pkg/models/repository.go, pkg/models/repository_test.go
Adds URL trailing slash on creation, if missing, and removes extra trailing slashes (e.g. http://example/path/////)
Also:
* Trims leading/trailing whitespace from URL before creation
* Reject requests where URLs contain other whitespace
=> Fixes 203: Add URL trailing slash on creation

pkg/dao/repository_config.go, pkg/dao/repository_config_test.go
To test:
Make a PUT/PATCH/DELETE request where the UUID has invalid syntax i.e. /repostories/bad-uuid
Previously, the API would return 500 error and complain about invalid UUID syntax. Now, it returns a 404.
=> Fixes 207: return 404 when uuid syntax invalid

pkg/dao/interfaces.go, pkg/dao/repositories.go, pkg/dao/repositories_test.go, pkg/external_repos/introspect.go, pkg/external_repos/introspect_mocks_test.go
Update functions and methods to align with return error type as the last item for tuple returns.
=> Fixes 205: Return error as last item

api/docs.go, api/openapi.json, pkg/api/repository_rpm.go, pkg/dao/helpers.go, pkg/dao/helpers_test.go, pkg/dao/interfaces.go, pkg/dao/repository_config.go, pkg/dao/rpm.go, pkg/dao/rpm_test.go, pkg/external_repos/introspect_mocks_test.go, pkg/handler/repositories.go, pkg/handler/repository_rpm.go
Adds sort/search functionality to the rpm list endpoint. 
This PR is paired with the front-end PR found [here.](https://github.com/content-services/content-sources-frontend/pull/46)
Still needs:
=> Fixes 212: Add sort/search to rpm List

deployments/deployment.yaml
- set `minReplicas` to 3
- add new `replicas` field with the same value.
- add note to delete `minReplicas` when the new field is available in all the environments.
=> Fixes 242: set minReplicas to 3

pkg/event/schema/schemas_test.go
- This change make the unit test deterministic, avoiding multiple error messages for the validation.
=> Fixes 264: fix TestValidateMessage unit test

pkg/event/schema/schemas_test.go
- fix test "force error when message content fails validation", it was providing
two errors which order is not deterministic; this change fix that providing only
one failure, making the result deterministic.
=> Refs 264: Fix one missed case in the unit test

pkg/dao/rpm.go, pkg/dao/rpm_test.go
- It matches sub-strings instead of suffix for the package name.
=> Fixes 255: update rpm search by matching substrings

deployments/deployment.yaml
=> Refs 283: only select api pods for backend service

pkg/config/config.go, pkg/dao/rpm.go, pkg/dao/rpm_test.go, pkg/db/db.go, pkg/external_repos/introspect.go, pkg/handler/api.go
Gorm has a built in way to batch creations, but we were not using it.  By using it, we can handle all creations, and introspect larger repos that were failing before
=> Fixes 266: use gorm config for batch creation

.vscode/launch.json, deployments/deployment.yaml, pkg/config/config.go, pkg/handler/api.go, pkg/handler/api_test.go
- Add default log level value to info.
- Add LOGGING_LEVEL parameter to the deployment level (we could increase the level in deployment time for ephemeral environment if needed).
- Fix '/ping' and '/ping/' endpoint and update the tests.
TODO:
=> Fixes 286: 404s not logged by default

pkg/config/config.go, pkg/config/logging.go
to reproduce the error we were seeing in stage, run with: `CLOUDWATCH_STREAM=""`  on main branch.
With this change, if you run with `CLOUDWATCH_STREAM=""`  it will default to a 'default' stream.  Otherwise it will use the specified stream.  This could allow us to customize the stream with env variables in our clowdapp config
=> Refs 299: set default log stream

deployments/testing.yaml
This will be deployed by app-interface after stage deployment, and should execute the iqe-content-sources container
=> Refs 322: Add clowdjobinvocation template for stage testing

deployments/testing.yaml
```
message: Some Jobs are still incomplete
reason: ClowdApp.cloud.redhat.com "content-sources" not found
status: 'False'
type: JobInvocationComplete
```
Resolving the above failure when this CJI tries to start
=> Refs 322: Fix appName in testing clowdjobinvocation param

deployments/testing.yaml
stage_post_deploy isn't modifying the HTTP defaults, so its pointing to production
=> Refs 322: Change CJI env to stage_proxy

pkg/dao/interfaces.go, pkg/dao/repositories.go, pkg/dao/repositories_test.go, pkg/external_repos/introspect.go, pkg/external_repos/introspect_mocks_test.go, pkg/external_repos/introspect_test.go, pkg/handler/repository_rpms_test.go
This fixes an issue seen when two packages were identical but have different names.
In such a case the total count would be incorrect, as the checksum data used for package uniqueness would prevent duplication of the package, but the original package count would still be used after this process was completed. 
This fix makes an actual count of the associated items in the database after the introspection is finished to accurately return the correct number for storage.
=> Fixes 289: Package count accuracy fix

api/docs.go, api/openapi.json, pkg/api/api.go, pkg/dao/repository_configs.go, pkg/dao/repository_configs_test.go, pkg/handler/api.go, pkg/handler/repositories.go, pkg/handler/repositories_test.go, pkg/seeds/seeds.go, pkg/seeds/seeds_test.go
Adds filtering repository list by status e.g. `/api/content-sources/v1/repositories/?status=Pending,Valid`
To test, create repositories with different introspection statuses and try filtering.
=> Fixes 326: Filter repositories by status

deployments/dashboards/grafana-dashboard-content-sources.configmap.yaml
Looks like this.
Unless there's something about how it looks that can't wait for a follow up PR, I suggest leaving it as is. I can't save my progress in the grafana playground or load this into the playground (as far as I can tell).
**Testing/Review**
I'm not sure how you would test this since you can't load it into the playground :)
I guess double check the fields against the information in the task's card. Or suggest another idea for where to place this file in the repo.
=> Refs 268: add initial grafana dashboard configmap

deployments/dashboards/grafana-dashboard-content-sources.configmap.yaml
Our grafana dashboard is not showing up in stage. Pretty sure this is why.
=> Refs 268: change grafana folder path to Insights

pkg/dao/repository_configs.go, pkg/dao/repository_configs_test.go
During BulkCreate, the repository URL was not being cleaned up (trailing slashes add/removed) before searching for an existing repository. This would cause an error when creating a repository without a trailing slash, if the repository already existed (with a trailing slash) because `FirstOrCreate` would not find the repository.
1. Create a repository https://jlsherrill.fedorapeople.org/fake-repos/needed-errata/
2. delete the repository
3. Create the repository again, but without a trailing slash: https://jlsherrill.fedorapeople.org/fake-repos/needed-errata
Without changes, this would say that it cannot create repository that already exists.
=> Fixes 1118: cleanup url before bulkcreate

deployments/dashboards/grafana-dashboard-content-sources.configmap.yaml
The grafana panels for the repository counts were using the wrong datasource. I changed the datasource to the environment variable that holds the value of the datasource selected for the whole dashboard (a dropdown in the outer UI).
none
=> Fixes 1138: use env variable for count grafana panels

.github/workflows/content-sources-actions.yml, .github/workflows/qe-approval.yml
This adds a couple of actions:
1) a pr is red if it has 'qe-testing-needed' label but does not have a qe-approved label
2) if someone from our quality engineering team approves a pr, it gets a 'qe-approved' label.  This uses a github action i forked and modified here:  https://github.com/content-services/label-when-approved-action
=> Fixes 1176: add qe approval workflow

pkg/dao/interfaces.go, pkg/dao/repositories.go, pkg/dao/repositories_test.go, pkg/dao/rpms.go, pkg/external_repos/introspect.go, pkg/external_repos/introspect_mocks_test.go, pkg/handler/repositories.go
as part of introspect-all.  This deletes any non-public repositories that were created more than a week ago and do not have any repo_configs defined
Create a repo:
```
curl -X POST http://localhost:8000/api/content-sources/v1/repositories/bulk_create/  -d '[{"name":"foobarz", "url":"https://jlsherrill.fedorapeople.org/fake-repos/needed-errataz"}]'  -H "`./scripts/header.sh 3 1`"   -H "Content-Type: application/json"   
```
update the created_at time:
```
```
```
UPDATE 1
```
Delete the repo (using UUID from create output):
```
curl -X DELETE http://localhost:8000/api/content-sources/v1/repositories/f3430e8e-38b1-4563-84c1-4b93c3e63585  -H "`./scripts/header.sh 3 1`"   -H "Content-Type: application/json"
```
introspect-all
```
go run cmd/external-repos/main.go …
```
=> Fixes 548: delete orphaned repos

deployments/testing.yaml
Include ui param to add selenium container
explicitly specify plugin
I'm not entirely sure this will correctly include the container in the CJI pod for iqe, but this param will be needed regardless of current working order. The CJI spec at least recognizes it right now.
https://github.com/RedHatInsights/clowder/blob/f43aee65bbbe9c1303c23de7661613f2bdf66110/apis/cloud.redhat.com/v1alpha1/clowdjobinvocation_types.go#L59
=> Refs 1104: Add params to CJI for iqe

deployments/testing-job.yaml, deployments/testing.yaml
Related to #204, this specifies a Job template instead of a ClowderJobInvocation, allowing for execution of IQE with a broader environment, with UI test inclusion.
Still needs some updates, opening for visibility and feedback.
=> Refs 1104:  add job spec

deployments/testing-job.yaml
ImagePullSecret is part of the PodSpec not ContainerSpec, and RestartPolicy is required by qontract-reconcile. 
There will be an additional change for the shm volume for the selenium container spec.
=> Refs 1104: Update testing job spec

pkg/config/logging.go
The global log level was hard-coded as info, so the log-level set in config was not taking effect.
It looks like this bug came about from a misunderstanding on a previous pr (#152), that `SetGlobalLevel` is the default log level. I believe the bug in that PR was fixed by adding `LOGGING_LEVEL` to `deployment.yaml`, but not by hard-coding `SetGlobalLevel` to `info`.
1. In your config and/or env, set the logging level to `info`.
2. `make run`, and you should see several messages logged to "info" in the terminal.
3.  Change your log level to `warn`.
4. `make run`, and you should no longer see those messages.
5. Double check my understanding of PR #152 and make sure I did not break what was fixed there.
=> Fixes 360: use log level from config/env

cmd/content-sources/main.go, pkg/dao/interfaces.go, pkg/dao/metrics.go, pkg/dao/metrics_test.go, pkg/event/consumer.go, pkg/event/consumer_test.go, pkg/event/factory.go, pkg/event/handler/introspect.go, pkg/instrumentation/custom/collector.go, pkg/instrumentation/metrics.go
Adds the following metrics:
* kafka message latency
* kafka message success (with error or without error)
* 36 hour intropsection status (intropsected or not)
* this reworks a lot of the existing 24 hours metric gathering
=> Refs 1203: add additional metrics

deployments/deployment.yaml
If its not running, then we aren't listening on port 9000 for metrics
=> Refs 1203: run instrumentation on consumers

pkg/external_repos/introspect.go, pkg/external_repos/introspect_test.go
so if there is slight variation, we will still introspect ever 24 hours
=> Fixes 1426: change introspection check to 23 hrs

README.md, pkg/event/handler/introspect.go, pkg/event/schema/introspectRequest.message.json, pkg/event/schema/introspectRequest.message.yaml, pkg/event/schema/schemas_test.go
Previously bad urls were treated as a 'kafka' error, and not an introspection error.  This led to bad stats when trying to look at metrics.
run the following query:
```.rest
POST http://{{host}}/api/content-sources/v1.0/repositories/
x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiQXNzb2NpYXRlIiwiYWNjb3VudF9udW1iZXIiOiIxIiwiaW50ZXJuYWwiOnsib3JnX2lkIjoiMSJ9fX0K
{
"name": "azure clizz2",
"url": "/fo1",
"distribution_versions": [
"8"
],
"distribution_arch": "x86_64"
},
```
then check metrics:
```
curl localhost:9000/metrics | grep kafka_message_result_total
```
you should see
```
content_sources_kafka_message_result_total{state="success"} 1
```
which is correct, the failure was in introspection, not in message parsing/handling
=> Fixes 1412: remove url validation on event reading

pkg/event/consumer.go, pkg/instrumentation/metrics.go
So that we can reuse them when we switch to a newer tasking system
=> Refs 1203: Rename kafka metrics

cmd/external-repos/main.go, deployments/deployment.yaml, pkg/external_repos/introspect.go
and add rhel 8.7 baseos to init containers
* tests pass
* ` go run cmd/external-repos/main.go import`
*  `go run cmd/external-repos/main.go introspect  https://cdn.redhat.com/content/dist/rhel8/8.7/x86_64/baseos/os https://cdn.redhat.com/content/dist/rhel8/8.6/x86_64/baseos/os`
*  `go run cmd/external-repos/main.go introspect  https://cdn.redhat.com/content/dist/rhel8/8.7/x86_64/baseos/os https://cdn.redhat.com/content/dist/rhel8/8.6/x86_64/baseos/os --force`
=> Fixes 1455: allow intropsect of more than one repo

pkg/config/event.go
Fixes this error:
```
{"level":"warn","time":"2023-03-24T08:00:51Z","message":"config.yaml
file not loaded: Config File \"config.yaml\" Not Found in 
\"[/configs]\""}{
"level":"debug","platform.content-sources.introspect":"platform-mq-stage.platform.content-sources.introspect","time":"2023-03-24T08:00:51Z","message":"internalToReal"}
{"level":"debug","platform-mq-stage.platform.content-sources.introspect":"platform.content-sources.introspect","time":"2023-03-24T08:00:51Z","message":"realToInternal"}
panic: runtime error: invalid memory address or nil pointer dereference[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9244d0]
goroutine 1 [running]:github.com/content-services/content-sources-backend/pkg/config.addEventConfigDefaults(0xc0004a6340?) …
```
=> Fixes 1507: handle nil kafka security proto

pkg/config/event.go
https://github.com/content-services/content-sources-backend/commit/3f26de3b5798caf97e2c20e7d4c7bf48d7562cf6 
moved us away from using a now deprecated clowder setting, but it turns out the non-deprecated setting isn't actually populated.  This now checks and tries to use either if they are populated.
Deploy to stage.
=> Fixes 1507: use deprecated security proto config

pkg/instrumentation/metrics.go
The bucket sizes weren't conducive to writing alerts or really even defining the SLO, this increases them greatly.
None needed?  check the metrics after creating a repo maybe?
=> Refs 1203: adjust message latency bucket sizes

pkg/dao/rpms.go, pkg/dao/rpms_test.go
IB is requesting that rpm name search be case insensitive 
Run these requests:
```
POST http://{{host}}/api/content-sources/v1.0/repositories/
x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiQXNzb2NpYXRlIiwiYWNjb3VudF9udW1iZXIiOiIxIiwiaW50ZXJuYWwiOnsib3JnX2lkIjoiMSJ9fX0K
{
"name": "needed2",
"url": "https://jlsherrill.fedorapeople.org/fake-repos/needed-errata/",
"distribution_versions": [
"8"
],
"distribution_arch": "x86_64"
}
POST  http://{{host}}/api/content-sources/v1.0/rpms/names
x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiQXNzb2NpYXRlIiwiYWNjb3VudF9udW1iZXIiOiIxIiwiaW50ZXJuYWwiOnsib3JnX2lkIjoiMSJ9fX0K
{
"urls": [
"https://jlsherrill.fedorapeople.org/fake-repos/needed-errata/"
],
"search": "Walrus"
}
```
you should get results …
=> Fixes 1149: make rpm name search api case insenstive

db/migrations/20230215133838_RenameEpelUrls.up.sql
This fixes an issue where in dev/ephemeral environments adding a "Popular Repository" would cause the API to return a Status of "" (empty string). 
This prevented the UI from updating the repository list the frontend looks at a repository's "Status" to determine whether or not to poll the API.
Add a popular repository that needs to introspect.
One you haven't added before, or clean out your database.
After adding quickly switch to the repository list view you should see a blank status.
Result after fixing: 
It should say Pending, or any state, if introspection has finished.
=> Fixes 1564: Update migration to prevent status ui bug

deployments/testing-integration.yaml
Shortens the name of the `ClowdJobInvocation` used for integration testing, as the resulting `Job` name exceeded the 63 character limit.
None
=> Shorten CJI name to avoid job name length limit

cmd/external-repos/main.go, pkg/event/handler/introspect.go, pkg/external_repos/introspect.go
This separates introspection errors from internal errors to better report them separately
run the server locally, and run the following request:
```
curl -X POST --location "http://localhost:8000/api/content-sources/v1.0/repositories/" \
-H "x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiQXNzb2NpYXRlIiwiYWNjb3VudF9udW1iZXIiOiIxIiwiaW50ZXJuYWwiOnsib3JnX2lkIjoiMSJ9fX0K" \
-d "{
\"name\": \"needed3\",
\"url\": \"https://jlsherrill.fedorapeople.org/fake-repos/needed-errata3/\",
\"distribution_versions\": [
\"8\"
],
\"distribution_arch\": \"x86_64\"
}"
```
Then monitor the server logs:
```
11:22AM INF Forcing introspection for 'https://jlsherrill.fedorapeople.org/fake-repos/needed-errata3/'
11:22AM WRN Error 0 introspecting repository …
```
=> Fixes 1568: lower log level on introspect errors

deployments/testing-integration.yaml
This PR updates the integration-testing template to never restart the testing or selenium containers.
=> Change integration test template to not restart containers on failure

deployments/deployment.yaml
This defines a query that gets run daily and collected into an S3 bucket for later analysis. 
Manually make sure the query is correct
=> Refs 1602: add floorist query for metrics gathering

deployments/testing-integration.yaml
This PR updates the e2e testing job template to run only once, when tests fail.
=> Update e2e test template to run only once

deployments/testing-integration.yaml
This PR updates the e2e test template to use an `imagePullPolicy` of `Always` for the testing container image. This is required because we always use the same `hms-integration` image tag to point to the latest build, and by default tags other than `latest` are not re-pulled.
=> Update e2e test template to pull testing image every time

deployments/testing-integration.yaml
The previous PR added `imagePullPolicy` at the wrong level in the e2e job template.
=> Move imagePullPolicy to container level in e2e job template

pkg/external_repos/external_repos.json
Image builder will support rhel 9.2 soon.  We need to add repos to support them.
can't test now, as these repos aren't live
=> Fixes 1759: add 9.2 repos

pkg/config/config.go, pkg/config/config_test.go, pkg/instrumentation/custom/collector.go, pkg/instrumentation/metrics.go
this adds a new metric "content_sources_rh_cert_expiry_days", that signifies the number of days until the current RH cert expires
Ensure you have a cdn cert configured in your config.yaml, run the server, then run:
```
curl localhost:9000/metrics | grep expi
```
you'll see something like:
```
content_sources_rh_cert_expiry_days 23
```
=> Refs 1770: add cert expiry metric

mk/pulp.mk
the previous change enabled pulp during compose commands by default improperly, this fixes it
```make compose-clean compose-up```
check if pulp is enabled: `podman ps`
=> Refs 1468: fix compose up and pulp

pkg/notifications/client.go
This attempted change was found online where they referenced different kafka versions (referenced in the sarama config). 
Reference to the existing sarama config versions [here](https://github.com/search?q=org%3ARedHatInsights%20.Version%20%3D%20sarama.&type=code)
=> Fixes 602: Update debug and change kafka version

pkg/notifications/client.go
Previous commit caused an error to do with an unfound dummy kafka ingress. 
This reverts that and prevents the error, it will likely not fix the failing notifications.
=> Fixes 602: Revert previous commit (Glitchtip)

deployments/deployment.yaml
We started building rhel-8.8 images and so we now need to also update the repository introspection in ephemeral environments.
Related to https://github.com/content-services/content-sources-backend/pull/301
=> Refs 1871: Deployments: Introspect rhel-8.8 in ephemeral

cmd/external-repos/main.go, deployments/deployment.yaml, pkg/handler/repositories.go, pkg/handler/repositories_test.go, pkg/tasks/introspect.go
- Renames the `introspect-all` command to `nightly-jobs`
- If new tasking system has been enabled, adds each repository as introspect job to queue, instead of directly invoking introspect for all repositories
1. Set `NEW_TASKING_SYSTEM` env var or `config.yaml` to true.
2. `go run cmd/external_repos/main.go nightly-jobs` will show `[Enqueued Task]...` for each repository.
3. Main server will need to be running for tasks to process.
4. Setting NEW_TASKING_SYSTEM to false should _not_ use the new tasking system, and instead directly invoke introspection for all repositories.
=> Fixes 1470: switch nightly introspect to tasking system

api/docs.go, api/openapi.json, pkg/handler/repositories.go, pkg/handler/repository_parameters.go, pkg/handler/repository_rpms.go, pkg/middleware/enforce_json.go, pkg/middleware/enforce_json_test.go, pkg/router/route.go
Adds middleware `EnforceJSONContentType` that returns an error with status code 415 "Unsupported Media Type" if the Content-Type header is missing, invalid, or not `application/json`. If the Content-Type has optional parameters (e.g. `application/json; parameter=value`), it is still accepted.
The middleware is added at root level and applied to any request that has a body
It affects the following endpoints: 
1. /rpms/names [post] - searchRpmByName
2. /repository_parameters/external_gpg_key/ [post] - fetchGpgKey
3. /repository_parameters/validate/ [post] - validate
4. /repositories [post] - createRepository
5. /repositories/bulk_create/ [post] - bulkCreateRepositories
6. /repositories/{uuid} [put] - fullUpdate
7. /repositories/{uuid} [patch] - partialUpdate
/repositories/{uuid}/introspect/ …
=> Fixes 1644: Enforce JSON Content Type

pkg/dao/repository_configs.go
Takes into account 'any' in AvailableForArch/AvailableForVersion filters.
1.  create a repository with arch 'x86_64'
2. create a 2nd repository with arch any
3.  curl  /api/content-sources/v1/repositories/?available_for_arch=x86_64
you should get both repositories.
Repeat a similar test for distribution_version and available_for_version
=> Fixes 1865: fix repository list filters

deployments/testing.yaml
The test deployment in testing.yaml only runs api tests, so the `ui` section is unnecessary and creates an unused selenium container for each deployment. This PR removes the `ui` section so that the container isn't created at all.
N/A
=> Fixes 25: Remove selenium container from testing.yaml

cmd/content-sources/main.go, pkg/config/config.go
Notifications Client loading spawns a go routine which seemed to cause an issue with worker shutdown in tests.
Tests pass, notifications still are sent.
=> Fixes 1924: move notifications loading to startup

deployments/testing.yaml
Allow for running the CJI with parameters set via SAAS
`bonfire deploy-iqe-cji <args> --template-file <path-to-file-in-branch>`
Resulting CJI had parameters values set correctly via defaults. Resulting pod had correct env config and pytest args.
=> Refs 1947: parametrize CJI fields for IQE

api/docs.go, api/openapi.json, configs/config.yaml.example, deployments/deployment.yaml, pkg/api/features.go, pkg/config/config.go, pkg/handler/api.go, pkg/handler/features.go, pkg/handler/features_test.go, pkg/handler/repositories.go, pkg/handler/repositories_test.go, pkg/router/route_test.go, scripts/header.sh
Adds a setting to determine if snapshotting is enabled
Adds a per account and per user setting to determine if the user can snapshot repositories
Adds an api to return if the feature is 1) enabled 2) accessible to the current user
Updated the header.sh to provide the ability to pass in an account id optionally 
copy new config options from the example config file
```/bin/bash
curl localhost:8000/api/content-sources/v1.0/features/  -H "`./scripts/header.sh 1 snapUser`" 
curl localhost:8000/api/content-sources/v1.0/features/  -H "`./scripts/header.sh 1 noAccess`" 
curl localhost:8000/api/content-sources/v1.0/features/  -H "`./scripts/header.sh 1 noAccess snapAccount`" 
curl localhost:8000/api/content-sources/v1.0/features/  -H "`./scripts/header.sh 1 noAccess NoAccess`" 
```
=> Fixes 1624: adds config/api detailing features

go.mod, go.sum, pkg/config/config.go, pkg/dao/interfaces.go, pkg/dao/repository_configs.go, pkg/dao/repository_configs_mock.go, pkg/dao/repository_configs_test.go, pkg/external_repos/introspect.go, pkg/handler/repositories.go, pkg/notifications/client.go
1) configure your config for kafka if not already:
```
kafka:
auto:
offset:
reset: latest
commit:
interval:
ms: 5000
bootstrap:
servers: localhost:9092
group:
id: content-sources
message:
send:
max:
retries: 15
request:
timeout:
ms: 30000
required:
acks: -1
retry:
backoff:
ms: 100
timeout: 10000
topics:
- platform.content-sources.introspect
- platform.notifications.ingress
```
2) run server `make run`
3) run listener ` KAFKA_TOPIC=platform.notifications.ingress make  kafka-topic-consume`
4) create a bulk repo, edit it, delete it, and see the associated notifications
=> Fixes 1948: Add introspection/edit/delete notifications

pkg/tasks/worker/worker.go, pkg/tasks/worker/worker_pool_test.go
We've been seeing an error message that suggests there is a scenario where a worker will attempt to refresh the heartbeat of the previous (but no longer in-progress) task. This makes it so now only the running task's heartbeat will be refreshed.
1. Use the tasking system by creating/introspecting/deleting repositories. Everything should be working as normal.
2. Try exiting the server with Ctrl+C at different points while tasks are running (or finished). You should not see any warnings or errors.
=> Fixes 1882: only refresh running tasks

pkg/dao/repository_configs.go, pkg/dao/repository_configs_test.go
Fixed a bug that would return an empty URL for the introspect notification, causing the schema to blow up. 
This was a simple DB call order mistake.
=> Fixes 2058: Empty url on introspect notification

pkg/dao/repository_configs.go, pkg/external_repos/introspect.go, pkg/external_repos/introspect_test.go
This fixes the empty struct values for the update notification that were causing it to fail to be parsed by the schems. 
This adds conditional sending of the introspect notification so that it now will only send a notification when the introspection would result in an update.
1) configure your config for kafka if not already:
```
kafka:
auto:
offset:
reset: latest
commit:
interval:
ms: 5000
bootstrap:
servers: localhost:9092
group:
id: content-sources
message:
send:
max:
retries: 15
request:
timeout:
ms: 30000
required:
acks: -1
retry:
backoff:
ms: 100
timeout: 10000
topics:
- platform.content-sources.introspect
- platform.notifications.ingress
```
2) run server `make run`
3) run listener ` KAFKA_TOPIC=platform.notifications.ingress make  kafka-topic-consume`
4) create a bulk repo, edit …
=> Fixes 2065: conditional Introspect & fixed update 

pkg/dao/rpms.go, pkg/dao/rpms_test.go, pkg/handler/repository_rpms.go, pkg/handler/repository_rpms_test.go
Changes RPM list endpoint to return a status 404 instead of 500 when the repository uuid is not found. 
~~GORM throws an error when an invalid uuid is passed in (i.e. invalid syntax) which is returned as a status 500. The 404 only occurs when a valid, but nonexistent uuid is passed.~~
The endpoint will return a 404 if an invalid uuid is passed in. I changed the `isOwnedRepository` method to compare the uuid as `text`, which is consistent with other endpoints.
```
curl localhost:8000/api/content-sources/v1.0/repositories/{some nonexistent repository config uuid}/rpms  -H "`./scripts/header.sh 1 user`"
```
=> Fixes 2112: RPM fetch 404

pkg/tasks/queue/pgqueue.go, pkg/tasks/queue/pgqueue_test.go, pkg/tasks/queue/queue.go, pkg/tasks/queue/queue_mock.go, pkg/tasks/worker/worker_pool.go
There is still reoccurring error "No rows affected when refreshing heartbeat". This error seems to be caused by a race condition at the postgres level. The process refreshing the heartbeat and the process completing the task are two separate goroutines. If the process refreshing the heartbeat queries the task while it is finishing, it will get the old values (i.e. the status is running and not completed). But when it refreshes the heartbeat, the task status is "completed" so there is no longer a heartbeat to refresh.
These changes make it so if we've hit the error, we query the task status, and and try again to refresh the heartbeat only if the task is running.
You can use this python script to help test by introspecting a repository repeatedly.
```
import requests
def sendReq():
url = …
```
=> Refs 1882: retry refresh heartbeat when no rows affected

deployments/testing-integration.yaml
- Update e2e testing template names to not be specific to the stage environment
- Create an identifier string to pass to the test container's IQE_IBUTSU_SOURCE env value. This is used when reporting test results.
=> Refs 1947: Update e2e test template

pkg/config/config.go, pkg/db/db.go, pkg/tasks/queue/pgqueue.go, pkg/tasks/queue/pgqueue_test.go, pkg/tasks/queue/pgx_pool_wrapper.go
This resolves a couple of issues:
* Enqueue() was not properly releasing its acquired db pool connection, this resulted in deadlocks when more than ~20 create reqs came in at once
* Sets a limit on the postgres connections for gorm, as if you perform ~50 create reqs at the same time a postgres server with a default limit of connections will start to max out and start issuing errors
* Reworks pgqueue to use a wrapper around pgxpool.Pool, this allows for testing while giving pgqueue the ability to start/end transactions and acquire/release Pool connections
Checkout this pr and 'make run'
create a new file `./cmd/test/main.go`   with the contents here: https://gist.github.com/jlsherrill/d07efa70bed152d8428c758b7332f95e
then run it:  `go run ./cmd/test/main.go`
You should only get back 201s, …
=> Fixes 2183: fix deadlock in concurrent task enqueue

cmd/external-repos/main.go, db/migrations/20230706145024_add_request_id_to_tasks.down.sql, db/migrations/20230706145024_add_request_id_to_tasks.up.sql, pkg/config/logging.go, pkg/dao/interfaces.go, pkg/event/handler/introspect.go, pkg/external_repos/introspect.go, pkg/external_repos/introspect_test.go, pkg/handler/api.go, pkg/handler/repositories.go, pkg/middleware/enforce_identity.go, pkg/middleware/rbac.go, pkg/models/task_info.go, pkg/pulp_client/client.go, pkg/pulp_client/task.go, pkg/rbac/client_wrapper.go, pkg/router/route.go, pkg/tasks/client/client.go, pkg/tasks/delete_repository_snapshots.go, pkg/tasks/introspect.go, pkg/tasks/queue/pgqueue.go, pkg/tasks/queue/queue.go, pkg/tasks/queue/queue_mock.go, pkg/tasks/repository_snapshot.go, pkg/tasks/repository_snapshot_test.go, pkg/tasks/worker/worker.go, pkg/tasks/worker/worker_pool_test.go, test/integration/snapshot_test.go
- Adds support for the request ID, `x-rh-insights-request-id`, sent in the header and propagates that request ID to logging in the API, tasking, and redis
- Also propagates TaskID/Type logging throughout tasking system and pulp. 
The goal here is to more easily track which events correspond to which request. For example, if I get an error during repository snapshot, it is nice to know which request or task triggered that failed snapshot.
TODO
1. Make an API request, for example, one to create a repository. Add the `x-rh-insights-request-id` header.
```
POST http://localhost:8000/api/content-sources/v1.0/repositories/
x-rh-identity: zEzcvAe....
x-Rh-Insights-Request-Id: 12345
```
3. You should see the request ID propagated through the to the logs for the API, …
=> Fixes 1846: log request ID

api/docs.go, api/openapi.json, pkg/handler/popular_repositories.go, pkg/handler/popular_repositories_test.go
The popular repository table UI implements pagination and this PR adds backend support for pagination using the limit and offset URL parameters.
The JSON that contains popular repositories currently has 3 entries, so it is easiest to test pagination with limits below 3.
```
curl "localhost:8000/api/content-sources/v1/popular_repositories/?offset=1&limit=1"  -H "`./scripts/header.sh 1 user`"
```
Negative or out of range offsets returns an empty array (consistent with other list APIs)
=> Fixes 2193: popular repository pagination

pkg/dao/admin_tasks.go, pkg/dao/admin_tasks_test.go
Improves the "not found" error message when fetching an admin task using a uuid with invalid syntax.
Previously, when making a GET request to `/admin/tasks/:uuid` with a uuid that had invalid syntax, e.g. "invalid-uuid", the error message would be `(ERROR: invalid input syntax for type uuid: "invalid-uuid" (SQLSTATE 22P02))`
The PR changes the error message to `Could not find task with UUID invalid-uuid` which is consistent with other fetch APIs
```curl localhost:8000/api/content-sources/v1.0/admin/tasks/bad-uuid  -H "`./scripts/header.sh 1 adminUser`"```
The "admin_tasks" config feature must be enabled. Either both "admin_tasks.accounts" and "admin_tasks.users" must  be nil to allow any user to access it, or "adminUser" must be added to "admin_tasks.users" to access the endpoint.
This …
=> Fixes 2224: admin task fetch 404

deployments/testing-integration.yaml
The selenium container needs a higher memory limit, but can request in smaller chunks.
The CPU chunks for the iqe container can be smaller, and its memory limit reduced
=> Refs 1947: Adjust memory request and limit, hms-integration

deployments/testing-integration.yaml
This PR adds parameters (enabled by default) to the e2e testing template, to allow collection of browser logs on test failure.
N/A
=> Refs 1947: Add browser and net logs to iqe job template

pkg/pulp_client/interfaces.go, pkg/pulp_client/pulp_client_mock.go, pkg/pulp_client/pulp_global_client_mock.go, pkg/tasks/delete_repository_snapshots.go, pkg/tasks/delete_repository_snapshots_test.go, test/integration/delete_test.go
if no domain was ever created
In an org that has never created any repos (or at least none that were snapshotted).  Create a repo:
```
POST http://localhost:8000/api/content-sources/v1.0/repositories/
x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiJmb28ifSwiYWNjb3VudF9udW1iZXIiOiIzMCIsImludGVybmFsIjp7Im9yZ19pZCI6IjMwIn19fQo=
x-Rh-Insights-Request-Id: 9876
{"name":"pulp 3.16","url":"http://yum.theforeman.org/pulpcore/3.16/el8/x86_64/","snapshot": false}
```
get the UUID of the created repo and delete it:
```
DELETE http://localhost:8000/api/content-sources/v1.0/repositories/14c3a83d-7574-4654-9a2d-8d4c92254b39
x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiJmb28ifSwiYWNj …
```
=> Fixes 2310: fix 404 err on delete task

pkg/dao/repository_configs.go, pkg/dao/repository_configs_test.go, pkg/handler/repository_parameters.go
The validation api didn't handle bad uuids well.  In addition, the error was returned to the user but was not logged.  This adds that logging
Perform this request:
```
POST http://localhost:8000/api/content-sources/v1.0/repository_parameters/validate/
x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiJqZG9lIn0sImludGVybmFsIjp7Im9yZ19pZCI6IjEyMyJ9fX0K
[{"url":  "http://yum.theforeman.org/pulpcore/3.16/el8/x86_64/", "uuid":  "'response.write(731,493*173,328)'", "snapshot":  false}]
```
=> Fixes 2273: handle bad uuids on validate api

cmd/content-sources/main.go, pkg/pulp_client/domains.go, pkg/pulp_client/interfaces.go, pkg/pulp_client/pulp_client_mock.go, pkg/pulp_client/pulp_global_client_mock.go, pkg/tasks/delete_repository_snapshots.go, pkg/tasks/delete_repository_snapshots_test.go, pkg/tasks/repository_snapshot.go, pkg/tasks/repository_snapshot_test.go
previously domains configured with s3 were not configured with an acl that was correct.  This fixes that, but some domains may already be created improperly.  This adds the ability to update s3 storage settings in pulp if they have changed
A bit hard to truly test.
1.  Create an s3 bucket on an amazon account. (default config is fine)
2.  within IAM in s3, create a user with full s3 permissions (AmazonS3FullAccess policy)
3. create an access key for them
4. on a fresh db, on 'main' branch, configure access to this account:
```
pulp:
server: http://localhost:8080
username: admin
password: password
storage_type: object #object or local
custom_repo_objects:
url: https://s3.us-east-1.amazonaws.com/
access_key: "MyKey"
secret_key: "MySecret"
name: test-pulp
region: us-east-1
```
5.  try to …
=> Fixes 2315: set proper s3 acl and update domains

pkg/tasks/worker/worker.go
PR #333 should merge first. This PR is built on that PR.
To make it clearer that the task failed, this changes logging to log the error of the failed task.
This PR in combination with this [commit to zest](https://github.com/content-services/zest/commit/ee55f31f4234ca312ca13fc860b8cd0ca923b2cb) should fully address the JIRA issue. The change to zest will not be used until we update our app to a newer version of zest. 
1. Create a repo with bad url (i.e. `http://example.com`), with snapshot enabled. 
2. You should see the error `json: cannot unmarshal string into Go struct field TaskResponse.error of type map[string]interface {}"` for the sync task specifically. 
3. To test the change to zest, update your go.mod to use the latest zest version. There will be some syntax errors in the …
=> Fixes 2083: log when a task fails to complete

deployments/deployment.yaml
app-sre flagged this as an issue, but most other insights apps seem to be flagged too, so its hard to find an example of anyone doing this correctly.  Lets see
tests pass
=> Refs 645: specifying runAsNonRoot for deploy

deployments/testing-integration.yaml
We are seeing some out of memory errors while capturing the browser logs. I'm hoping that increasing the limit will resolve this.
=> Refs 1947: Increase selenium container memory

configs/config.yaml.example, deployments/deployment.yaml, pkg/config/config.go, pkg/pulp_client/rpm_remote.go
Allows setting the download policy via an environment variable.  Currently only on_demand and immediate are supported.
for local dev testing run:
```
CLIENTS_PULP_DOWNLOAD_POLICY=immediate  make run
```
create a repo with snapshotting turned on, then check pulp (use password 'password'):
```
$ psql -h localhost -p 5432  pulp pulp 
pulp=# select policy from core_remote;
```
There's not really any way to test this from a users perspective. right now
=> Fixes 1965: configurable download policies in pulp

deployments/testing-integration.yaml
the IQE_PLUGINS parameter has invalid chars for a job name
Auto promotion is failing because my updated job name doesn't meet job name specs with the plugin names.
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/77500
=> Refs 2344: Add a job name stub for integration job

pkg/dao/admin_tasks.go, pkg/dao/repository_configs.go, pkg/dao/rpms.go, pkg/dao/snapshots.go, pkg/dao/snapshots_test.go, pkg/dao/task_info.go, pkg/dao/task_info_test.go, pkg/handler/snapshots.go, test/integration/snapshot_test.go
There are a few different endpoints where bad params can cause 500 errors. This should fix most if not all of those endpoints.
1. GET `/repositories/{bad-uuid}/snapshots/`
2. GET `/tasks/baduuid`
3. POST `/rpms/names/` with body ` { uuids: ["John Doe"] }`
4. GET `tasks/?offset=10&limit=10&status=%00`
Note number 4 in particular, where the status is %00. That affects other endpoints params too like `/repositories/?status=`  or `/repositories/%00/snapshots`. 
1. Test the endpoints listed with the params listed. You should get no 500 errors.
2. You can try similar inputs on other similar endpoints to see if anything was missed.
=> Fixes 2239: fix various 500 errors caused by bad params

deployments/deployment.yaml, pkg/config/config.go, pkg/rbac/client_wrapper.go, pkg/rbac/client_wrapper_test.go
if rbac_org_admin_skip is set to true, then don't check rbac if a user identity header tells us the user is an org_admin
1.  turn on rbac_enabled in config.yaml
2. run the app with skip turned on and the mock rbac service
```
RBAC_ORG_ADMIN_SKIP=true go run cmd/content-sources/main.go api mock_rbac
```
3. use this header script to generate org_admin headers:  https://gist.github.com/jlsherrill/880bb18c288be3916c8cda94db0efacd
4.  List/create repos via the api.  Any request generated with the new script should work.  Using the older script, only those users listed in 'mocks' -> 'rbac' section of config.yaml would be allowed, all others would be rejected
=> Fixes 2419: ignore rbac check for org admins

cmd/external-repos/main.go, pkg/dao/interfaces.go, pkg/dao/task_info.go, pkg/dao/task_info_mock.go, pkg/dao/task_info_test.go, pkg/external_repos/introspect.go
according to the following rules:
* repo delete tasks that are older than 10 days and not failed
* introspect tasks that are older than 10 days
* snapshot tasks where the repository config has been deleted
Previously orphan cleanup was also being run multiple times, this reduces it to just once per nightly job (before starting the introspection jobs)
On a freshly cleaned db, use this main script:   https://gist.github.com/jlsherrill/efe0bd375a46f32ed3a562e130bb8371
to create some tasks.
This creates similar tasks to the unit test i wrote. 
You can then use 'make db-cli-connect' to look at the tasks.
run: ```go run cmd/external-repos/main.go  nightly-jobs```  to cleanup the tasks.
QE can only really easily test the 3rd of the rules above. 
* Create a repository with snapshotting enabled. …
=> Fixes 2018: add task cleanup

.rhcicd/pr_check.sh
and fix doc link
One test[1] is failing[2] because it is not supported in ephemeral env, so I want to add this env variable.
pr checks pass[3]
[1] https://gitlab.cee.redhat.com/insights-qe/iqe-content-sources-plugin/-/blob/master/iqe_content_sources/tests/test_repository_api_only.py#L613
[2] https://ci.int.devshift.net/job/content-sources-backend-pr-check-main/359/testReport/junit/tests/test_repository_api_only/test_introspection_of_persistent_user/
[3] https://ci.int.devshift.net/job/content-sources-backend-pr-check-main/
=> Add IQE_ENV=ephemeral

deployments/deployment.yaml
The kafka consumer init container is crashing while trying to introspect repos (On startup, all repos in the database are introspected.). This problem only occurs in ephemeral env.
As per @jrusz 's suggestion, this issue could be due to memory taking to long to be increased, so bumping the request size to see if that helps to get the memory increased before the pod crashes. 
Check for content-sources-backend-kafka-consumer restarting multiple times.
=> Refs 1963: Bump mem request to 200Mi

pkg/dao/admin_tasks.go, pkg/dao/helpers.go, pkg/dao/repository_configs.go, pkg/dao/rpms.go, pkg/dao/snapshots.go, pkg/dao/task_info.go
instead of converting to text in queries, as
that has a performance penalty
Tests pass
Here's the explain plan comparing two queries, the one with text(uuid) has a MUCH higher 'cost':
```
content=# explain SELECT * FROM repository_configurations WHERE (text(UUID) = '59a54071-06fb-45b6-b721-09bd0fb767cf' AND ORG_ID = '16791776') AND repository_configurations.deleted_at IS NULL ORDER BY repository_configurations.uuid LIMIT 1
;
                                                        QUERY PLAN                                                         
---------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=3529.23..3529.23 rows=1 width=172)
   ->  Sort  (cost=3529.23..3529.23 rows=1 width=172)
         Sort Key: …
```
=> Fixes 2543: use a null uuid for bad uuids

pkg/config/config.go, pkg/config/config_test.go
Sometimes the objectstore  hostname has a protocol/scheme, sometimes it doesn't.  Handle both cases (with a test!)
snapshotting works in ephemeral, we'll test stage after merge
=> Fixes 2631: handle bucket hostname with proto

go.mod, go.sum
to limit the size of an xml file we can process
Try to introspect a repo: https://raw.githubusercontent.com/lpardoRH/custom-repo/zip_bomb2/
You will likely run out of memory in ephemeral (maybe locally).  With this fix it will simply return zero packages (as its not really an xml file).   Right now this does not trigger an error which is a result of underlying libraries.  Since this edge case is an attempted attack and not a legitimate case, this is okay.  A partial (or corrupted) XML file would error as expected
=> Fixes 2668: use newer yummy

pkg/dao/repository_configs.go, pkg/dao/repository_configs_test.go
When creating a repository, if a name or URL is already being used, the error message should say which field is duplicated. In a previous change, we renamed constraints that were being used to determine which field is duplicated. I've updated the function with the new constraint names.
1. Create a repository
2. Create a repository again with the same name.
3. Check the error message. It should tell you "name" is the duplicated field.
4. Create a repository again with the a different name, but same URL.
5. Check the error message. It should tell you "URL" is the duplicated field.
=> Fixes 2381: specify if name or URL is duplicated

.github/workflows/content-sources-actions.yml, db/migrations/20220512132042_create_repository_configurations_table.up.sql, db/migrations/20220923124812_add_package_count.down.sql, db/migrations/20220923124812_add_package_count.up.sql, db/migrations/20221130134116_move_revision_to_checksum.down.sql, db/migrations/20221130134116_move_revision_to_checksum.up.sql, db/migrations/20221212134912_remove_revision.down.sql, db/migrations/20221212134912_remove_revision.up.sql, db/migrations/20230322110439_add_failed_introspection_count_to_repositories.down.sql, db/migrations/20230322110439_add_failed_introspection_count_to_repositories.up.sql, db/migrations/20230330144631_snapshotting_custom.down.sql, db/migrations/20230330144631_snapshotting_custom.up.sql, db/migrations/20230410105610_add_jobqueue.down.sql, db/migrations/20230410105610_add_jobqueue.up.sql, db/migrations/20230706145024_add_request_id_to_tasks.down.sql, db/migrations/20230706145024_add_request_id_to_tasks.up.sql, db/migrations/20230707065625_add_repository_path.down.sql, db/migrations/20230707065625_add_repository_path.up.sql, db/migrations/20230804092757_add_domains.up.sql, db/migrations/20230807161216_refactor_snapshots.up.sql, db/migrations/20230814125610_add_snapshot_added_removed.down.sql, db/migrations/20230814125610_add_snapshot_added_removed.up.sql, db/migrations/20230823115016_add_last_snapshot_task.down.sql, db/migrations/20230823115016_add_last_snapshot_task.up.sql, db/migrations/20230831162419_add_repo_fields.down.sql, db/migrations/20230831162419_add_repo_fields.up.sql, mk/go-rules.mk
Makes it so migrations be be re-run on an already migrated database. Also fixed a few down migrations that were not working. Adds a CI test for migrations.
1. Migrate up
2. Migrate down
3. Migrate up
4. Drop the `schema_migrations` table
5. Migrate up again
=> Fixes 2490: make migrations idempotent

pkg/tasks/introspect.go, pkg/tasks/queue/pgqueue.go, pkg/tasks/queue/pgqueue_test.go, pkg/tasks/queue/queue.go, pkg/tasks/queue/queue_mock.go, pkg/tasks/worker/worker.go
We're seeing an issue where ListenForCancel is erroring because context is canceled. Likely happening because the task is finishing before the listener is ready to wait for a notification.
You can see the timestamps are very close.
```
Oct 5, 2023 @ 08:01:11.935 --> time right before registering listener
Oct 5, 2023 @ 08:01:12.006 --> time failed because context cancelled
```
There are many cases where this does not happen and the listener has time to finish registering, which should rule out an issue with the register command hanging.
This adds `context.CancelWithCause` so that we can identify when the context is canceled because the task is finished. If the task is finished, we simply ignore these errors.
You might try to reproduce this locally, but I was not able to.
=> Refs 1581: cancel task with cause

.gitignore, pkg/dao/repository_configs_test.go, pkg/handler/popular_repositories.go, pkg/handler/popular_repositories_test.go
Fixes popular repositories not having a UUID added to their list due to a gorm default limit change. 
Previously, when limit was set to 0  (or not set, which defaults to 0) the limit was effectively infinite, the update changes that so that the limit is now actually 0. 
This made it so that on query of the repositoryConfig.List method (with the default Limit of 0), UUID updates for each item on the popular repositories list were not being applied. As "nothing" was found in the Data, despite a count of 1 being returned.
- Add a popular repository
- Check that the UUID is now returned in the response
- This will also be evident in the UI by the "Remove" button being visible on the popular repositories view.
=> Fixes 2588: Existing popular repositories not found error

configs/config.yaml.example, deployments/deployment.yaml, pkg/config/config.go, pkg/notifications/client.go
so we can disable it in prod
in one terminal: 
```
make kafka-topic-consume KAFKA_TOPIC=platform.notifications.ingress
```
in another:
``` go run cmd/content-sources/main.go api consumer ```
Then create a repo for introspection:
```
curl -X POST --location "http://localhost:8000/api/content-sources/v1.0/repositories/" \
-H "x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiIxIn0sImFjY291bnRfbnVtYmVyIjoiMSIsImludGVybmFsIjp7Im9yZ19pZCI6IjEifX19Cg==" \
-H "x-Rh-Insights-Request-Id: 9876" \
-d "{
\"name\": \"pulp3.16-8\",
\"url\": \"http://yum.theforeman.org/pulpcore/3.16/el8/x86_64/\",
\"snapshot\": false
}"
```
You should see no messages comes through.   Finally, turn it on:
``` OPTIONS_ENABLE_NOTIFICATIONS=true  go run …
```
=> Fixes 2717: add config to turn off notifs

configs/config.yaml.example
Removed duplicate pulp key in config.yaml.example that was causing issues when running the app for the first time.
=> Fixes 2777: removed duplicate key from config example

pkg/tasks/queue/pgqueue.go
Previously the db pool max limit was defaulting to 8 in ephemeral.  This wasn't enough for 2 tasks to run at the same time, due to needing a connection for:
* heartbeat update
* cancel listener
* updating payloads
* finishing the task
If enough of these things happened at once, it could exceede 8.
ci passes
=> Fixes 2776: set max pg pool for task db

pkg/dao/repository_configs.go, pkg/dao/snapshots.go, pkg/handler/repositories.go, pkg/handler/repositories_test.go
In PR #414, I mistakenly set context on a shared struct. This means that unless the context is manually reset by using `InitializePulpClient` before calling the `repoConfig.List` or `repoConfig.Fetch` dao methods, the request will fail with
`{"errors":[{"status":500,"title":"Error fetching repository","detail":"Get \"http://cs-pulp-api-svc.content-sources-stage.svc.cluster.local:24817/pulp/api/v3/status/\": context canceled"}]}`
This changes makes it so `context.TODO()` is used instead of the propagated context. This is only a quick and temporary fix to unblock things for now.
1. Fetch a repository
2. Introspect the same repository
3. Without this change, the introspection will fail with the 500 error.
=> Refs 2615: don't propagate canceled context

.github/pull_request_template.md
Production doesn't use pulp currently, lets add a reminder to test the pr without it
=> Build: Add reminder to test without pulp

pkg/dao/repository_configs.go, pkg/dao/repository_configs_test.go
Seeing error where if pulp isn't enabled, certain API endpoints are broken because there are dao functions that query pulp. This checks if snapshots are enabled in all of those places before querying pulp.
Turn off pulp and see if the errors are still present when listing/fetching repositories.
=> Fixes 2890: don't query pulp if not enabled

build/Dockerfile
Switches to using the ubi-micro container, which appears to have everything we need other than a ca-trust, which we can copy from ubi-minimal
This reduces our security footprint and potential attack vectors
tests pass
=> Build: use ubi-micro

deployments/deployment.yaml, pkg/config/config.go, pkg/rbac/client_wrapper.go, pkg/rbac/client_wrapper_test.go, pkg/test/handler/utils.go, scripts/header_org_admin.sh
Removes the setting that enables/disables "org admin rbac skip", but keeps the functionality i.e. it is permanently enabled. This allows a user with the org admin field set to true to skip the rbac check.
1. In your `config.yaml` set `clients: rbac_enabled` to true.
2. When your start the server, start it with the `mock_rbac` argument. i.e. `go run cmd/content-sources/main.go api consumer instrumentation mock_rbac`
1. GET repositories with a user that does not have read permissions and the org admin field is _false_. You should get a 401. For example `./scripts/header.sh <org_id> usernoperms` will generate the identity.
3. GET repositories with a user that does not have read permissions and the org admin field is _true_. You should get a 200 response. For example …
=> Fixes 2450: remove org admin skip setting

deployments/deployment.yaml
Rename the kafka-consumer deployment prior to adding alerting around the pods
tests pass?
=> Refs 2675: rename kafka-consumer deployment

deployments/deployment.yaml
Sets the number of replicas via a parameter so it can be adjusted easily
Tests pass?
=> Refs 2711: set replicas via parameter

.github/workflows/title.yml
Tries to prevent "Fixes 123,Fixes 456: summary" titles when doing multiple issues, but keep "Fixes 123,456: summary"
=> Build: Fix title regex to prevent bad multi issues

pkg/handler/features.go
Adding check so that if a feature is not enabled, it is also not accessible
=> Refs 2190: adding enabled check to accessible

pkg/tasks/worker/worker.go, pkg/tasks/worker/worker_pool_test.go
Previously if a task paniced for some reason, the worker routine would get 'stuck' and refuse to process anything else.  Now the task is marked as failed and the worker can continue to pick up another task.
modify the pkg/taskss/introspection.go  to panic sometimes or all the time:
```
if rand.Int()%2 == 0 {
panic(fmt.Errorf("You are unlucky!!"))
}
```
Create some repository with with snapshotting turned off (for simplicity)
```
curl -X POST --location "http://localhost:8000/api/content-sources/v1.0/repositories/" \
-H "x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiJqdXN0aW4ifSwiYWNjb3VudF9udW1iZXIiOiIxMTQ4NjU4OSIsImludGVybmFsIjp7Im9yZ19pZCI6IjE2Nzg4NjE2In19fQo=" \
-d "{
\"name\": \"errata\",
\"url\": …
```
=> Fixes 2474: Recover from tasks panics

pkg/pulp_client/task.go
Adds "canceling" as one of the possible states while polling a pulp task. Previously it was jumping to the default case of "Pulp task with unexpected state" and logging an error.
If you search for "canceling" [here in the pulp docs](https://docs.pulpproject.org/pulpcore/restapi.html#tag/Tasks/operation/tasks_list), you can see it is a valid state.
I can't find a reliable way to reproduce this, but it's a very small and simple change.
You can try
1. Creating a larger repo like epel 9, with snapshot enabled.
2. Canceling that task using the cancel endpoint (`/tasks/:uuid/cancel/`), and the `last_snapshot_task_uuid` from the create response.
3. You may or may not see the new state logged.
=> Fixes 2768: add canceling state to PollTask

pkg/config/config.go
=> Refs 3053: debug bucket name

deployments/deployment.yaml, pkg/config/config.go
Change to a new bucket name for our clowder provided resource.  The previous name was reused across buckets resulting in both buckets having the same 'name' internally.
IQE tests Pass
=> Refs 3053: Move to new bucket name

pkg/dao/repositories.go, pkg/dao/repositories_test.go
even if failed counts has been reached
As public repos should never fail  in the real world, some action may need to be taken, and we can retry.
We add RHEL repos before they are actually on the cdn, which means it can fail introspection for some time before its officially there.  Once it is, we want to introspect it properly.
I wrote a test to test this, i think test passing is sufficient.
=> Fixes 3081: always intropsect public repos

pkg/external_repos/external_repos.json
Google aarch64 repositories don't need to be introspected yet, as we don't build aarch64 images for google cloud.
=> Fixes 3066: introspect aarch64 repositories

deployments/jobs.yaml
I believe this would cause it to be triggered in stage
=> Refs 3050: trigger job in stage

pkg/external_repos/introspect.go
Found another place where its checking this
=> Refs 3081: ignore failed intro count for public repos

cmd/repair_latest/main.go, deployments/deployment.yaml, deployments/jobs.yaml, pkg/pulp_client/interfaces.go, pkg/pulp_client/pulp_client_mock.go, pkg/pulp_client/rpm_repository_version.go
and delete newest version if does not match latest snapshot
Currently in stage we have a couple issues, stemming from a repository snapshotting, and the publish failed due to a missing metadata file (that is downloaded, not generated).  
So for each red hat org's repository, we grab the latest_version_href from pulp and trigger a repair.  If this latest version doesn't match the repo's latest snapshot, we delete it. 
You might edit the redhat_repo.json file and delete all except for the `Red Hat Ansible Engine 2 for RHEL 8 x86_64 (RPMs)` repo.  
Run 
```make repos-import```
```go run cmd/external_repos/main.go nightly-jobs```
This will sync the red hat repo.   Then run:
```go run cmd/repair_latest/main.go --force```
=> Refs 3050: repair redhat repos

deployments/deployment.yaml, deployments/jobs.yaml
I thought `            inheritEnv: true`   would help, but i guess not!
=> Refs 3050: set env variables on repair job

api/docs.go, api/openapi.json, deployments/deployment.yaml, pkg/api/api.go, pkg/dao/interfaces.go, pkg/dao/repository_configs.go, pkg/dao/repository_configs_mock.go, pkg/dao/repository_configs_test.go, pkg/dao/snapshots.go, pkg/dao/snapshots_mock.go, pkg/dao/snapshots_test.go, pkg/handler/admin_tasks_test.go, pkg/handler/api.go, pkg/handler/api_test.go, pkg/handler/features_test.go, pkg/handler/popular_repositories_test.go, pkg/handler/public_repositories_test.go, pkg/handler/repositories.go, pkg/handler/repositories_test.go, pkg/handler/repository_parameters_test.go, pkg/handler/repository_rpms_test.go, pkg/handler/snapshots.go, pkg/handler/snapshots_test.go, pkg/handler/task_info_test.go, pkg/middleware/enforce_identity.go, pkg/utils/utils.go
Adds an endpoint that returns the GPG key of a repository as a file.
Also adds updates the fields in the config.repo file that is returned by the config.repo file endpoint.
1. Create a repository with and without a GPG Key
2. Query the `repositories/:uuid/snapshots/:snapshot_uuid/config.repo` and `repositories/:uuid/gpg_key`
3. Verify the correct returns.
=> Fixes 2616: add gpg key file endpoint

pkg/dao/repository_configs.go
and not current_date
1.  ```make repos-import```
2.  adjust SnapshotInterval in value_constraints.go to 0
3. run  ```go run ./cmd/external-repos/main.go nightly-jobs```   Notice snapshot tasks get created
4. wait for them to finish
5. run  ```go run ./cmd/external-repos/main.go nightly-jobs```  again, Notice snapshot tasks get created. Without this pr, you wouldn't see them
=> Fixes 3033: calculate timestamp to snapshot based off now()

pkg/dao/snapshots.go, pkg/dao/snapshots_test.go
We want to remove any nonalphanumeric characters from the label the config.repo file and replace with an underscore.
1. Sync a repository with a name that has nonalphanumeric characters, like parentheses. 
2. Fetch the config.repo file from the `/respositories/:uuid/snapshots/:snapshot_uuid/config.repo` endpoint.
3. The label (the title in the square brackets) should have all the nonalphanumeric characters replaced with an underscore.
=> Fixes 3032: replace nonalphanumeric chars in repo config ID

pkg/models/repository_configuration.go, pkg/models/repository_configuration_test.go
We weren't specifying the association foreign key correctly, so we were getting a 'random' snapshot, and not the latest
Generate a repo with multiple snapshots, view the json when fetching a repo and make sure that 'last_snapshot_uuid' matches 'last_snapshot.uuid'
=> Fixes 3184: query last_snapshot correctly

deployments/jobs.yaml
We fixed a pulp issue that was preventing repairs from working
none
=> Refs 3053: repair for the last time

api/docs.go, api/openapi.json, deployments/deployment.yaml, pkg/dao/snapshots.go, pkg/handler/repositories.go, pkg/handler/repositories_test.go, pkg/middleware/enforce_identity.go
Changes the gpg key file endpoint to `repository_gpg_key/:uuid` so that it can be whitelisted i.e. skip auth
1. Deploy PR in ephemeral
2. Create repository with GPG key and snapshot enabled
3. Use the GPG Key URL in the config.repo file to open a tab (in browser) to the GPG Key
4. Should be able to open the URL in your browser despite not having the correct auth
=> Fixes 3189: change gpg key file endpoint

.github/workflows/content-sources-actions.yml
- govet and gofmt are already tested by golangci-lint
- there's also no need to explicitly enable tests in the args for the golangci-lint action because we have a config file for it
tests pass
=> Fixes 3271: remove redundant lint CI tests

.rhcicd/pr_check.sh, deployments/deployment.yaml, pkg/config/config.go, pkg/external_repos/redhat_repos.go, pkg/external_repos/redhat_repos.json
Provide an env variable that can be used to exclude some or all of the red hat repos from being loaded.  
In dev,
In between each test, a ```make compose-clean compose-up``` is needed to clear out what is there.
With backend and frontend running:
```
go run ./cmd/external-repos/main.go import
```
should still import all red hat repos (can check in the UI).  
```
OPTIONS_REPOSITORY_IMPORT_FILTER="small" go run ./cmd/external-repos/main.go import
```
should import only 1 small ansible redhat repo
```
OPTIONS_REPOSITORY_IMPORT_FILTER="none" go run ./cmd/external-repos/main.go import
```
should cause no red hat repos to be imported.
For QE, you can use with bonfire: 
--set-parameter content-sources-backend/OPTIONS_REPOSITORY_IMPORT_FILTER=small
--set-parameter …
=> Fixes 3250: provide filter for excluding loaded RH repos

pkg/dao/repository_configs_test.go, pkg/models/repository.go
This adds a simple check on the model for repositories.URL to see if it is a valid. 
Manually testing can be done by attempting to hit any of the repositories create/edit endpoints with an incorrect URL. 
Invalid URL example: repo_2_url  
Valid URL example: https://repo_2_url.org
=> Fixes 3037: Adds a url validity check.

pkg/config/config.go, pkg/middleware/enforce_identity.go, pkg/middleware/enforce_identity_test.go, pkg/middleware/enforce_json.go, pkg/router/route.go
Adds check to middleware to reject requests if the Org ID is -1
Make a request to any endpoint with an identity header with Org ID set to -1. Response should return a 403.
=> Fixes 3016: Reject requests with org id of -1

pkg/config/config.go, pkg/middleware/enforce_identity.go, pkg/middleware/enforce_identity_test.go, pkg/middleware/enforce_json.go, pkg/router/route.go
This reverts commit 2802ea28c793aec866a79f89115d06e75adc2729.
=> Refs 3016: revert org id check

pkg/router/route.go
Fixes `missing x-rh-identity-header` in /metrics endpoint
=> Refs 3016: fix order of middleware for metrics endpoint

pkg/handler/repositories.go, pkg/handler/repositories_test.go
Prevents snapshots on non-snapshot enabled repos
=> Fixes 1973: Prevents snapshots on non-snapshot enabled repos

api/docs.go, api/openapi.json, pkg/api/snapshots.go
Found a typo in the response during testing, this changes: 
repository_uuid**s** => repository_uuid
None
=> Fixes 1973: Typo in model

pkg/handler/api.go, pkg/handler/api_test.go
Updates limit in API request to `DefaultLimit` (100) if ever set to 0
Test any listing API endpoint (`/repositories`, `/popular_repositories`, `/repositories/:uuid/rpms`, etc) and set the limit to 0. Should not panic and update limit to default of 100.
=> Fixes 3252: listing with limit=0 causes divide by 0 panic

.github/workflows/content-sources-actions.yml
Added Github Action to check for out of order database migrations.
If the content in `db/migrations.latest` does not reflect the timestamp of the newest added set of migration files in `db/migrations`, the job will fail. If these timestamps match or if there are no new migrations, the job will succeed. 
Can test by:
- Adding a set of test migration files with an earlier timestamp than the latest and not updating the `db/migrations.latest`. This should cause the job to fail.
- Removing the test migration files. The `db/migrations.latest` content should reflect the newest added set of migration files. This should cause the job to succeed.
- Adding a set of test migration files with a timestamp that matches the timestamp in `db/migrations.latest`. This should cause the job to succeed.
=> Fixes 3232: add gh action to prevent out of order migrations

pkg/dao/repositories.go, pkg/dao/repositories_test.go, pkg/tasks/queue/pgqueue.go, pkg/tasks/queue/pgqueue_test.go
When introspecting, certain error messages may contain non-UTF8 characters. The database doesn't like non-UTF8 characters. This removes those characters before the error messages are inserted into the database.
1. Assuming [this yummy PR](https://github.com/content-services/yummy/pull/21) is not integrated into the backend, introspect this repository: https://fixtures.pulpproject.org/rpm-pkglists-updateinfo/
2. Without this PR you will get the error: "invalid byte sequence for encoding \"UTF8\": 0xf4 0x62 0x20 0x28 (SQLSTATE 22021)"
3. With this PR, you should get no error
=> Fixes 3231: remove non-UTF8 chars from introspection error

pkg/config/value_constraints.go, pkg/dao/repository_configs_test.go, pkg/dao/snapshots.go, pkg/dao/snapshots_test.go
The repository config file wasn't providing the correct gpg key path for red hat repos. All the red hat repos have the same gpg key path, so this hard codes that value. 
1. Import red hat repos and create a snapshot
2. Fetch the config.repo file from the `/repositories/:uuid/snapshots/:snap_uuid/config.repo/` endpoint
3. The config.repo file should have the red hat gpg key path
=> Fixes 3171: add gpg key path for red hat repos

pkg/handler/snapshots.go, pkg/handler/snapshots_test.go
To properly show the gpg key url from the gateway
1.  create a repo with a gpg key set, and snapshotting enabled
2.  fetch your repos list to get uuids for the repo and latest snapshots: GET http://localhost:8000/api/content-sources/v1/repositories/
3.    fetch this url: http://localhost:8000/api/content-sources/v1/repositories/60dd106b-d08e-436a-bf34-53180713d4bc/snapshots/8a68fc2d-c8eb-4046-8c56-df44603f8206/config.repo
replacing the UUIDs for the repo & snapshot UUID. Notice the URL is likely https://localhost:8000/.
4.  now fetch the url with the header:   'X-Forwarded-Host: example.com'
you should see the url change to  https://example.com/
=> Fixes 3170: use x-forward-host hdr for repo config

deployments/deployment.yaml
As part of switching to new central pulp server we need to switch to a new s3 bucket for domain creation.  All previous content will be deleted
none
=> Refs 3372: switch to new s3 bucket name

.rhcicd/pr_check.sh, pkg/tasks/repository_snapshot.go, pkg/tasks/repository_snapshot_test.go
pass the remote href when doing a sync, as pulp has an rbac bug preventing us from using the remote on the repo
integration tests pass
=> Fixes 3402: pass remote href on sync

pkg/external_repos/redhat_repos.json
adds the base arm64 repos 
configure a cdn cert in the config if you have one, if you don't reach out to me to get one.
load in the repos:
`make  repos-import`
trigger the sync:
```go run cmd/external-repos/main.go nightly-jobs```
wait a while
make sure that all repos have snapshots.
=> Fixes 3423: add arm64 repos

pkg/dao/interfaces.go, pkg/dao/snapshots.go, pkg/dao/snapshots_mock.go, pkg/dao/snapshots_test.go, pkg/tasks/repository_snapshot.go, pkg/tasks/repository_snapshot_test.go
during snapshot, and if one is found use that to continue.  
This helps the situation where some issue occurs and the pulp repo sync is successful, but the task dies, panics, or the publication creation fails.  If the repo hasn't changed at the next snapshot time, no new snapshot gets created.  With this change, the previously created repo version is re-used if there isn't a new one during the sync.
I couldn't figure out a way to simulate this, so instead we can manually clear the db.  On a fresh empty db:
1)  create  a repo with snapshotting enabled.  Wait for it to finish snapshotting
2) within the database delete the snapshot:    `make db-cli-connect`
```
delete * from snapshots;
```
3) trigger the snapshot manually:
```
POST http://localhost:8000/api/content-sources/v1.0/repositories/6 …
```
=> Fixes 3144: check for orphan repo versions

pkg/external_repos/redhat_repos.json
This fixes an incorrect arch i had added.  
Check out master, run `make repos-import`   notice the "Red Hat Ansible Engine 2 for RHEL 8 ARM 64 (RPMs)" repo has an arch of x86_64. 
Checkout this PR, run `make repos-import` again, notice its not correct
=> Refs 3423: fix arm64 repo arch

pkg/tasks/repository_snapshot_test.go
fix broken unit test due to commits merge
tests pass
=> Refs 3144: fix broken unit test

.github/workflows/content-sources-actions.yml, compose_files/pulp/docker-compose.yml, go.mod, go.sum
Updates our compose files to configure pulp to use /pulp/api
1.  checkout PR
2. make compose-clean compose-up
3. make run
4. create a repo with snapshotting turned on, verify the snapshot gets created properly.
=> Build: Update to use new pulp api path

.rhcicd/pr_check.sh
We do not want to run any full introspection tests in pr checks.
There are simple checks within other CRUD tests.
there are now two we need to skip
so use just "introspection" to make it generic.
Test pass
=> Fixes 3482: Do not run introspection tests

pkg/dao/task_info.go, pkg/dao/task_info_test.go
Fixes a query that didn't properly limit joined repo configs to the proper org id.
Create two repos pointing to the same URL in two different orgs.
Fetch the resulting introspect task for each repo in each org
verify the repo uuid and name matches from the expected org
=> Fixes 3492,3371: properly join repo to task

pkg/cache/redis.go
change the pulp content cache path
none, test pass
=> Refs 3372: change pulp content path cache key

api/docs.go, api/openapi.json, go.mod, go.sum, pkg/api/repository_environments.go, pkg/api/repository_package_groups.go, pkg/api/snapshots.go, pkg/dao/environments.go, pkg/dao/environments_mock.go, pkg/dao/environments_test.go, pkg/dao/interfaces.go, pkg/dao/package_groups.go, pkg/dao/package_groups_mock.go, pkg/dao/package_groups_test.go, pkg/dao/rpms.go, pkg/dao/rpms_test.go, pkg/handler/api.go, pkg/handler/environments.go, pkg/handler/environments_test.go, pkg/handler/features_test.go, pkg/handler/package_groups.go, pkg/handler/package_groups_test.go, pkg/handler/repositories.go, pkg/handler/repositories_test.go, pkg/handler/rpms_test.go
- ~~Built on this PR: https://github.com/content-services/content-sources-backend/pull/517. Do not merge before this PR has merged.~~
- ~~Waiting for this dependency PR to finish and merge: https://github.com/content-services/tang/pull/3~~
- Adds endpoints to search environments and package groups of snapshots, by name.
- Also fixes issue where ID metadata was not being exposed for package groups and environments. 
- Functionality is the same as the existing searching endpoints for repositories. The only difference is you must send a snapshot UUID in the request body (instead of a repository UUID or URL).
1. Create a snapshot
2. These two repos are good for testing: https://rverdile.fedorapeople.org/dummy-repos/comps/. So are epel and rh repos.
3. Search package groups by name using `POST …
=> Fixes 2983: add api for searching snap comps groups

cmd/retry_failed_tasks/main.go, deployments/deployment.yaml, deployments/jobs.yaml
Adds a job to update the current failed "delete-repository-snapshot" tasks so that they get requeued by the new retry system.
1. In your config, set `tasking.heartbeat: 5s` and `tasking.retry_wait_upper_bound: 10s`.
2. Create a repository with a snapshot.
3. Run `podman stop cs_pulp_api_1` so you can no longer make requests to pulp without error.
4. Try to delete the repository.
5. It will fail and retry 3 times and then stop. 
6. Run `go run cmd/retry_failed_tasks/main.go --force`
7. You should see the failed task updated and retry 3 more times.
=> Fixes 3517: job to retry existing failed tasks

pkg/pulp_client/client.go, pkg/pulp_client/content_guard.go, pkg/pulp_client/domains.go, pkg/pulp_client/orphans.go, pkg/pulp_client/rpm_distributions.go, pkg/pulp_client/rpm_publication.go, pkg/pulp_client/rpm_remote.go, pkg/pulp_client/rpm_repositories.go, pkg/pulp_client/rpm_repository_version.go, pkg/pulp_client/task.go
Establishes new pattern for handling pulp api response errors to ensure nil check and include the response body in the error. 
1. Cause a pulp error somehow. One way is to do `podman stop cs_pulp_api_1`, then try to sync a repository.
2. You should see the error message in the logs includes the body response.
3. Also look through the pulp client package and see if I missed adding this response pattern to the responses.
=> Fixes 3346: new pattern for pulp response errors

deployments/deployment.yaml
previous commit had a mistake when escaping bools
=> Refs 3255: fix escaping of bool

pkg/dao/repository_configs.go, pkg/handler/repositories.go, pkg/handler/repositories_test.go
Snapshot create-on-edit is inconsistent between API and UI 
This was caused by the URL not being checked correctly before enqueueing snapshot/introspect tasks. 
This card corrects that issue.
- From the api or UI, update a repository (patch) with the original URL in the request.  
Without this change, introspection/snapshot tasks will always be enqueued. 
With it, the tasks will correctly, be ignored, as those two tasks are contingent on a URL change.
=> Fixes 3353: Snapshot  inconsistent for API/UI

.rhcicd/pr_check.sh
In smoke tests I see `DEPLOY_TIMEOUT:-"600` coming from appsre:
`$ bonfire deploy ${APP_NAME} ${DEPLOY_ARGS} --source=appsre --ref-env ${IQE_REF_ENV} --namespace ${NAMESPACE} --timeout ${DEPLOY_TIMEOUT:-"600"} ${FRONTEND_ARG}`
but deploy time seem too short:
`2024-02-12 20:48:10 [   ERROR] [          thread-358] [clowdjobinvocation/create-contentsources-user] timed out waiting for resource to be ready, details:   clowdjobinvocation/create-contentsources-user not ready, status conditions:`
Frontend already has `export DEPLOY_TIMEOUT="900"  # 15min` so I will try that for backend.
pr checks pass
=> Build: increase deployment timeout to 900

pkg/config/config.go
Fixes a typo in the default value for this config settings.  If the default isn't set, the config reader doesn't actually use the value.
=> Refs 3255: correct mistaken default config value

go.mod, go.sum
Updates yummy to latest version. Includes fix where repo comps with certain file extensions or of group_gz data type were not detected.
These repos should be able to be introspected successfully: 
- http://yum.theforeman.org/pulpcore/3.16/el7/x86_64/
- http://yum.theforeman.org/pulpcore/3.16/el8/x86_64/
=> Refs 3539: update yummy

pkg/dao/snapshots.go
adds  ssl options to repo config
```
sslclientcert=/etc/pki/consumer/cert.pem
sslclientkey=/etc/pki/consumer/key.pem
```
snapshot a repo, copy/download the repo config, look for the piece above
=> Fixes 3612: add sslclient options to yum config

configs/config.yaml.example
Comment out cdn cert by default
comment out feature users/accounts so it works for all by default
=> Build: update example config to work out of the box

configs/config.yaml.example, deployments/deployment.yaml, pkg/config/config.go, pkg/handler/features.go, pkg/handler/features_test.go, pkg/handler/repositories_test.go
Adds org ids as a way to make features accessible.
edit your config.yaml and edit/add:
```
features:
snapshots:
enabled: true #true
accounts: 
users: 
organizations: ["FOO"]
```
use header.sh to test the org_id.  this should work:
```
curl -X POST --location "http://localhost:8000/api/content-sources/v1.0/repositories/"       -H "Content-Type: application/json"     -d "{
\"name\": \"needed errata\",
\"url\": \"https://jlsherrill.fedorapeople.org/fake-repos/needed-errata/\",
\"gpg_key\": \"\",
\"snapshot\": true
}"   -H "`./scripts/header.sh FOO 1 1`"
```
This should fail:
```
curl -X POST --location "http://localhost:8000/api/content-sources/v1.0/repositories/"       -H "Content-Type: application/json"     -d "{
\"name\": \"needed errata\",
\"url\": …
```
=> Fixes 3629: add org id to features config

README.md, api/docs.go, api/openapi.json, pkg/api/public_repositories.go, pkg/dao/repositories.go, pkg/handler/public_repositories_test.go
Simply removes the UUID from the public_repos response.
- Get /public_repositories/ list, check that the UUID is no longer present.
=> Fixes 3654: Remove UUID from public repos

pkg/cache/redis.go, pkg/config/config.go
and resets cache keys
to check the default, apply this patch:
```
diff --git a/cmd/external-repos/main.go b/cmd/external-repos/main.go
index 6eb17810..26065f99 100644
--- a/cmd/external-repos/main.go
+++ b/cmd/external-repos/main.go
@@ -27,6 +27,8 @@ func main() {
config.Load()
config.ConfigureLogging()
+       fmt.Printf("FOO: %v", config.Get().Clients.Redis.Expiration.Rbac)
+
err := db.Connect()
if err != nil {
log.Panic().Err(err).Msg("Failed to connect to database")
```
then when you run: 
```
go run cmd/external-repos/main.go 
{"level":"warn","time":"2024-02-29T15:11:32-05:00","message":"Caching is disabled."}
FOO: 0s
```
With this change, you should see the default of 60s.
Also you can look in redis itself.
Before:
```
podman run -it docker.io/library/redis   redis-cli   -h …
```
=> Fixes 3142: fixes default expiration on redis cache

api/docs.go, api/openapi.json, pkg/dao/interfaces.go, pkg/dao/snapshots.go, pkg/dao/snapshots_mock.go, pkg/dao/snapshots_test.go, pkg/handler/snapshots.go, pkg/handler/snapshots_test.go
This changes 3 apis:
/repositories/snapshots/for_date/
/repositories/{uuid}/snapshots/{snapshot_uuid}/config.repo
to
/snapshots/for_date
/snapshots/{snapshot_uuid}/config.repo
make requests to the new 2 apis
=> Fixes 3720: standardize snapshot routes

cmd/external-repos/main.go, pkg/dao/task_info.go, pkg/dao/task_info_test.go, pkg/handler/task_info.go
allows all orgs to fetch tasks for RH repos
Ensure a RH repo has been snapshotted, List tasks:
GET /api/content-sources/v1.0/tasks/
and then fetch one's UUID:
GET /api/content-sources/v1.0/tasks/UUID/
Bonus points if you try to cancel a RH task:
POST /api/content-sources/v1.0/tasks/uuid/cancel/
(you shouldn't be able to)
=> Fixes 3664: support listing/fetching RH tasks

pkg/dao/repositories.go, pkg/dao/repositories_test.go
previously we would 'cleanup' the url when you manually trigger introspection, but this was broken during a refactor
```
go run cmd/external-repos/main.go introspect --force https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/ansible/2/os
```
Without this pr, the command will do nothing, with you should see:
```
5:44PM DBG Introspecting https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/ansible/2/os/
```
also during ephemeral deployments you should see the this ansible repo get introspected, without this, its always pending
=> Fixes 3740: clean url during manual introspect

deployments/deployment.yaml
Since with the default configuration in ephemeral, we do require pulp currently
deployment passes
=> Build: move pulp to a ordinary dependency

api/docs.go, api/openapi.json, go.mod, go.sum, pkg/api/rpms.go, pkg/dao/interfaces.go, pkg/dao/rpms.go, pkg/dao/rpms_mock.go, pkg/dao/rpms_test.go, pkg/handler/rpms.go, pkg/handler/rpms_test.go
adds a new snapshot rpm list api:
```// @Router       /repositories/{uuid}/rpms [get]```
Create a repo and let it snapshot, then fetch the rpms:
```
GET http://localhost:8000/api/content-sources/v1.0/snapshots/0e6c9e7f-e021-4710-8021-f59cb9c56d82/rpms?search=foo&limit=1
```
=> Fixes 2940: add snapshot rpm list api

pkg/pulp_client/domains.go
fixes this glitchtip, which occurs when updating a domain fails:
:runtime error: invalid memory address or nil pointer dereference
Module "github.com/content-services/content-sources-backend/pkg/tasks/worker", line 221, in (*worker).recoverOnPanic
Module "github.com/content-services/content-sources-backend/pkg/pulp_client", line 66, in (*pulpDaoImpl).UpdateDomainIfNeeded
Module "github.com/content-services/content-sources-backend/pkg/tasks", line 89, in (*SnapshotRepository).Run
Module "github.com/content-services/content-sources-backend/pkg/tasks", line 54, in SnapshotHandler
Module "github.com/content-services/content-sources-backend/pkg/tasks/worker", line 174, in (*worker).process
tests pass
=> Fixes 3775: handle nil response for domain updating

compose_files/candlepin/Dockerfile, compose_files/postgres/init.d/create-multiple-dbs.sh, deployments/docker-compose.yml
switches to the candlepin:dev-latest image. 
Uses an init file to generate a 2nd db/user for the postgres container
=> Build: switch to official candlepin images

pkg/rbac/client_wrapper.go
Corrects the method used to check the cache error is "NotFound". The "NotFound" error is wrapped within the return error, and so `errors.Is(...)` must be used because it checks the wrapped errors and not just the top error.
1. In your config.yaml set `redis.expiration.rbac : 1s`.
2. Enable mock rbac. First, enable rbac in your config.yaml under `clients.rbac_enabled:  true`. Then, in your run arguments add `mock_rbac` i.e. `go run cmd/content-sources/main.go api consumer mock_rbac`.
3. Hit the repositories list endpoint. Without this change, you'll get the "not found" error.
=> Fixes 3668: remove err log for cache miss

deployments/docker-compose.yml
=> Build: handle selinux on postgres mount

pkg/external_repos/redhat_repos.json
fixes a repo label
on main:  ```make repos-import```
```
select label from repository_configurations where name = 'Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)';
```
switch to the branch
```make repos-import```
```
select label from repository_configurations where name = 'Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)';
```
You should see the updated label
=> Fixes 3813: correct repo label for 9 appstream

api/docs.go, api/openapi.json, pkg/handler/snapshots.go
The path only has a single parameter, being the identifier of the snapshot.
---
Error I encountered:
```
+ /home/sanne/go/bin/go1.20.14 generate -mod=mod ./...
error generating code: error creating operation definitions: path '/snapshots/{snapshot_uuid}/config.repo' has 1 positional parameters, but spec has 2 declared
exit status 1
```
with
```
//go:generate go run -mod=mod github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen --config client.cfg.yaml content-sources.v1.json
```
---
=> Fixes 3876: remove unused path param in config.repo spec

deployments/testing-integration.yaml
New sel image is failing the test pipeline because it does not have a controlled shutdown command, making the pod stuck and resulting into timeout.
=> Refs IQE-2748: Revert old sel testing image backend

pkg/external_repos/external_repos.json
Image builder switched to rolling URLs for the latest minor in order to find snapshots more easily. As a result the package search now happens against the rolling URLs.
=> Refs 2950: add rolling distros to default introspection repos

pkg/config/config.go
Stage/prod dbs need to use ssl, which wasn't being done because we don't have a ca cert.  Lets try using the one clowder is giving us for our db.
Don't think there is an easy way  to test this
=> Fixes 3937: use clowder rds ca for tangy db

pkg/config/config.go
This reverts commit b2f2940fa8ef8bcb71b07fe0a2c4e151aefa7945.
After the previous change, now the api seems to be timing out
=> Refs 3937: Revert 'use clowder rds ca for tangy db (#629)'

pkg/config/config.go
Set the ca cert for the tangy connection if clowder is present
=> Fixes 3937: use clowder rds ca for tangy db (#629)

pkg/dao/repository_configs.go
Create all red hat repos as 'public' so they can be searched just like public repos.
In master, revert this change:
https://github.com/content-services/content-sources-backend/commit/542f8f32f1c2770609b5bb2c77b62c78ff72a069
then run:
```make compose-clean compose-up repos-import```
Now, verify that some RH repos are not public:
```
```
now check out this PR and re-run ```make repos-import``` and rerun the query:
```
```
all RH repos should now have public  set to true.
For QE, this will be hard to fully test outside of stage, as the new deployments have all the RH repos in external_repos.json, so they will be public on new deployments.
=> Fixes 3939: create/update RH repos as public

pkg/dao/repository_configs.go, pkg/dao/repository_configs_test.go
Fixes case where repository status is "Unknown" if a snapshot task never reaches a running state 
- When a snapshot task is `pending` or `running`, the status in the repository response should show `Pending` and the UI should show it's `In progress`
- These `Pending` repositories should be displayed when filtering on status `Pending`
- I tested this by adding a repository and snapshotting, then manually changing the snapshot task status to `pending` in the db and verifying that the status shown in the repository status is `Pending`, but there is probably a better way to simulate this case
- EDIT: see [Ryan's comment](https://github.com/content-services/content-sources-backend/pull/634#issuecomment-2051854053) for a better way to test this
=> Fixes 3940: handle pending snapshot task

pkg/dao/environments.go, pkg/dao/environments_test.go, pkg/dao/helpers.go, pkg/dao/package_groups.go, pkg/dao/package_groups_test.go, pkg/dao/rpms.go, pkg/dao/rpms_test.go, pkg/handler/environments.go, pkg/handler/package_groups.go, pkg/handler/rpms.go, pkg/handler/rpms_test.go
- Returns a 400 response code if a repository / snapshot is not found for these search endpoints:
```
/rpms/names
/package_groups/names
/environments/names
/snapshots/rpms/names
/snapshots/package_groups/names
/snapshots/environments/names 
```
- Updates the error response for requests with missing urls / uuids to return a 400 instead of a 500
- Also adds a handler test for DetectRpms because I realized I forgot to do that :) 
- Make a request to each endpoint with an incorrect uuid / url, each should return 400
- Requests with no uuid / url to these endpoints should also return 400
=> Fixes 3766: add check for missing repos/snapshots

deployments/deployment.yaml, pkg/handler/repositories.go
I'm pretty sure this is the reason we're not getting alerts for service errors. I noticed in the logs that sentry was being configured for the task worker, but not for the service. The name for the task worker is "content-sources-glitchtip". Both pods were working fine in ephemeral if I used an env variable.
I included an error log to verify if this works. If it does, I'll remove the error log in a followup.
Just merge and see I think
=> Refs 3897: fix sentry name

pkg/handler/repositories.go
The change in #644 seemed to correct the issue, so I'm removing the error log. Titled "Fixes" so the card closes.
None
=> Fixes 3897: remove test err log

.rhcicd/pr_check.sh
Recent errors in pr_checks (which use clowder venv):
`HTTP response body: Bad Request: x-rh-identity header has an invalid or missing org_id`
possibly related to authentication changes, e.g. certs required, but clowder and ephemeral users are not configured for cert auth, they are user name and password only.
Lets try if ephemeral's use of caddy containers solves that problem.
pr check runs OK
=> Refs 4035: set QE_ENV="ephemeral"

go.mod, go.sum, pkg/middleware/extract_status.go, pkg/router/route.go
This uses a custom lecho fork to accomplish two things:
1.  log slow requests at a higher log level
2.  do not treat non-500 errors as needing error level logging
2.  was kinda tricky.  We need another middleware that runs around lecho to properly parse the error into the correct struct, extract the correct status, and set that on the response.  Then lecho has to re-lookup the response to get the proper status code.  I will work on contributing 1. back to lecho, but i'm not sure if the changes for 2 make sense to?
to test 1:
add in a time.sleep(2*time.Second)  somewhere in a handler (like listRepositories).  Watch requests get logged at warn
to test 2:
in listRepositories add some code after the filter is parsed:
```
if filterData.Search == "foo" {
return ce.NewErrorResponse(500, "Error …
```
=> Fixes 4013,4008: Use custom lecho for enhanced logging

pkg/dao/rpms.go, pkg/dao/rpms_test.go
Previously introspecting large repos resulted in an error
Create a repo with URL https://mirror.web-ster.com/fedora/releases/40/Everything/x86_64/os/
Disable snapshotting to speed it up.
it will fail without this PR
=> Fixes 4044: fix introspection of large repos

README.md, mk/includes.mk, mk/mockery.mk, pkg/cache/cache.go, pkg/candlepin_client/interface.go, pkg/dao/interfaces.go, pkg/pulp_client/interfaces.go, pkg/tasks/client/client.go, pkg/tasks/queue/queue.go
Adds make command to install mockery and regenerate mocks
- Run `make mock`. This should install the latest version of mockery if it isn't already installed in the release directory and regenerate the mocks we have
=> Fixes 3793: add make command for mockery

pkg/external_repos/external_repos.json
adds the 9.4 repos  which will fail introspection currently, but should work soon
=> Build: Add rhel 9.4 repos

pkg/external_repos/redhat_repos.json
Adds some more rhel 8 and rhel 9 repository for snapahostting
go run cmd/external-repos/main.go nightly-jobs
wait a while for it to sync all the repos.  Navigate in the UI to red hat repos and make sure they were snapshotted.
For QE:  i'd just check a deployment and see that the new rhel repos are there (if anything)
=> Fixes 3919: Add additional red hat repos

pkg/dao/templates.go, pkg/handler/admin_tasks.go, pkg/handler/api.go
Changes filter/pagination parsing errors as info level logging instead of error
perform a request:
GET http://localhost:8000/api/content-sources/v1.0/templates/?limit=a
watch your server, it should show logging at INFO
=> Fixes 4055: treat filter/page param parse as info

cmd/content-sources/main.go, configs/config.yaml.example, pkg/config/config.go, pkg/config/config_test.go, pkg/config/logging.go, pkg/dao/interfaces.go, pkg/dao/metrics.go, pkg/dao/metrics_mock.go, pkg/dao/metrics_test.go, pkg/dao/rpms_mock.go, pkg/instrumentation/custom/collector.go, pkg/instrumentation/metrics.go, pkg/tasks/queue/pgqueue.go, pkg/tasks/queue/pgqueue_test.go
Adds new metrics:
* Average queue time of pending task
* Length in queue for the oldest pending task
* Number of pending tasks
Also:
* Increases default metric calculations to 30 seconds from 5
* makes interval for metric calculation configurable
* adds log level override for metrics so you can set the rest of the app to trace while metrics are set to debugging
on a new db:
```
make run
```
in another tab:
```
go run cmd/external-repos/main.go nightly-jobs
```
This will kick off a ton of tasks, you can monitor with:
```
curl localhost:9000/metrics | grep task_stats
```
This will update every ~30 seconds.
=> Refs 2422: Add pending task metrics

mk/repos.mk, pkg/external_repos/redhat_repos.json
Support importing only a subset of repos for testing rhel9 (for example), and a handy make target.
on a fresh db:  
```
make repos-import-rhel9
```
then check the red hat repos list and see only these two red hat repos
=> Build: add make repos-import-rhel9

cmd/content-sources/main.go, pkg/instrumentation/custom/collector.go, pkg/instrumentation/custom/collector_test.go, pkg/instrumentation/metrics.go
adds a metric to represent the status of the pulp connection.  
curl localhost:9000/metrics 
look for:
```
content_sources_PulpConnectivity 1
```
=> Refs 3565: add pulp connectivity metric

pkg/middleware/request_id.go
The previous pr: https://github.com/content-services/content-sources-backend/pull/637  had a bug where the request_id wasn't being set on the response in all cases (when one was specified). The result is that tasks didn't get their proper request_id
Run a curl request to create (and snapshot a repo):
UUID="1cf4b0b0-fc0a-11ee-8913-201e8814f721"
curl -H "x-rh-insights-request-id:$UUID"  http://localhost:8000/api/content-sources/v1/repositories/  -H "`./scripts/header.sh 1 1`"   -d '{"name":"foo", "url":"https://jlsherrill.fedorapeople.org/fake-repos/needed-errata/", "snapshot":true}'  -H "Content-Type: application/json"
And watch the server logs:
you should see a lot of:
```
request_id=1cf4b0b0-fc0a-11ee-8913-201e8814f721
```
Both at the api level and then as the task runs
Also check the …
=> Refs 1738: set request id header on response

pkg/instrumentation/metrics.go
Accidently had it in camel case instead of snake case
=> Refs 3565: correct pulp connectivity metric name

pkg/api/snapshots.go, pkg/dao/snapshots.go, pkg/dao/snapshots_test.go, pkg/handler/snapshots_test.go, pkg/tasks/update_template_distributions.go
- Updates the date in the request to /snapshots/for_date to be an alias of type time.Time
- Date can be formatted like either YYYY-MM-DD or 2024-05-02T00:00:00-04:00
- Frontend change for this as well to ensure template creation doesn't fail on the Set up date step, PR [here](https://github.com/content-services/content-sources-frontend/pull/256). <-- this is not needed anymore for this PR since both formats work, but will be once we remove support for YYYY-MM-DD in a following PR
- Test the /snapshots/for_date endpoint with a request like this, this should work:
```
{
"date": "2024-04-28T00:00:00-04:00",
"repository_uuids": ["1510694a-1bfa-479a-b596-4377261f3135"]
}
```
- This should also work:
```
{
"date": "2024-04-28",
"repository_uuids": ["1510694a-1bfa-479a-b596-4377261f3135"]
}
```
=> Fixes 3832: update date type in /snapshots/for_date

pkg/external_repos/redhat_repos.json
Duplicate/incorrect label was causing `make repos-import` to fail
1. Run `make repos-import`
2. Should not fail
=> Fixes 4160: fix incorrect red hat repo label

db/migrations/20240513101357_add_label_constraint_to_repository_configuration.up.sql
This label was duplicated before being fixed in #671 
The label needs to be updated as part of the migration, or the migration will fail.
1. Assuming your local DB has the latest migration (label uniqueness constraint), run `go run cmd/dbmigrate/main.go down --steps 1`
2. Update the redhat_repos.json to revert the change made in #671.
3. Run `make repos-import`
4. Run `go run cmd/dbmigration/main.go up` to run the uniqueness constraint migration.
5. The migration should not fail, and the label for this repository in repository_configurations should be correct.
=> Refs 4160: update label constraint migration to change label

pkg/candlepin_client/candlepin_client_mock.go, pkg/candlepin_client/content.go, pkg/candlepin_client/environment.go, pkg/candlepin_client/interface.go, pkg/tasks/update_template_content.go, test/integration/update_template_content_test.go
for custom repos
Adds overriding of custom content baseurls 
Follow the directions here: https://github.com/content-services/content-sources-backend/blob/main/docs/register_client.md
At the end you should have a client configured to use a  custom repository and a red hat repository.  You should now be able to 'dnf install' a package from the custom repo
=> Fixes 4093: Override candlepin environment paths

api/docs.go, api/openapi.json, go.mod, go.sum, pkg/dao/rpms.go, pkg/dao/rpms_test.go, pkg/handler/rpms.go
- Enables sorting on issued_date, updated_date, type, and severity for snapshot errata
- Dependent on this [tang PR](https://github.com/content-services/tang/pull/9) and a new tang release
- Create a repository and let it snapshot
- Make a request to list the snapshot errata and sort by issued_date, updated_date, type, and severity (asc or desc). Example request:`/snapshots/:uuid/errata?sort_by=type:desc`
- This should return a list of errata sorted by the specified field and direction
- Listing the snapshot errata with no sort_by parameter should still default to sorting by issued_date descending
=> Fixes 4009: snapshot errata should be sortable

api/docs.go, api/openapi.json, pkg/api/templates.go, pkg/dao/templates.go, pkg/dao/templates_test.go
adds a new parameter 'client_environment_id' to kafka template events & api responses
in local setup:  
```
KAFKA_TOPICS=platform.content-sources.template   make kafka-topic-consume  
```
now create a content template via the api/ui and watch the result:
```
Partition:0	content-type:application/cloudevents+json	null	{"specversion":"1.0","id":"14ebf3a8-1c8b-497a-9228-92a826452d81","source":"urn:redhat:source:console:app:repositories","type":"com.redhat.console.repositories.template-created","subject":"urn:redhat:subject:console:rhel:template-created","datacontenttype":"application/json","time":"2024-05-28T18:18:07.558203259Z","data":[{"uuid":"77e526a0-0ee9-4284-8d32-3eebe4ad9e84","name":"test","org_id":"9","description":"","arch":"","version":"","date":"2024-05-02T10:04:05-04:00","repositor …
```
=> Fixes 4208: add environment ID to template events/api

api/docs.go, api/openapi.json, go.mod, go.sum, pkg/api/rpms.go, pkg/dao/interfaces.go, pkg/dao/rpms.go, pkg/dao/rpms_mock.go, pkg/dao/rpms_test.go, pkg/handler/rpms.go, pkg/handler/rpms_test.go
- Adds API for listing content template errata: `/templates/:uuid/errata` (similar to the list errata endpoint for snapshots)
- Includes optional query parameters `search`, `limit`, `type`, and `severity`
- Depends on this [tang PR](https://github.com/content-services/tang/pull/10) to add in the CVEs
- Add a custom repository with errata and a RH repository and let them snapshot (this will snapshot a small RH repo: `OPTIONS_REPOSITORY_IMPORT_FILTER=small go run cmd/external-repos/main.go import && go run cmd/external-repos/main.go nightly-jobs`)
- Create a template with those repositories, selecting the latest date 
- Make a request to the `/templates/:uuid/errata` endpoint with the template uuid and you should see the template's errata (should include errata from both of the snapshots in …
=> Fixes 3656: add api to list template errata

docs/register_client.md
Updates the system association command in the rhsm registration docs
=> Build: Fix command in docs

api/docs.go, api/openapi.json, cmd/lint_openapi/main.go, mk/swag.mk, pkg/handler/environments.go, pkg/handler/package_groups.go, pkg/handler/rpms.go, pkg/handler/snapshots.go
Adds a linter to check for multiple tags in the openapi spec when running `make openapi`. Each tag is associated with the resulting data. For example, for listing repository package groups, the tag would be `packagegroups`.
- If there are any cases of multiple tags in the openapi spec, `make openapi` should fail and tell you which endpoint has more than one tag
- `make openapi` should not fail if each endpoint has only one tag
- For QE, some endpoints will be moved around (for example, if an endpoint was originally found under the `repositories_api` and it lists repository rpms, it would now only be found under the `rpms_api`)
=> Fixes 4195: check for multiple tags in openapi spec

deployments/deployment.yaml
expose this option to our deployments
=> Build: expose worker count to clowder

pkg/dao/repository_configs.go
Changes repo list search query to be case insensitive
- Add a repository
- Make a request to the list repos endpoint with a search term (i.e. `/repositories/?search=everything`)
- Should return repositories with that term regardless of case
- Can also check this in the UI with the Name/URL filter
=> Fixes 4222: make repo list search case insensitive

pkg/dao/repository_configs.go
We're seeing this error, but the actual error isn't logged. Need to see the error to debug further.
=> Refs 4271: improve err logging for fetchRepoConfigsForRepo

pkg/tasks/update_repository.go
Return from the update task if candlepin is not configured
In ephemeral try to update a repository and check the status of the task, it should be successful
=> Refs 4110: return from update task if no cp

build/Dockerfile
=> Build: update to ubi9

.github/workflows/content-sources-actions.yml, pkg/tasks/delete_repository_snapshots_test.go, pkg/tasks/delete_templates.go
Don't call out to candlepin when deleting a template if its not configured
Locally disable the candlepin server by commenting out the candlepin server url
create a template and then try to delete it
=> Refs 3600: wrap template delete calls

api/docs.go, api/openapi.json, pkg/api/templates.go, pkg/dao/templates.go, pkg/dao/templates_test.go, pkg/handler/templates_test.go, pkg/models/template.go
- Adds support for updating a template name 
- This doesn't have the candlepin integration in place yet (updating a template name will not update the environment name). Ticket for that [here](https://issues.redhat.com/browse/HMS-4290)
- Add a repository, let it snapshot, then create a template
- Edit the template name. This should work via both the API and UI
=> Fixes 4272: template name should be editable

api/docs.go, api/openapi.json, pkg/dao/rpms.go, pkg/handler/rpms.go
Adds sort_by parameter to `/templates/:uuid/errata`
- Add a repository with errata, let it snapshot, and create a template
- Make a request to list the template errata with a sort_by parameter. You can sort by issued_date, updated_date, type, or severity. Example request: `/templates/:uuid/errata?sort_by=type:asc`
- Response should list template errata sorted by the column and order specified (type and severity will be sorted alphabetically)
=> Fixes 4285: add sort_by to /templates/uuid/errata

cmd/external-repos/main.go, deployments/deployment.yaml, pkg/dao/repository_configs.go, pkg/dao/repository_configs_test.go, pkg/tasks/update_repository.go
start snapshotting every hour.  On each hourly run:
* Snapshot at least # of repos/24 on each run:
* snapshots all repos that have not been snapshotted in the last 24 hours
* if this amount is less than # of repos/24, then grab more repos to snapshot up to that number prioritizing those that have been snapshotted last.
* on a fresh db:  make repos-import
* `go run cmd/external-repos/main.go nightly-jobs`
* wait until all repos are done snapshotting
* create one or more custom repos
from a `make db-cli-connect` console run:
```
select count(queued_at), max(name), tasks.repository_uuid from tasks inner join repository_configurations rc on rc.repository_uuid = tasks.repository_uuid  where type = 'snapshot'  group by tasks.repository_uuid ;
```
this will show you the number of snapshot tasks …
=> Fixes 4256: snapshot every hour

pkg/dao/repository_configs.go, pkg/dao/repository_configs_test.go, pkg/external_repos/external_repos.json
and make repos removed from the external_repos.json file no longer public
1. on main run `make repos-import`
2. connect to the db and query 8-stream public repos:
```
```
3.  Check out this PR, re-run `make repos-import`
4. re-query the query and make sure the 8-stream repos are no longer public
5. query the 9-stream repos and make sure they are still public
```
```
=> Fixes 4281: remove 8-stream from public repos

pkg/api/api.go, pkg/dao/admin_tasks.go, pkg/dao/admin_tasks_test.go, pkg/handler/admin_tasks.go
Adds ability to filter admin tasks by type
1. Either test using frontend PR or make a request like `GET /admin/tasks/?type=introspect,snapshot`
2. Make sure you've created/deleted some repos and templates so you have a few task types to filter.
3. These are all the task types: https://github.com/content-services/content-sources-backend/blob/main/pkg/config/tasks.go#L4-L9
=> Refs 4133: add types filter to admin tasks list

pkg/dao/templates.go, pkg/dao/templates_test.go
Fixes a bug where filtering templates by multiple repo uuids lists duplicate templates
- Add 2 repositories, let them snapshot, and create a template with both of those repositories
- Make a request to list templates filtering by those 2 repo uuids (`templates/?repository_uuids=f572ddd9-2aaa-4503-bd87-9be723574f33,3a379621-e5af-40ad-a7a6-1b0c59934194`)
- You should see that template listed once and count should be 1:
```
{
"data": [
{
"uuid": "8f52f555-eef5-4b06-96ce-c0afdd260dd6",
"name": "template1",
"org_id": "17684632",
"description": "",
"arch": "x86_64",
"version": "8",
"date": "2024-06-17T00:00:00-04:00",
"repository_uuids": [
"f572ddd9-2aaa-4503-bd87-9be723574f33",
"3a379621-e5af-40ad-a7a6-1b0c59934194",
],
"rhsm_environment_id": "8f52f555eef54b0696cec0afdd260dd6",
"created_by": …
```
=> Fixes 4292: filtering templates by repo uuids lists dups

pkg/config/value_constraints.go, pkg/dao/repository_configs.go
By changing it to 24 hours, we are forcing snapshotting to happen only if they haven't been snapshotted in 24 hours, not 20.  Since the job is running hourly, it won't now grab ~3 hours worth of repos
None right now, I think we should merge and monitor the behavior
=> Refs 4256: change snapshot interval to 24 hours

api/docs.go, api/openapi.json, pkg/handler/repository_parameters.go
Adds the request body to the api spec for `/repository_parameters/external_gpg_key/`. This was missing and is needed for QE to test validation of gpg keys when fetching from a remote repo.
- Add a repository (QE example [here](https://issues.redhat.com/browse/HMS-3942) is using this one: https://jlsherrill.fedorapeople.org/fake-repos/signed/) 
- Fetch the gpg key from this URL: https://jlsherrill.fedorapeople.org/fake-repos/signed/GPG-KEY.gpg
```
POST /repository_parameters/external_gpg_key/
Request:
{
"url": "https://jlsherrill.fedorapeople.org/fake-repos/signed/GPG-KEY.gpg"
}
Response:
{
"gpg_key": "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nmQINBGPhWqgBEACnFSBzQlJ1ilLhS/toT46iJqInMQFtQz...-----END PGP PUBLIC KEY BLOCK-----\n"
}    
```
- Using the gpg key from the previous response, …
=> Fixes 3942: valid meta_key shows no gpg key found

deployments/dashboards/grafana-dashboard-content-sources.configmap.yaml
Adds a new panel to the dashboard showing tasks as they finish (with any result)
In the picture below the added graph is in the top left.  All task graphs are put on a new row:
=> Fixes 4320: add dashboard for all completing tasks

compose_files/pulp/docker-compose.yml
There seems to be a race condition where podman thinks postgres is 'up' but its not.  So restart the pulp migration if it errors.
```
make compose-clean compose-up
```
try to create a repo for snapshotting
=> Build: restart pulp migration on error

pkg/pulp_client/content_guard.go, pkg/pulp_client/domains.go
After reviewing the domain creation logic to handle race conditions on create, i determined the current method was best, but could use some simplification by use of errorWithResponseBody
while testing, however, i discovered that the content_Guard creation did not properly handle race conditions.
1.  turn on content guard creation by setting clients -> pulp -> 'custom_repo_content_guards' to true in config.yaml
2. run the server
3. run:
```
curl -H "`./scripts/header.sh $RANDOM $RANDOM`"  http://localhost:8000/api/content-sources/v1/repositories/bulk_create/  -H "content-type: application/json"  -X POST -d '[{"name":"abc1", "url":"https://jlsherrill.fedorapeople.org/fake-repos/needed-errata/", "snapshot": true},{"name":"abc2", "url":"https://jlsherrill.fedorapeople.org/fake-repos/signed/", …
```
=> Fixes 2246: fix conflict on guard creation

pkg/handler/admin_tasks.go, pkg/handler/api.go, pkg/handler/task_info.go, pkg/handler/templates.go
Changes all the parse filter error returns to log at the same level (INFO)
1. Make a request to `tasks/?exclude_red_hat_org=notabool`, where the params are the wrong type
2. In the server logs, there will be an error logged at the INFO level
=> Fixes 4334: lower parse filters log level

pkg/config/tasks.go, pkg/handler/task_info.go, pkg/tasks/client/client.go, pkg/tasks/client/client_test.go, pkg/tasks/queue/queue.go
- Adds a list of cancellable tasks to check against and rejects cancelling any tasks not included in the list. Currently includes only snapshot and introspect tasks
- Unrelated but attempting to cancel a RH task resulted in a panic due to dereferencing an error that doesn't exist so this includes that fix also
- Start a few different tasks in addition to introspect and snapshot and take note of the task uuid. List of all task types [here](https://github.com/content-services/content-sources-backend/blob/main/pkg/config/tasks.go)
- Make a request to cancel any task that isn't snapshot or introspect: `POST /tasks/:uuid/cancel/`. You should get a 400
- Cancelling snapshot or introspect tasks works as before
=> Fixes 3861: reject cancellation of certain task types

compose_files/pulp/docker-compose.yml, deployments/deployment.yaml
Set variables needed for candlepin communication.  Cert & key come from a secret.  This won't affect ephemeral at all
tests are green
=> Refs 4414: set candlepin deploy params

deployments/deployment.yaml
sets resource limits per deployment, as the api doesn't need as much as the workers.  Adapts to a new format to support the newest bonfire.
Tests pass
=> Build: set new resource limits per deployment

deployments/deployment.yaml, pkg/candlepin_client/client.go, pkg/config/config.go
support a custom ca cert in teh candlepin connection
I would just do a code review on this.  I was able to see this work using custom certs, but it was a very manual process of loading files from the filesystem into the config (since the config takes the file contents, not file names).   We should see it fix the current issue in stage quickly
=> Fixes 4420: add ca support to candlepin client

pkg/candlepin_client/client.go
Add some logging to help debug a ca issue
none
=> Refs 4420: debug candlepin ca

pkg/candlepin_client/client.go
=> Refs 4420: set RootCAs, not ClientCAs

api/docs.go, api/openapi.json, pkg/handler/repositories.go, pkg/handler/repositories_test.go
When using repository introspect and snapshot ends points, the response will now be the task info struct.
1. Use the repository introspect API to introspect a repository, it should return a 200 and a json with the task info.
2. Use the repository snapshot API to snapshot a repository, it should return a 200 and a json with the task info.
=> Fixes 4346: return task for introspect and snapshot APIs

pkg/candlepin_client/environment.go, pkg/tasks/update_template_content.go, test/integration/update_template_content_test.go
Within the stage the 404 error is not the same as in dev,  `couldn't fetch environment: 404 Not Found:`  instead of `couldn't fetch environment: 404:`   So instead we should just check the response code.  
Also we should be setting an environment type, which can be an arbitrary string, set here to 'content-template'.
Create a content template as normal, verify no errors
=> Fixes 4431: detect env fetch 404 and use env type

go.mod, go.sum
go-redis removed v9.5.4, so this is reverting to the most recent stable build which is v9.5.2
=> Build: revert to go-redis v9.5.2

api/docs.go, api/openapi.json, pkg/api/repositories.go, pkg/dao/repository_configs.go, pkg/dao/repository_configs_test.go, pkg/handler/repositories.go, pkg/models/repository.go, pkg/tasks/repository_snapshot.go, test/integration/snapshot_test.go
Run the snapshot task at creation of upload repositories.  
Modify the snapshot task to not create a remote and not perform a sync during the snapshot task.  Instead it will grab the latest version href from the repository in pulp (which should be empty version 0)
1. create an upload repo:
```
####
POST http://localhost:8000/api/content-sources/v1.0/repositories/
//x-Rh-Insights-Request-Id: 9d229d34-7219-405d-ba3d-8f99cf7c36ae
{
"name": "test",
"url": "",
"origin": "upload",
"snapshot": true
}
```
2.  Fetch the repository (GET /repositories/?origin=upload), you should see a snapshot …
=> Fixes 4294: snapshot on create for upload repo

pkg/candlepin_client/environment.go
Ignores 404s when trying to delete an environment in candlepin
- Start the app with candlepin disabled (set the candlepin.server to blank in config.yaml) and create a template
- Restart the app with candlepin enabled and delete the template. You shouldn't see any errors in the logs
- Without this PR you would see `couldn't delete environment: 404 Not Found`
- This [PR](https://github.com/content-services/content-sources-backend/pull/745) resolved the issue we were seeing on fetching environments when removing a repo from a template
=> Fixes 4423: handle 404 on delete template

.github/workflows/content-sources-actions.yml, pkg/config/tang.go, pkg/dao/rpms.go, pkg/tasks/update_template_content.go, test/integration/update_template_content_test.go
After template creation, supports fetching the latest snapshot for each of the repositories in the template, if the use_latest parameter is set.
1. Create a repository with multiple snapshots by changing the URL after creating the first snapshot
2. Add that repository to a template (should work on create and update for the template)
3. If you navigate to where the distribution servers the content, should be `pulp.content:8080/pulp/content/<domain>/templates/<template_uuid>` locally, you should see only the content for the most recent snapshot.
4. A call to `GET templates/:uuid/rpms` should return only the content of the most recent snapshot
=> Fixes 4312: support use_latest in update_template_content

cmd/content-sources/main.go, pkg/dao/repository_configs.go, pkg/tasks/introspect.go, pkg/tasks/queue/pgqueue.go
We are seeing what's likely expected error logs from tasks that are cancelled. We want to avoid logging these errors because they are expected when a task is cancelled and can be ignored.
1. `make repos-import`
2. `go run cmd/external-repos/main.go nightly-jobs`. Turn off snapshotting to save time.
3. Keep exiting the server with CTRL+C and restarting it
4. You shouldn't see error logs, expect maybe `error requeuing task with task_id: 00000000-0000-0000-0000-000000000000`. Ignore that one.
=> Fixes 4446: improve task context canceled logging

pkg/dao/rpms.go, pkg/dao/rpms_test.go
This adds CVEs to the response when listing snapshot errata.
- Add 2 repos with and without CVEs and let them snapshot (the small RH repo https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/ansible/2/os/ has CVEs)
- Make a request to list the snapshot errata (`GET /snapshots/:uuid/errata`). You should see the CVEs listed in the response for the one with CVEs and an empty array for the CVEs for the one without
- Without this PR you would see `"cves": null`
=> Fixes 4468: listing snapshot errata does not include CVEs

pkg/dao/task_info.go
Fixes 500 error on invalid repo uuids when listing tasks
- List tasks filtered by an invalid repository uuid (for devs: `/tasks/?repository_uuid=repository_uuid`, for QE: `app.content_sources.rest_client.tasks_api.list_tasks(repository_uuid="repository_uuid")`)
- Should return 200 and an empty list
=> Fixes 4416: listing tasks returns 500 for bad repo uuid

configs/config.yaml.example
There is a wrong indentation in the `configs/config.yaml.example` file which when copied to remove `.example` extension doesn't work and causes `make compose-up` fail. 
Fixed indentation and it works now after copying the file.
=> Fixes 4539: fix indentation in example yaml config

pkg/dao/environments.go, pkg/dao/package_groups.go, pkg/dao/rpms.go, pkg/dao/task_info.go
- Adds a clause to a few queries to check only repo configs that have not been soft-deleted
- Add a repository, let it snapshot, and grab the snapshot task uuid
- Restart the app with pulp disabled to force the delete-repository-snapshots task to fail
- Delete the repository
- Fetch the task associated with that repository, you should get a 404
- Listing tasks filtered on that repository uuid should return an empty list
- Searching environments, package groups, and rpms should work as before
- For QE, this should fix the issue that caused `test_repo_snapshot_functions` to fail, so we should make sure this test passes
=> Fixes 4422: edited repo returns incorrect snapshot task

pkg/pulp_client/task.go
added the domain to logging/errors of failed pulp tasks
create a repo with snapshotting pointing at a URL that is nonsense.  Monitor the logs:
```
error="domain ed88dfc6 had Pulp Task error 'traceback:   File...
```
=> Fixes 4561: log/return domain on pulp task failures

pkg/candlepin_client/candlepin_client_mock.go, pkg/candlepin_client/environment.go, pkg/candlepin_client/interface.go, pkg/tasks/update_template_content.go, test/integration/update_template_content_test.go
When template name is updated, the associated environment name in Candlepin isn't being updated. This PR fixes that.
Added a new `RenameEnvironment()` method to our Candlepin client. This method is called from the `update_template_content` task, which is started after updating the template, when the names are different.
_Change integration test passes._
_Manual test:_
```sh
http :8000/api/content-sources/v1.0/templates/ "$( ./scripts/header.sh acme 1111)" arch='x86_64' version='8' repository_uuids:='[]' description='testing rename' name='test' use_latest:=true
```
```sh
http :8000/api/content-sources/v1.0/templates/{_New template ID_} "$( ./scripts/header.sh acme 1111)"
http -a admin:admin :8181/candlepin/environments/{_New template ID without hyphens_}
```
```sh
http PATCH …
```
=> Fixes 4290: update candlepin env name after template rename

pkg/middleware/log_server_error_request.go, pkg/middleware/log_server_error_request_test.go, pkg/middleware/utils.go, pkg/router/route.go
Added a middleware which stores the body of incoming requests (cutoff to the limit of 1000B) and logs the request body when the response error code is of the 500 level (i.e. Server Error).
Wrote automated tests for checking the body storing it's recovery, cutoff limit and logging. Also tested this manually and checked for `request-id` retention and logging.
```
return ce.NewErrorResponse(http.StatusInternalServerError, "Test Error", "5xx testing error")
```
example request:
```
http http://localhost:8000/api/content-sources/v1.0/rpms/names "$( ./scripts/header.sh acme 1111)" limit:=100 uuids:='["cdb499cd-fc3b-44f9-9d4b-81824a418090"]' search='YfbrYLBvVcnY' x-Rh-Insights-Request-Id:9d229d34-7219-405d-ba3d-8f99cf7c36ae -v
```
=> Fixes 4432: log request body for server errors

pkg/api/templates.go, pkg/dao/templates.go, pkg/dao/templates_test.go, pkg/handler/templates.go, pkg/handler/templates_test.go, test/integration/update_latest_snapshot_test.go
There is a problem when sending a `PATCH` to update a template and supplying only the `use_latest=true` and not the date (supplying a null or an empty string), that errors out right now, but it should zero out the date instead.
This PR fixes that, by changing the way the date is decoded/unmarshaled from the JSON request body by wrapping it in a custom type (it's necessary to it this way, so that the parsing doesn't quit after first binding error, can't just silence the error returned by `Bind()` as that would ignore any following data).
Accepting `date=""` as zeroed date was also propagated to accompanying template `PUT` and `POST` endpoints.
```bash
http :8000/api/content-sources/v1.0/templates/ "$( ./scripts/header.sh acme 1111)" arch='x86_64' version='9' repository_uuids:='[]' …
```
=> Fixes 4541: fix template patch endpoint error on empty date

pkg/candlepin_client/candlepin_client_mock.go, pkg/dao/interfaces.go, pkg/dao/task_info.go, pkg/dao/task_info_mock.go, pkg/dao/task_info_test.go, pkg/handler/repositories.go, pkg/handler/repositories_test.go, pkg/handler/task_info.go, pkg/tasks/client/client.go, pkg/tasks/client/client_mock.go, pkg/tasks/client/client_test.go, pkg/tasks/queue/pgqueue.go, pkg/tasks/queue/pgqueue_test.go, pkg/tasks/queue/queue.go, pkg/tasks/queue/queue_mock.go, pkg/tasks/worker/worker.go, test/integration/snapshot_test.go
Adds support for cancelling pending tasks. Anywhere in our code that was cancelling a running task will now cancel a running or pending task.
1. Add all the EPEL repos, so their snapshot tasks will use all 3 workers. These snapshot tasks will be running.
2. Create another repo with snapshot. This snapshot task will be pending.
3. Delete all the repos you just created.
4. Both the running and pending snapshot tasks should be canceled.
=> Fixes 4478: support cancel pending tasks

pkg/api/templates.go, pkg/dao/interfaces.go, pkg/dao/templates.go, pkg/dao/templates_mock.go, pkg/dao/templates_test.go, pkg/handler/templates.go, pkg/handler/templates_test.go, pkg/tasks/update_template_content.go, test/integration/update_template_content_test.go
On the template update task, check to see if the template has been softdeleted, and simple return from the task if so
With your server running
Create a repo with snapshotting
Run the server with just the api:
`go run ./cmd/content-sources/main.go api`
Create a template with the repo:
```
####
POST http://localhost:8000/api/content-sources/v1.0/templates/
{
"name":"test5",
"arch": "x86_64",
"version": "9",
"repository_uuids": ["cd79da0f-dea2-46d4-82c4-56d3012db8bb"],
"date": "2024-08-09T14:04:05Z"
}
```
delete the repo:
```
####
DELETE …
```
=> Refs 4540: check for soft deleted template on update

pkg/api/templates.go, pkg/dao/templates.go, pkg/dao/templates_test.go
This PR makes the template part of the API respond with times in UTC time format, which fixes weird timezone/location converted output of the zero date (and others). This has to be done, even though all of our `time.Time` data is stored as UTC in our DB, but that is converted when reading it to the local time of the system it's running on (and also output in that).
Also has a [sibling front-end PR](https://github.com/content-services/content-sources-frontend/pull/325) addressing [this issue](https://issues.redhat.com/browse/HMS-4297) there.
We should think about doing this for all of our endpoints so that the responses are clearer and less "confusing"/more standardized.
Make a request to the endpoint which lists all templates and check date that the format of all dates is in UTC (doesn't …
=> Fixes 4297: template API responds in UTC time

pkg/tasks/queue/pgqueue.go
statement_timestamp() calculates the timestamp of when the statement starts.  I suspect that a new task is being added while this query is executing in rare cases (but don't actually have much evidence for this).  By using clock_timestamp(), we could (in theory) ensure that the started_at is always set after the queued_at is set.
We'll probably have to commit this and monitor errors for a couple weeks to see if its still occuring.
tests pass
=> Fixes 4523: use clock timestamp for started_at

api/docs.go, api/openapi.json, pkg/api/pulp.go, pkg/api/uploads.go, pkg/handler/pulp.go, pkg/handler/repositories.go, pkg/handler/utils.go, pkg/tasks/add_uploads.go, scripts/uploads.py, test/integration/pulp_upload_test.go
- Adds the public APIs for creating an upload and uploading a chunk: `POST /repositories/uploads/` and `POST /repositories/uploads/:upload_uuid/upload_chunk/`
- Modifies the existing addUploads API to use either an upload UUID or an upload href
- Modifies the python script for testing the upload process to use either the public or internal APIs
- Create an upload repository with snapshot set to true
- Use the ./scripts/uploads.py script to use the public APIs to create an upload, upload the chunks, and add the uploads:
`python3 uploads.py <repo_uuid> <rpm1 rpm2 ...> --api public` (the same script should still be able to be used with the internal APIs: `python3 uploads.py <repo_uuid> <rpm1 rpm2 ...> --api internal`)
- Fetch the repository and verify the package count (should be 1)
- Fetch …
=> Fixes 4548: add public upload create and upload chunk apis

go.mod, go.sum, pkg/candlepin_client/candlepin_client_mock.go, pkg/candlepin_client/content.go, pkg/candlepin_client/interface.go, pkg/tasks/update_template_content.go
The newer version of candlepin limits the number of content sets returned and errors if more than 3000 are returned. 
Candlepin does support  paging, but these options are not exposed in the api spec for reasons.
We really don't need to list them all, so this changes it to fetch the contet sets by label (which is a new feature)
Create a content template with some subset of rhel 9 repos and a custom repo.  Verify that a client sees just those pieces of content (or check the db and verify that the  cp_environment_content table in candlepin has what is expected
=> Fixes 4666: lookup content sets instead of listing

pkg/tasks/update_template_content.go
FetchContentsByLabel takes an orgID not a templateID.  This wasn't detected in dev because the ID passed in isn't used, instead a global org ID is used.  
There isn't a test for this and right now, its not easily testable.   Proper testing in stage would have caught it, and i've opened this issue to try to come up with a better test
=> Fixes 4692: pass org id to FetchContentsByLabel

pkg/handler/repositories.go, pkg/handler/repositories_test.go
Adds the AddUploads task as the last_snapshot on the repository
1.  create an upload repository
2. using its uuid, upload an rpm to it:
```
IDENTITY_HEADER="eyJpZGVudGl0eSI6eyJvcmdfaWQiOiI5IiwgInR5cGUiOiJVc2VyIiwidXNlciI6eyJ1c2VybmFtZSI6ImZvbyJ9LCJhY2NvdW50X251bWJlciI6ImZvbyIsImludGVybmFsIjp7Im9yZ19pZCI6IjkifX19Cg==" python ./scripts/uploads.py  30d60f06-b45d-44fa-aece-869d55edf002  ~/rpms/zebra-0.1-2.noarch.rpm 
```
3.  Fetch the repository and see a new last_snapshot_task
=> Fixes 4672: on AddUploads add task to last_snapshot

pkg/tasks/queue/pgqueue.go, pkg/tasks/worker/worker.go
It was still possible for a canceled task to get requeued on server exit. This fixes that.
It shouldn't be possible for the HeartbeatListener() method to requeue canceled tasks because heartbeats are removed as part of canceling the task. But if this fix doesn't work, that's the next place to look. 
1. Create and immediately delete a template. Need to replace repository uuid in create request below.
```
UUID=`curl -X POST --location "http://localhost:8000/api/content-sources/v1.0/templates/"     -H "x-rh-identity: eyJpZGVudGl0eSI6eyJvcmdfaWQiOiIxNzc5MTU2MCIsICJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiJzbmFwVXNlciJ9LCJhY2NvdW50X251bWJlciI6IjE3NzkxNTYwIiwiaW50ZXJuYWwiOnsib3JnX2lkIjoiMTc3OTE1NjAifX19Cg=="     -H "Content-Type: application/json"     -d "{
\"name\":\"test-$RANDOM\", …
```
=> Refs 4540: prevent requeue on exit for canceled task

pkg/dao/templates.go, pkg/tasks/update_template_content.go, pkg/tasks/worker/worker.go
* improper context passing
* lack of wrapping DaoError errors
* Check for closed transaction error
1. Create and immediately delete a template. Need to replace repository uuid in create request below.
```
UUID=`curl -X POST --location "http://localhost:8000/api/content-sources/v1.0/templates/"     -H "x-rh-identity: eyJpZGVudGl0eSI6eyJvcmdfaWQiOiIxNzc5MTU2MCIsICJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiJzbmFwVXNlciJ9LCJhY2NvdW50X251bWJlciI6IjE3NzkxNTYwIiwiaW50ZXJuYWwiOnsib3JnX2lkIjoiMTc3OTE1NjAifX19Cg=="     -H "Content-Type: application/json"     -d "{
\"name\":\"test-$RANDOM\",
\"arch\": \"x86_64\",
\"version\": \"9\",
\"repository_uuids\": [\"2f859dec-184b-48d4-9451-140a2336ce4d\"],
\"date\": \"2024-08-09T14:04:05Z\"
}"  | jq .uuid`
curl -X DELETE --location …
```
=> Refs 4540: fix task cancel issues

pkg/candlepin_client/content.go, pkg/tasks/candlepin_helpers.go, pkg/tasks/candlepin_helpers_test.go, test/integration/update_template_content_test.go
By default clients registered to stage/prod have  sslsslverifystatus set to 1, which works fine for cdn.redhat.com, but not for s3.   This overrides that setting for each content set.
Register a system and associate it to a template: https://github.com/content-services/content-sources-backend/blob/main/docs/register_client.md
on the client run 'subscription-manager refresh'
```
sslverifystatus = 0
```
=> Fixes 4712: add content override for sslverifystatus

pkg/dao/repositories_test.go, pkg/dao/repository_configs_test.go
adds origin filter to all the RepoConfig listing dao tests and fixes bug that prevented "SeedPreexistingRedHatRepos()" method from running for the RepoConfig dao suite
1. Import red hat repos locally
2. Run unit tests
3. Without the PR, the tests will fail
=> Fixes 4707: add origin to RepoConfig dao tests

api/docs.go, api/openapi.json, pkg/api/task_info.go, pkg/dao/repository_configs.go, pkg/dao/task_info.go, pkg/dao/task_info_test.go, pkg/handler/task_info.go, pkg/handler/task_info_test.go, pkg/models/task_info.go
For tasks relating to templates it doesn't make sense to use the `repository_name` and `repository_uuid` fields, so this PR changes those to `object_name` and `object_uuid` and a new field `object_type` which distinguishes to which type of object (`"repository" || "template"`) they are associated to.
1. Create a repository and a template.
2. List tasks with `GET /api/content-sources/v1.0/tasks/`.
3. Verify the `object_*` fields are present and correct.
=> Fixes 4644: task info response shows template name and uuid

pkg/candlepin_client/candlepin_client_mock.go, pkg/candlepin_client/consumer.go, pkg/candlepin_client/environment.go, pkg/candlepin_client/interface.go, test/integration/update_template_content_test.go
When deleting a template, consumers associated to that template will not be deleted.
1. Create a template
2. Create a consumer
```
curl -X POST --location "http://localhost:8181/candlepin/consumers/?owner=content-sources-test" \
-H "Authorization: Basic YWRtaW46YWRtaW4=" \
-d '{
"name": "example-consumer",
"type": {
"label": "system"
}
}'
```
3. Associate the consumer to the template
```
go run cmd/candlepin/main.go add-system <consumer uuid> <template name>
```
4. Delete the template
5. Check that the consumer still exists
```
curl -X GET --location "http://localhost:8181/candlepin/consumers?owner=content-sources-test" \
-H "Authorization: Basic YWRtaW46YWRtaW4="
```
You could also test this by
1. Create a …
=> Fixes 4185: retain systems when deleting template

pkg/handler/api.go
Changes our ping call to pulp to use domain list as we won't have permission for remotes list
The health check (using metrics) already uses this!
monitor the pulp api:
```
podman logs -f cs_pulp_api_1 
```
launch the server
```
go run cmd/content-sources/main.go api instrumentation consumer
```
call the ping api:
```
curl localhost:9000/ping  
````
you should only see calls to /api/pulp/default/api/v3/domains/?name=default
You'll only see ping hit this endpoint once per server start.  You should see it get hit by the metrics go routine every ~30 minutes.
=> Fixes 4745: use domain list to detect pulp is up

pkg/dao/task_info.go, pkg/dao/task_info_test.go
object name and UUID was not being returned for the fetch endpoint
1. Fetch a task that has the red hat org is the orgID
2. The object UUID and name should appear. Previously, those would be blank.
=> Fixes 4643: return object name for red hat task fetch

pkg/candlepin_client/product.go
We don't need the custom param defined to correctly query products here. I think I misunderstood how the parameter worked when I first implemented this. 
Without this change, only custom products are included in the response, but we want to return custom and red hat products (which is the default behavior).
I tested the API call in stage so it should work there
To test locally:
1. Turn off devel_org in the config file
2. `GET /api/content-sources/v1/subscription_check/` should return false
3. Turn on devel_org
4.  `GET /api/content-sources/v1/subscription_check/` should return true
=> Fixes 4777: remove custom param in list candlepin products

pkg/dao/snapshots.go, pkg/dao/snapshots_test.go
fills in the URL field on the snapshot response on the for_date snapshot api
1.  create a repo, let it snapshot
2. call the for_date api:
```
####
POST http://localhost:8000/api/content-sources/v1.0/snapshots/for_date/
{
"repository_uuids": ["cace7ad3-e385-41a8-afc2-aae94bde6cf6"],
"date": "2024-10-08T14:19:58Z"
}
```
verify the response has a url filled in:
```
{
"data": [
{
"repository_uuid": "cace7ad3-e385-41a8-afc2-aae94bde6cf6",
"is_after": true,
"match": {
"uuid": "ac856ef6-bd0f-473f-9574-26328a26a215",
"created_at": "2024-10-09T14:17:31.029366Z",
"repository_path": …
```
=> Fixes 4821: expose URL on snapshot/for_date

pkg/api/snapshots.go, pkg/dao/rpms.go, pkg/dao/snapshots.go, pkg/dao/snapshots_test.go, pkg/handler/snapshots_test.go, pkg/tasks/update_template_content.go
- Changes /snapshots/for_date/ request to remove support for YYYY-MM-DD date formats
- We currently support both RFC3339 and YYYY-MM-DD formats to maintain backward compatibility with IB. We can remove support for YYYY-MM-DD now as they've made the necessary changes [here](https://github.com/osbuild/image-builder/pull/1252)
- [ Frontend PR](https://github.com/content-services/content-sources-frontend/pull/352) should be merged first
1. Try to make a request to /snapshots/for_date/ with a YYYY-MM-DD date, this should fail:
```
{
"date": "2024-10-02",
"repository_uuids": ["30050c99-e904-4bf3-a31d-c213e203e19d"]
}
```
2. A request like this should still work:
```
{
"date": "2024-10-02T00:00:00Z",
"repository_uuids": ["30050c99-e904-4bf3-a31d-c213e203e19d"]
}
```
=> Fixes 4151: remove support for YYYY-MM-DD date formats

pkg/external_repos/external_repos.json
As part of an effort of letting image builder build beta releases, we'll need the beta repositories introspected.
=> Fixes 4854: introspect rhel beta repositories

pkg/dao/repository_configs.go, pkg/dao/repository_configs_test.go
Fixes a bug where the repo UUID and name were missing from `last_snapshot` in the repository response
1. Create a repository and let it snapshot
2. Fetch that repository. The `repository_uuid` and `repository_name` should not be empty in `last_snapshot`
```
...
"last_snapshot": {
"uuid": "911a76a9-2942-42b4-85aa-406222e543d2",
"created_at": "2024-10-16T18:22:58.496151Z",
"repository_path": "34aadb80/30d9d7b9-d49a-45b5-8a75-a527c35bd821/9eb85075-6c1e-426e-aff2-8454eb5f8c80",
"content_counts": {
"rpm.advisory": 2,
"rpm.package": 8,
"rpm.packagecategory": 1,
"rpm.packagegroup": 2
},
"added_counts": {
"rpm.advisory": 2,
"rpm.package": 8,
"rpm.packagecategory": 1,
"rpm.packagegroup": 2
},
"removed_counts": {},
"url": "http://pulp.content:8080/pulp/content/34aadb80/30d9d7b9-d49a-45b5-8a75-a527c3 …
```
=> Fixes 4797: no repo name or uuid in last_snapshot

pkg/dao/snapshots.go, pkg/dao/snapshots_test.go
Previously the change to this query improperly used the timestamp postgresql type which ignores timezones, by using timestamptz, the query now works properly.  We'll also just convert the date to UTC to be more consistent with using UTC dates.
Fly to somewhere that doesn't use UTC.
Run the TestUseLatest integration test in test/integration/update_template_content_test.go
=> Fixes 4860: use timestamptz for date comparisons

.github/workflows/content-sources-actions.yml, .golangci.yaml, .pre-commit-config.yaml, cmd/swagger2openapi/main.go, pkg/candlepin_client/client.go, pkg/dao/main_test.go, pkg/db/db.go, pkg/external_repos/introspect.go, pkg/external_repos/store.go, pkg/handler/main_test.go, pkg/models/main_test.go, pkg/pulp_client/client.go, pkg/pulp_client/package.go, pkg/tasks/add_uploads.go, pkg/tasks/queue/main_test.go, pkg/tasks/queue/pgqueue.go, test/integration/health_check_test.go, test/integration/import_export_repository_test.go, test/integration/pulp_upload_test.go
This PR addresses all problems currently reported by the `gosec` security checker and adds `gosec` to the list of checkers used in `golangci-lint`. Also fixes a problem with miss-matched Go versions for our pre-commit hooks.
=> Fixes 4853: fix gosec errors and enable gosec in CI

pkg/api/snapshots.go, pkg/dao/rpms.go, pkg/dao/snapshots_test.go, pkg/dao/templates.go, pkg/handler/snapshots_test.go, pkg/tasks/update_template_content.go
This reverts commit 533684ffc8622ffb551bbde1952aa344197e72af.
More changes are needed in IB so this doesn't break things, so reverting this until those are in place. 
Requests with date formats of YYYY-MM-DD or RFC3339 should be accepted to `/snapshots/for_date/`:
```
{
"date": "2024-10-23T00:00:00Z",
"repository_uuids": ["94c19c10-c5e1-4a65-8909-75e90baa4080"]
}
{
"date": "2024-10-23",
"repository_uuids": ["94c19c10-c5e1-4a65-8909-75e90baa4080"]
}
```
=> Refs 4863: Revert "remove support for YYYY-MM-DD formats"

api/docs.go, api/openapi.json, pkg/api/repositories.go, pkg/dao/interfaces.go, pkg/dao/repository_configs.go, pkg/dao/snapshots.go, pkg/dao/snapshots_mock.go, pkg/dao/snapshots_test.go, pkg/handler/snapshots.go, pkg/handler/snapshots_test.go, pkg/tasks/delete_repository_snapshots.go, pkg/tasks/delete_repository_snapshots_test.go, pkg/tasks/helpers/pulp_distribution_helper.go, pkg/tasks/helpers/pulp_distribution_helper_test.go, pkg/tasks/repository_snapshot_test.go, pkg/tasks/snapshot_helper.go, pkg/tasks/update_latest_snapshot.go, pkg/tasks/update_template_content.go
- When a new snapshot is taken either via a sync, or via an upload, a new distribution there is a new distribution in pulp pointing to /latest.
- The full URL to the above 'latest' snapshot distribution is returned with each snapshotted & upload repository, as the attribute:  "latest_snapshot_url"
- New route to download the repo-config with associated 'latest' url @/repositories/UUID/config.repo  
- Create a custom repository > wait for snapshot > check the response for the "latest_snapshot_url"
- Call the /repositories/UUID/config.repo endpoint with the above repository uuid, see the latest_snapshot_url represented there as "url"
- Check that you can download the above distribution.
=> Fixes 4716: Add "latest" snapshot distribution

pkg/dao/repository_configs.go
Adjusts comparison to check formatted url to keep from triggering snapshots if only a slash was added or removed.
1. Create a repository and let it snapshot
2. Update the repository URL by adding an extra slash or removing a slash. Snapshots should not be triggered with either PUT or PATCH
=> Fixes 4610: don't trigger snapshot on adding slash to url

cmd/external-repos/main.go, deployments/deployment.yaml, pkg/dao/domain_dao_mock.go, pkg/dao/domains.go, pkg/dao/domains_test.go, pkg/dao/interfaces.go, pkg/utils/utils.go
Adds a new command and weekly cron job to run orphan cleanup for pulp. Runs in batches of 5 orgs.
1. You can use this script to create a bunch of orgs
```
TOTAL_ORGS=33
for ((i=0; i<$TOTAL_ORGS; ++i))
do
ORG_ID=`tr -dc A-Za-z0-9 </dev/urandom | head -c 13`
HEADER=`./scripts/header.sh $ORG_ID`
UUID=$(curl -X POST --location "http://localhost:8000/api/content-sources/v1.0/repositories/" \
-H "${HEADER}" \
-d '{
"name": "comps repo 2",
"url": "https://rverdile.fedorapeople.org/dummy-repos/comps/repo2/",
"snapshot": true
}' | jq -r .uuid)
curl -X DELETE --location "http://localhost:8000/api/content-sources/v1.0/repositories/$UUID" \
-H "${HEADER}" \
-H "Content-Type: application/json"
done
```
2. Run `go cmd/external-repos/main.go pulp-orphan-cleanup`
3. …
=> Fixes 4775: add weekly cron for pulp orphan cleanup

pkg/external_repos/external_repos.json
As part of an effort of letting image builder build beta releases, we'll need the beta repositories introspected.
Just rhel 10 beta content
=> Fixes 4991: introspect rhel 10 beta repositories

mk/compose.mk, pkg/external_repos/redhat_repos.json
- Adjusts the make command for container volume removal to add support for docker
- Adds a selector to RHEL9 arm repos so it's easier to import those repos
1. Using docker, `make compose-clean` should clear out all unused volumes
2. Using podman, `make compose-clean` should still work as before
3. Running `OPTIONS_REPOSITORY_IMPORT_FILTER=arm go run cmd/external-repos/main.go import && go run cmd/external-repos/main.go nightly-jobs` should import and snapshot RHEL9 arm repos
=> Fixes 4964: add support for docker and importing arm repos

api/docs.go, api/openapi.json, pkg/api/content_units.go, pkg/dao/environments.go, pkg/dao/environments_test.go, pkg/dao/package_groups.go, pkg/dao/package_groups_test.go, pkg/dao/rpms.go, pkg/dao/rpms_test.go, pkg/handler/rpms.go
Adds new parameter to the request body of name search for rpms, package groups, and environments, "exact_names", to search for content units that exactly match the given names.
Also, the RPM presence API will now show as deprecated in the API spec
Example request
```
POST http://localhost:8000/api/content-sources/v1.0/rpms/names
x-Rh-Identity: {{identity-17791560}}
{
"urls": ["https://rverdile.fedorapeople.org/dummy-repos/comps/repo1/", "https://rverdile.fedorapeople.org/dummy-repos/comps/repo2/"],
"search": "",
"exact_names": ["penguin", "bear"]
}
```
1. With ["penguin", "bear"] as the value for "exact_names", both will be returned by the response
2. With ["penguin", "be"] as the value for "exact_names", only penguin will show, because "be" is not an exact …
=> Fixes 4958: add rpm exact name search

api/docs.go, api/openapi.json, pkg/api/api.go, pkg/api/content_units.go, pkg/api/pulp.go, pkg/api/repositories.go, pkg/api/repository_parameters.go, pkg/api/rpms.go, pkg/api/snapshots.go, pkg/api/templates.go, pkg/api/uploads.go
- Add required fields for API spec requests.
=> Fixes 3877: Add required fields for API spec requests

deployments/deployment.yaml
Orphan cleanup didn't run because the args were wrong. This fixes that. Changes the day to Thursday so I can check it again tomorrow.
You could test this in ephemeral by changing the cron timer to every couple of minutes and checking the logs, but I already did :)
=> Refs 4775: fix pulp-orphan-cleanup deployment

pkg/handler/repositories.go, pkg/handler/repositories_test.go
Triggers the update-latest-snapshot task after uploading content to a repo. Without this, use_latest templates with upload repos wouldn't get updated with the latest content.
(It's probably easiest to do most of this in the UI)
1. Add a RH repo and an upload repo with 1 rpm, let them snapshot
2. Create a template using those repos and set it to use latest content
3. Upload another rpm to the upload repo
4. Check the template's packages via the UI or the API (`/templates/:uuid/rpms?search=<uploaded_rpm_name>`). They should include all the uploaded packages
=> Fixes 5034: update latest snapshot after uploading content

pkg/dao/admin_tasks.go, pkg/dao/admin_tasks_test.go, pkg/dao/environments.go, pkg/dao/package_groups.go, pkg/dao/repository_configs.go, pkg/dao/rpms.go, pkg/dao/snapshots.go, pkg/dao/snapshots_test.go, pkg/dao/task_info.go, pkg/dao/templates.go, pkg/dao/templates_test.go
=> Fixes 4925: fixup DBErrorToApi funcs

api/docs.go, api/openapi.json, pkg/api/templates.go, pkg/dao/interfaces.go, pkg/dao/templates.go, pkg/dao/templates_test.go, pkg/models/template_repository_configuration.go
Adds snapshot list to template list and fetch api calls.  
1.  Create a repository, let it snapshot
2. Create a template with that repository:
```
####
POST http://localhost:8000/api/content-sources/v1.0/templates/
{
"name":"test3",
"arch": "x86_64",
"version": "9",
"repository_uuids": ["48b89a40-7d3d-4bd8-8596-f20d77c42032"],
"date": "2024-09-10T15:09:43-04:00"
}
```
3.  Fetch/list the template and see the snapshot list:
```
{
"data": [
{
"uuid": "01bc2b42-b74c-47f4-a9bd-1da2e8b3e941",
"name": "test3",
"org_id": "9",
"description": "",
"arch": "x86_64",
"version": "9",
"date": …
```
=> Fixes 4952: add snaps list with temp list/fetch

cmd/content-sources/main.go, cmd/external-repos/main.go, pkg/handler/api.go, pkg/tasks/queue/pgqueue.go, pkg/tasks/queue/pgx_pool_wrapper.go, test/integration/suite_test.go
This PR fixes the problems introduced with the changes made to how we close the pg pool, which were required to prevent leaving hanging connections. The introduced problem was when workers tried requeuing tasks on the context stop, but the pool was already closed at that point, so the requeuing was moved to when the workers start.
1. Enqueue a bunch of tasks.
2. CTRL+C to close the server.
3. Start the server again.
4. Verify that there are no errors:
- error requeuing task with task_id: 959ae228-6974-499b-b049-8600832355a7
- error starting database transaction: closed pool
=> Fixes 4928: fix worker task requeuing on start/stop

README.md
Import of repos fails if there is no running DB, which is deployed with `make compose up`.
=> Build: First start compose before importing repos

compose_files/pulp/docker-compose.yml, deployments/docker-compose.yml
By allowing ports to be specified, we can reuse this for tang and other places
This also moves minio out of the pulp compose into the main compose
=> Build: make pulp docker-compose reusable

cmd/jobs/main.go, deployments/deployment.yaml, deployments/jobs.yaml, pkg/dao/domain_dao_mock.go, pkg/dao/domains.go, pkg/dao/domains_test.go, pkg/dao/interfaces.go, pkg/jobs/cleanup_missing_domains.go
Adds a job to clean up the domains in our DB that are not in pulp
You can use the pulp CLI to test this, setup docs [here](https://pulpproject.org/pulp-cli/)
1. Create 2 repos in different orgs and let them snapshot
2. List domains in pulp via the pulp CLI: `pulp domain list | jq '.[].name'`
3. Delete one of the repos
4. Delete the domain associated to the deleted repo's org ID in pulp via the pulp CLI: `pulp domain destroy --name <domain_name>`
5. List the domains in pulp again to confirm the domains that are left
6. Run this job to clean up the domains in our DB: `go run cmd/jobs/main.go cleanup-missing-domains`
7. List the domains in our DB. They should now match pulp's cs-prefixed domains
=> HMS-5063: create job to cleanup missing domains

cmd/external-repos/main.go, pkg/dao/repository_configs.go, pkg/dao/repository_configs_test.go
After some investigation it was discovered that currently all failed snapshots are being re-run every hour.  This results in no 'extra' repos being synced.   This change results in failed snapshots only being re-run every day.  
This also fixes a couple of things, such as sorting by finished_at (instead of queued_at), and re-snapshotting every 25 hours instead of 24 (need to subtract one from the query)
1.   Create 3 repos with snapshotting, two that are real and one that isn't:
https://fixtures.pulpproject.org/rpm-unsigned/
https://jlsherrill.fedorapeople.org/fake-repos/needed-errata/
https://redhat.com/notarepo
2.  on main, run `go run cmd/external-repos/main.go nightly-jobs 24`
for consistentcy do not re-run it until snapshots are done
everytime you run it, you'll see one snapshot get …
=> HMS-5202: don't always rerun failed snaps

api/docs.go, api/openapi.json, pkg/handler/snapshots.go
This PR adds missing API spec filters for listing snapshots of a repository, needed in IQE for testing automatic snapshot deletion.
Related ticket: [HMS-4749](https://issues.redhat.com/browse/HMS-4749)
=> Build: update api spec for list snapshots by repo

pkg/dao/snapshots.go, pkg/dao/snapshots_test.go
- Fixes "invalid input syntax" errors when requesting to fetch the latest snapshot and list snapshots by date
- Adds validation to the repository uuids in requests to list snapshots by date
1. Make a request to `/repositories/:uuid/config.repo` with the uuid set to something like "uuid". This should return a 404.
2. Make a request to `/snapshots/for_date/` with the repository_uuids set to something like ["uuid1", "uuid2"]. This should also return a 404.
=> HMS-4987: fix 500s on invalid input syntax

pkg/dao/interfaces.go, pkg/dao/templates.go, pkg/dao/templates_mock.go, pkg/dao/templates_test.go, pkg/handler/templates.go, pkg/handler/templates_test.go, pkg/tasks/delete_repository_snapshots.go, pkg/tasks/delete_repository_snapshots_test.go, pkg/tasks/delete_snapshots.go, pkg/tasks/delete_snapshots_test.go, pkg/tasks/delete_templates.go, pkg/tasks/update_latest_snapshot.go, pkg/tasks/update_repository.go
This PR fixes a bug that happens when a repository exists within a template, and both are deleted, but the repository config is deleted before the template is deleted, then the `delete-templates` task gives a "repository not found" error and if this happens the template-repository distribution doesn't get deleted and remains an orphan.
The ticket assumed that the `delete-repository-snapshots` task didn't try deleting the template-repository distribution, but it actually already was trying to do so, but that step just needed to be moved earlier in the task and also do that for soft deleted templates. The `delete-template` task just needed to be changed to ignore not found repository configs.
1. Create a custom repository and add it to a new template.
2. Note down the template-repository …
=> HMS-5062: fix del-templ task fail if repo is deleted first

pkg/config/tasks.go, pkg/dao/task_info.go, pkg/dao/task_info_test.go
Adds canceled tasks to the query that cleans up all the old the tasks. Cleans up canceled with a queued_at time older than 20 days, not finished_at because canceled tasks do not have a finished_at time
1. Create and then delete a repository so that the snapshot and/or update-latest-snapshot tasks get canceled
2. Manually edit the queued_at time so it is older than 20 days
3. Run nightly-jobs and the task should be cleaned up
=> HMS-5259: cleanup canceled tasks

pkg/dao/module_streams.go
we have to aggregate the the streams into modules, and are using a map. This doesn't preserve module ordering though, so this change ensures that the name order is consistent. 
run the  dao/TestSearchRepositoryModuleStreams test 10 times and see no failures
=> HMS-5348: ensure order on module stream search

pkg/handler/repositories.go
Fixes some issues when creating an upload:
- changes artifact href to be a string instead of null if empty (this is blocking IQE from calling this api)
- rejects request if chunk_size is 0 
1. Artifact href should be set to an empty string if it doesn't exist
2. Request should be rejected if chunk size is 0 or less
=> HMS-5380: create_upload fixes

.github/workflows/content-sources-actions.yml
* By moving the wait for pulp to after candlepin, we hopefully don't have to wait as long
* unsure if we realy need these 'sleep 30' statements, lets try to get rid of them
=> Build: speed up integration tests

api/docs.go, api/openapi.json, pkg/api/uploads.go, pkg/handler/repositories.go
- Omits null values for `created`, `last_updated`, `artifact_href`, and `completed_checksums` from the upload response (used when creating an upload or uploading a chunk). These values are not always needed and null values here prevent the generated IQE client from calling these APIs
- Adds the upload uuid to the response when an artifact href is found (i'm not sure this should be null or omitted)
1. Responses from creating an upload and uploading a chunk shouldn't have any null values
2. Uploading rpms in the UI should still work the same (existing uploads should be reused)
3. IQE: Go through the uploading flow using the IQE environment, let me know if there are any other API type errors etc and I'll make the changes here
=> HMS-5390: omit null values in upload response

pkg/api/admin_task.go, pkg/feature_service_client/features.go, pkg/handler/admin_tasks.go, pkg/handler/admin_tasks_test.go, pkg/handler/api.go
This adds an API to list the content if a feature from the feature service API
1. Add the correct certs path to the clients.feature_service option in the config.yaml
2. Use the `GET /api/content-sources/v1/admin/features/` endpoint list the features
3. Choose one and use the name with `GET /api/content-sources/v1/admin/features/:name/content/` to list the content
4. Check that the fields match what is described by the JIRA ticket
=> HMS-5293: add list feature content

pkg/config/tasks.go, pkg/dao/interfaces.go, pkg/dao/metrics.go, pkg/dao/metrics_mock.go, pkg/dao/metrics_test.go, pkg/instrumentation/custom/collector.go, pkg/instrumentation/metrics.go, pkg/seeds/seeds.go
This PR adds new Prometheus metrics that are gonna be used in our grafana dashboard.
```python
content_sources_templates_age_average 
content_sources_templates_count 
content_sources_templates_updated_in_last_24_hour_count 
content_sources_templates_use_date_count 
content_sources_templates_use_latest_count 
content_sources_task_pending_time_average_by_type{task_type="add-uploads-repository"}
content_sources_task_pending_time_average_by_type{task_type="delete-repository-snapshots"}
content_sources_task_pending_time_average_by_type{task_type="delete-snapshots"}
content_sources_task_pending_time_average_by_type{task_type="delete-templates"}
content_sources_task_pending_time_average_by_type{task_type="introspect"}
content_sources_task_pending_time_average_by_type{task_type="snapshot"} …
```
=> HMS-5379: add metrics for templates

deployments/dashboards/grafana-dashboard-content-sources.configmap.yaml
This PR adds the [recently added metrics](https://github.com/content-services/content-sources-backend/pull/958) to the Grafana dashboard and resizes some of the existing visualizations to fit better.
=> HMS-5379: add template metrics to grafana

deployments/deployment.yaml
This PR adds the missing option for snapshot cleanup to the job deployment yaml 🔧
=> HMS-4747: add missing option to job deployment

.github/workflows/playwright-actions.yml, _playwright-tests/.prettierignore, _playwright-tests/.prettierrc, _playwright-tests/eslint.config.mjs, _playwright-tests/package.json, _playwright-tests/playwright.config.ts, _playwright-tests/tests/API/CheckGetFeatures.spec.ts, _playwright-tests/tests/API/PopularRepos.spec.ts, _playwright-tests/tests/API/Templates.spec.ts, _playwright-tests/tests/API/base_client.ts, _playwright-tests/tests/auth.setup.ts, _playwright-tests/tests/helpers/loginHelpers.tsx, _playwright-tests/yarn.lock
This PR adds 2 GH actions to check formatting and linting of our PW tests. 🔍 To do this new scripts are added to our `packages.json` which can be used with `yarn` (few dev dependencies are needed to do this, and also couple of format and lint config files). 🤖⚙️
New `yarn` scripts:
- `yarn lint` - checks for linting warnings and errors
- `yarn lint:fix` - fixes all auto-fixable linting problems
- `yarn format` - auto formats our PW tests code
- `yarn format:check` - check for formatting violations
- `yarn verify` - runs checks for linting, formatting and all PW tests
1. Run tests on main and on this PR, should be the same outcome.
2. Test out the new scripts/commands and verify their functionality.
=> Test: add format and lint checks to PW tests

.github/workflows/playwright-actions.yml
- Adds the CDN cert for RH repos to the backend config
- The same action steps exist on the frontend repo via this [PR](https://github.com/content-services/content-sources-frontend/pull/440) and were validated with the frontend RH repo tests
- You shouldn't see this warning anymore in the action step to trigger a snapshot for RH repos: `{"level":"warn","time":"2025-02-14T17:18:43Z","message":"No Red Hat CDN cert pair configured."}`
=> Test: add cdn cert

pkg/pulp_client/status.go, pkg/tasks/repository_snapshot.go
There are two small bugs fixed here
- For canceled snapshots, the failed_snapshot_count was not being updated because the DB query was using context that was canceled. This changes it to use context.Background().
- GetContentPath() in the pulp client was logging an error when it failed due to canceled context, but an error is expected if context is canceled
1. In the UI, add and remove the popular repositories (EPEL)
2. After removing them, there will no longer be an error logged "Failed to update failed_snapshot_count: context canceled"
=> HMS-5526: ignore canceled ctx for failed_snapshot_count

.github/workflows/playwright-actions.yml
This enables us to use secrets and manually trigger the workflow. Update also group to using PR number as `ref` would be always sha of main.
Copied from frontend.
=> Test: Update playwright trigger

.github/workflows/playwright-actions.yml, _playwright-tests/tests/API/Repositories.spec.ts, test/integration/delete_test.go, test/integration/update_latest_snapshot_test.go, test/integration/update_template_content_test.go
Replaces uses of the https://rverdile.fedorapeople.org/dummy-repos/comps repositories with the new ones at https://content-services.github.io/fixtures/yum/comps-modules
=> HMS-5162: replace fedorapeople comps repos with github fixtures

pkg/jobs/transform_pulp_logs.go
This will help to notify us of log format changes.  Its possible this may produce false log messages and i may need to adjust a bit
none
=> HMS-5396: Log error if log event is malformed

cmd/external-repos/main.go, pkg/dao/interfaces.go, pkg/dao/snapshots.go, pkg/dao/snapshots_mock.go, pkg/dao/snapshots_test.go, pkg/handler/snapshots.go, pkg/handler/snapshots_test.go, pkg/pulp_client/interfaces.go, pkg/pulp_client/pulp_client_mock.go, pkg/pulp_client/rpm_distributions.go, pkg/pulp_client/rpm_repository_version.go, pkg/tasks/delete_repository_snapshots.go, pkg/tasks/delete_repository_snapshots_test.go, pkg/tasks/delete_snapshots.go, pkg/tasks/delete_snapshots_test.go, pkg/tasks/delete_templates.go, pkg/tasks/snapshot_helper.go, pkg/tasks/update_template_content.go
* Changes snapshot SoftDelete to not error if the given snapshot was already soft deleted
* Adds the ability to list snapshots that are also soft deleted and uses this in cleanup
* makes pulp repo version delete and distribution delete return a string pointer instead of a string to make it obvious that 404s will not return a task href
* modified it so that if an error occurred for one repository, it would log it and still try to do the rest.
create a repository and get its repo config uuid
use this to create old snapshots, run in the terminal:
```
rcuuid="abcde"
created="2024-10-02 00:55:30.953994+00"
snapUUID=`uuidgen`
query="insert into snapshots (uuid,created_at, repository_configuration_uuid, version_href, publication_href, distribution_href, distribution_path) VALUES …
```
=> HMS-5522: cleanup snapshots even if partially deleted

pkg/dao/task_info.go, pkg/dao/task_info_test.go
Fixes a regression where by templates last update tasks were being deleted
import and snapshot rhle9 repos
Create a rhel 9 template 
update the dates:
```
update tasks set queued_at =  now() - interval '30 day';
update tasks set started_at =  now() - interval '30 day';
update tasks set finished_at =  now() - interval '30 day';
```
run process-repos:
```
go run cmd/external-repos/main.go process-repos
```
On main, you'll see the task get deleted and the template will show up in the UI as 'invalid'.  "edit" the templates to get them back to a green status and then repeat on this PR.
=> HMS-5585: do not delete last template update tasks

_playwright-tests/tests/API/CheckGetFeatures.spec.ts, _playwright-tests/tests/API/PopularRepos.spec.ts, _playwright-tests/tests/API/Repositories.spec.ts, _playwright-tests/tests/API/Templates.spec.ts
This adds test describes/suite wrappers to all current PW test files and removes the weird 'Content >' prefix that they all had, we know those tests test our API, since they live in out repo.
- All tests should pass (nothing has changed there) but the PW reports and traces should be better/cleaner.
=> Test: add test describes to playwright tests

.github/workflows/playwright-actions.yml
Switches secrets to be referenced from Github instead of Codebuild
- PW tests pass (triggered manually on this branch and passed [here](https://github.com/content-services/content-sources-backend/actions/runs/13638994392))
- No secrets being pulled from Codebuild (these look like `$FOO` instead of `${{ secrets.FOO }}`)
=> Test: move all secrets to github from codebuild

go.mod, go.sum, pkg/dao/rpms.go, pkg/dao/rpms_test.go
Changes the rpm name search to only search using prefixes.  This has a couple advantages:
1.  it is much much faster
2. The exact match will appear in the list first
Snapshot search is also switched here: https://github.com/content-services/tang/pull/18
create a repo, then search for rpms:
```
POST http://localhost:8000/api/content-sources/v1.0/rpms/names
x-rh-identity: eyJpZGVudGl0eSI6eyJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiIxIn0sImFjY291bnRfbnVtYmVyIjoiZm9vIiwiaW50ZXJuYWwiOnsib3JnX2lkIjoiMSJ9fX0K
{"urls":["https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/",
"http://yum.theforeman.org/pulpcore/3.16/el8/x86_64/"],
"search":"p"}
```
from the results, try search for a prefix, or a middle substring.  Only prefix's should return a match
Do the …
=> HMS-5551: use prefix match for rpm search

mk/pulp.mk
specifies full path to compose files to work around podman-compose bug
make compose-clean compose-up
=> Build: use full path for compose files

pkg/config/certificates.go, pkg/config/config.go, pkg/config/config_test.go, pkg/errors/errors.go, pkg/instrumentation/custom/collector.go, pkg/instrumentation/metrics.go
- Adds gauge vector with "certificate_label" type to filter by 
- This replaces the existing red hat cdn metric, so eventually that can be removed. But not until the existing alert is removed.
1. Configure all of the certs: cdn, candlepin, and feature service
2. `make run`
3. verify that `http:/localhost:9000/metrics` shows the CertificationExpiryDays metric, with each cert's days separated by the label
=> HMS-5395: add metrics for cert expiration

deployments/dashboards/grafana-dashboard-content-sources.configmap.yaml
Replaces the gauge of the rh cdn expiry days with a group of guages that show expiry days for all the certs. Any new certs added to this metric will automatically show up within this group
Looks like this:
You can look at the board after this merges and I can open a new PR with changes if needed
=> HMS-5395: add all cert expirations to grafana

_playwright-tests/tests/API/PopularRepos.spec.ts, _playwright-tests/tests/API/Repositories.spec.ts, _playwright-tests/tests/API/helpers/apiHelpers.tsx
Adds playwright tests for searching repository rpms and adding a popular repo
=> HMS-5613,HMS-5614: search rpms and add popular repo tests

cmd/external-repos/main.go, pkg/clients/candlepin_client/interface.go, pkg/dao/interfaces.go, pkg/dao/repositories.go, pkg/dao/repositories_mock.go, pkg/dao/repositories_test.go, pkg/dao/repository_configs.go, pkg/dao/repository_configs_mock.go, pkg/dao/repository_configs_test.go, pkg/external_repos/external_repos.json, pkg/external_repos/redhat_repos.json, pkg/handler/repositories.go, pkg/handler/repositories_test.go, pkg/tasks/delete_repository_snapshots.go, pkg/tasks/update_template_content.go, test/integration/delete_test.go, test/integration/suite_test.go, test/integration/update_latest_snapshot_test.go
This adds support for removing Red Hat repos for syncing.  (Currently they stay for introspection).  
Some changes needed to support this
* within the delete-repository-snapshots task, move the candlepin processing prior to the pulp processing.  This is due to some models being deleted during the pulp processing (it also makes sense to do things in reverse upon deletion).
* Looking up the red hat content ids from their labels
* Looking up templates to remove the repo from across all orgs, not just templates with the same org as the repository
setup, i'd recommend on a clean db.  On Main, run:
```
make compose-clean compose-up
```
start the server:
```
make run
```
snapshot all the repos:
```
go run cmd/external-repos/main.go process-repos
```
Create a template with RHEL …
=> HMS-5303: remove ansible repositories for snapshotting

pkg/instrumentation/custom/collector.go, pkg/instrumentation/metrics.go
Removes the RHCertExpiryDays metric because it is replaced by the CertificateExpiryDays metric
Alert has already been removed from stage
1. `make run`
2. View metrics at `http://localhost:9000/metrics
3. This metric no longer shows up
=> HMS-5395: remove RHCertExpiryDays metric

pkg/tasks/delete_snapshots.go, pkg/tasks/helpers/pulp_distribution_helper.go, pkg/tasks/helpers/pulp_distribution_helper_test.go, pkg/tasks/snapshot_helper.go, pkg/tasks/update_latest_snapshot.go, pkg/tasks/update_template_content.go
Fixes bug where fetching a snapshot task resulted in a parsing error. The snapshot payload was incorrectly saving the distribution href instead of the distribution task href.
Also fixes issue where we were not polling the update distribution task from pulp
1. Create a snapshot
2. Fetch that snapshot task from the admin tasks API: `/admin/tasks/<task_uuid>`
3. Previously, there would be a 500 because of a missing "logging_cid"
=> HMS-5565: fix admin task fetch parsing error

.github/workflows/playwright-actions.yml
Changes the codebuild project reference to point to the new backend codebuild project in our AWS account
Playwright tests run
=> Test: change codebuild project references

pkg/clients/feature_service_client/features.go, pkg/dao/repository_configs.go
Task workers in stage are crashlooping due to calling the feature service status API with an invalid org ID (-1). This adds a check to bypass that API if using an org ID of -1 (which is only used to delete unneeded repos). 
1. Run `make repos-import` when the feature service is enabled. Command should succeed and repos should be imported as normal
2. Layered repos (OCP and HA) should be present when listing RH repos or viewing RH repos in the UI if using an account that has access to these repos
3. Previously `make repos-import` failed when the feature service is enabled
=> HMS-5925: bypass feature service api for red hat org

_playwright-tests/tests/API/Repositories.spec.ts
We are seeing 403s in the integration repo [test runs](https://github.com/content-services/content-sources-playwright/actions/runs/14269364245/job/39998792719#step:10:119) from these 2 tests when they call the cleanup helper, likely because we were passing a function instead of a string. This fixes the name creation to call the function before passing it to the helper.
=> Test: fix name creation in repo tests

renovate.json
We already use dependabot, so the konflux bot is just creating unnecessary noise
=> Build: turn off konflux dependency bumping

configs/config.yaml.example, pkg/config/config.go, pkg/tasks/queue/pgqueue.go
and add a warning if its too small
in config.yaml set: 
```
worker_count: 25
pool_limit: 30
```
then import and sync all repos:
```
go run cmd/external-repos/main.go process-repos
```
see that they all complete
=> HMS-6020: add pool limit for tasking

pkg/dao/rpms.go
Adds RH org to the query to fix searching for rpms by repo UUID
1. Import RH repos and introspect at least one: `make repos-import-rhel9 && go run cmd/external-repos/main.go introspect https://cdn.redhat.com/content/dist/rhel9/9/x86_64/appstream/os/`
2. Searching rpms for that repo by UUID should work 
```
POST /rpms/names
{
"search": "nodejs",
"uuids": ["1d4d6b01-d5fd-466a-a56f-1863e0ce4d24"]
}
```
```
[
{
"package_name": "nodejs",
"summary": "JavaScript runtime"
},
{
"package_name": "nodejs-devel",
"summary": "JavaScript runtime - development headers"
},
...
]
```
=> HMS-5801: fix /rpms/names for RH repo uuids

pkg/dao/rpms.go, pkg/dao/rpms_test.go
The previous PR for HMS-5998 had a bug where if a module stream existed in a different repository with a higher version, that entire module stream would be ignored. 
to reproduce the original issue, import and sync  all the appstream repos:
```
go run cmd/external-repos/main.go introspect  https://cdn.redhat.com/content/dist/rhel8/8/x86_64/appstream/os
go run cmd/external-repos/main.go introspect  https://cdn.redhat.com/content/dist/rhel9/9/x86_64/appstream/os
go run cmd/external-repos/main.go introspect https://cdn.redhat.com/content/dist/rhel9/9/aarch64/appstream/os
```
wait for them to finish.
Then trigger rpm search:
```
curl -X POST --location "http://localhost:8000/api/content-sources/v1.0/rpms/names" \
-H "x-rh-identity: …
```
=> HMS-5998: properly get newest version for modules

deployments/deployment.yaml
Previously i forgot to add the new tasking_pool_limit to the deployment.yaml to make available in the deployment
ci passes
=> Build: add tasking_pool_limit to deployment

_playwright-tests/test-utils/src/helpers/repositories.ts
I made a new batch of 100 repos without a number in the URL
The multirepos path with a rank number in URL causes problems when that number corresponds to a release version.
tests pass
=> Test: Change to centirepos

deployments/deployment.yaml
makes the roadmap server configurable in the deployment
=> Build: Add roadmap server config to deployment

configs/config.yaml.example, pkg/cache/cache.go, pkg/cache/cache_mock.go, pkg/cache/noop.go, pkg/cache/redis.go, pkg/clients/roadmap_client/client.go, pkg/clients/roadmap_client/roadmap.go, pkg/clients/roadmap_client/roadmap_client_mock.go, pkg/config/config.go, pkg/dao/rpms.go, pkg/dao/rpms_test.go
Adds package streams info to package_sources. Pulls package stream info from the roadmap API and adds it to package sources if the RPM name matches.
Also adds RHEL EoL as the end date for any package source that is not in the roadmap API. Uses the end date for the latest released version of the matching RHEL major version.
To test package streams:
1. Search for "nodejs" in a rhel9 repo
2. Under package sources, you should see both the node 16 module and the 16.14.0 package stream
To test the rhel lifecycle info:
1. When a RHEL package doesn't exist in the roadmap, the RHEL end date is used instead
2. Search with a codeready repo. For example, "help2man" in https://cdn.redhat.com/content/dist/rhel9/9/aarch64/codeready-builder/os/
=> HMS-5913: add package dates from RHEL lifecycle

cmd/external-repos/main.go, deployments/deployment.yaml, pkg/tasks/delete_snapshots.go
Separates the snapshot-cleanup job from process-repos so it can be run on its own schedule (this sets it to run daily). This may also help narrow down and reduce the errors being reported by glitchtip (https://issues.redhat.com/browse/HMS-5947)
1. Create a repo, let it snapshot, then edit the repo URL to get another snapshot
2. Adjust the date of one of the snapshots to be a year old: `UPDATE snapshots SET created_at = (NOW() - CAST('365 days' AS INTERVAL)) WHERE uuid = '<snapshot_uuid>';`
3. Run `go run cmd/external-repos/main.go process-repos`. You shouldn't see any delete-snapshots tasks enqueued
4. Run `go run cmd/external-repos/main.go snapshot-cleanup`. This should start the delete-snapshots task
=> Build: separate delete-snapshots from process-repos

pkg/dao/interfaces.go, pkg/dao/templates.go, pkg/dao/templates_mock.go, pkg/tasks/delete_snapshots.go, test/integration/delete_test.go
Template distributions were not being updated when cleaning up outdated snapshots for RH repos, resulting in failed deletion of repo versions. There might be other issues at play here, so I've left in the debug logs for now.
I haven't found a way to test this without multiple RH snapshots, this hasn't been reproducible for me locally with custom or EPEL repos. If you have multiple RH snapshots, you can follow these steps:
1. Create a template with just the base RH repos for any version or arch. Set to a date earlier than the oldest snapshot so it uses the oldest
2. Update one of the RH repo's oldest snapshot so that it is set to be cleaned up. You can use this query:  `UPDATE snapshots SET created_at = (NOW() - CAST('365 days' AS INTERVAL)) WHERE uuid = '<snapshot_uuid>';`
3. Confirm the …
=> HMS-5947: fix delete-snapshots glitchtip errors

.github/workflowScripts/getFrontendRepo.sh, .github/workflows/playwright-actions.yml
This updates the `getFrontendRepo` workflow helper script to clone the frontend repo with submodules. Needed for cloning test utils.
This also switches the proxy to use the CI specific routes config, which is needed for the proxy to work correctly inside DinD. And makes the Playwright action use the updated user secrets.
Playwright tests pass in CI.
=> Build: update getFrontendRepo to clone submodules

mk/mockery.mk
This pins the version of the downloaded mockery binary to `v2.*` as our config isn't v3 compatible. This should be reverted/removed when we or if we update the config.
Task for updating our config was created here [[HMS-8889](https://issues.redhat.com/browse/HMS-8889)].
- When you remove your currently downloaded version of the mockery tool (`release/mockery`), the `make mock` command should download the latest v2 version and the mocks should be generated successfully.
=> Build: pin the downloaded mockery version to v2

pkg/clients/feature_service_client/features.go, pkg/external_repos/snapshotted_repos_importer.go
The prod feature service doesn't include RHEL-OS-x86_64 as a feature, so we can't include that in the request.
1. Set the feature service server in the clients section of the config to the prod server and grab the certs from vault and set them here too: 
```
feature_service:
server: https://feature.api.redhat.com/features/v1
client_cert:
client_key:
ca_cert:
client_cert_path: /home/bhouse/certs/cp_prod_client.cert
client_key_path: /home/bhouse/certs/cp_prod_client.key
ca_cert_path:
```
2. Also set options.feature_filter in the config to `["RHEL-HA-x86_64", "OPENSHIFT-OCP-x86_64"]`
3. On a fresh backend, run make repos-import
4. You should see the layered repos (openshift and HA) in the response when listing repos either via API or UI (using your prod account)
=> Build: append RHEL feature manually when importing repos

compose_files/pulp/docker-compose.yml
The pulp database was not persisting between compose-down and compose-up
1. `make compose-clean compose-up`
2. Create a repository with snapshot
3. List the repositories in pulp. e.g. `get http://localhost:8080/api/pulp/cs-62edc243ec/api/v3/repositories/?offset=0&limit=25`
4. The repository will be listed
5. `make compose-down compose-up`
6. Again, list the repositories in pulp
7. The repository should still be listed. Without this PR, no repositories would be found
=> HMS-8916: Persist pulp database for compose-down

_playwright-tests/tests/API/Repositories.spec.ts
Add end-to-end test that verifies manual snapshot creation workflow including repository setup, manual snapshot triggering via API, and task completion validation with timestamp verification.
=> HMS-8899: Add test to verify manually trigger snapshot feature

configs/config.yaml.example, pkg/config/config.go, pkg/config/logging.go, pkg/db/db.go, pkg/db/db_logger.go
- Makes the DB log level optionally configurable because the number of logs is freezing up my laptop
- Gorm now ignores "context canceled" error logs 
1. Use this to test the context canceling. It lists repositories and the cancels it quickly: https://gist.github.com/rverdile/646a8576d3919f18ab1998f7cb2682cd
2. Without this PR, gorm will log the context is canceled
3. Change the db_level option under logging to change it from the global logging level
=> HMS-9081: make db log level configurable

pkg/clients/kessel_client/client.go
Getting a 401 but we're not logging any additional information
=> HMS-9371: add debug logs for kessel api calls

pkg/clients/kessel_client/client.go, pkg/rbac/kessel.go
Kessel requires that we get the Default workspace ID rather than the Root workspace ID
=> HMS-9371: use default workspace ID for kessel

README.md
Updates the IP address for the pulp.content host entry needed to run the go integration tests
=> Build: fix instructions for running go integration tests

mk/go-rules.mk
After updating some code and re-running 'make run', the makefile would recompile every binary, which wasn't really necessary.  This limits it to only rebuilding content-sources.
Modify some dao file or model
run 'make run'
look for:
```
go build  -o "/home/jlsherri/git/content-sources-backend/release/content-sources" "cmd/content-sources/main.go"
```
previously you'd see about ~5 of these.
=> Build: Only recompile the main binary on make run

pkg/config/value_constraints.go, pkg/dao/repository_configs.go, pkg/dao/repository_configs_test.go, pkg/dao/suite_test.go
Changes the functionality of the process-repos command:
* snapshot all Red Hat repos every hour
* snapshot failed Community Repos regardless of failed_snapshot_count
Also refactors the InternalOnly_ListReposToSnapshot method to modularize more of it and improve the readability
1. Use this CLI cursor made to add tasks to repositories: https://gist.github.com/rverdile/5c4d43d1fba474bfdd24fea030d0dd6a
2. Create some combinations of custom, community, and red hat repositories with new, old, or failed tasks
3. run `make process-repos` 
4. Snapshots should be enqueued as expected based on the tasks you've created
5. For Red Hat repos specifically, if just one of the snapshots is older than 45 minutes, all Red Hat repos should be enqueued.
=> HMS-6307: Snapshot Red Hat repos together during process-repos

README.md, mk/compose.mk, mk/repos.mk
This adds 2 new helper make commands.
- `make compose-run`, that starts the container dependencies without initializing any
- `make repos-mvp`, which will import 2 repos needed for a minimal local setup and force them to snapshot
Verify those commands do what they should.
=> Build: add development helper make commands

_playwright-tests/tests/API/Repositories.spec.ts, configs/config.yaml.example, deployments/deployment.yaml, pkg/config/config.go, pkg/config/value_constraints.go, pkg/dao/repository_configs.go, pkg/dao/repository_configs_test.go, pkg/dao/suite_test.go
- Prevents creating custom EPEL repos
- If the `allow_custom_epel_creation` feature flag is true for some orgs, custom EPEL repos can be created by those
1. Set `features.community_repos.enabled: true` and `features.allow_custom_epel_creation.enabled: false` in your config
2. Try to create an EPEL repo and a repo with `origin: community`. Both should fail with a 400
3. Do the same with the bulk create API. This should also fail with a 400
4. Add an org ID to the `features.allow_custom_epel_creation.organizations` field and flip `features.allow_custom_epel_creation.enabled`  to true
5. Request to create these repos with that org ID. The repos should be created (or fail with `Repository with this URL already belongs to organization` if you have one already)
=> HMS-5988: prevent creation of custom EPEL repo

pkg/rbac/client_wrapper.go, pkg/rbac/client_wrapper_test.go, pkg/rbac/kessel.go
Previously, if a user was an admin, RBAC was skipped.  
It was added as a work around for something that is no longer needed.  
The commit removes this behavior.
- Test locally, enable RBAC in config.yaml.
- If you want for a user to get authorized, add their username under mocks.rbac in config.yaml under appropriate role.
- Perform a request to an endpoint.
- A user should not get authorized, even if they are an admin, if their username is not listed in mocks.rbac.
Note that redis is set up to keep identity headers for a certain period of time.
You might want to set it up in config.yaml under redis.expiration.rbac to use a short time frame.
I used a 1s setting (default is 1min).
=> HMS-9391: remove skipping RBAC for users with admin privileges
