.github/workflows/content-sources-actions.yml
.gitignore
Makefile
build/Dockerfile
deployments/deployment.yaml
pkg/db/db.go

This:
* builds the migration files and the migration command into the container 
* configures the deployment to use an init container to migrate the database
* Adjusts the migration command to not error if no changes are detected

CONTENT-67: db migrate in containers

---

api/docs.go
api/openapi.json
go.mod
go.sum
pkg/api/repository.go
pkg/dao/error.go
pkg/dao/interfaces.go
pkg/dao/main_test.go
pkg/dao/repository.go
pkg/dao/repository_test.go
pkg/handler/api.go
pkg/handler/repositories.go
pkg/handler/repository_test.go
pkg/models/repository_configuration.go
pkg/models/repository_configuration_test.go
scripts/header.sh

CONTENT-51 - add put/patch for repositories

---

pkg/dao/error.go
pkg/dao/repository.go
pkg/dao/repository_test.go
pkg/models/base.go
pkg/models/repository_configuration.go

for name, url, AccountId, and OrgId

CONTENT-81 - do not allow blank values

---

db/migrations/20220512132042_create_repository_configurations_table.up.sql
pkg/api/api.go
pkg/dao/interfaces.go
pkg/dao/repository.go
pkg/dao/repository_test.go
pkg/handler/api.go
pkg/handler/repositories.go
pkg/handler/repository_test.go
pkg/models/repository_configuration.go
pkg/seeds/seeds.go

 CONTENT-78: Add Filters to list Api

---

pkg/api/api.go
pkg/dao/repository.go
pkg/dao/repository_test.go
pkg/seeds/seeds.go

CONTENT-107: Allow arch/version to accept comma separated values

---

docs/architecture.md
docs/db-model.puml
mk/plantuml.mk

This PR just add a draft for an entity-relationship to be reviewed.

Refs 47: db:add preliminar entity relationship diagram

---

api/docs.go
api/openapi.json
pkg/api/repository_parameters.go
pkg/config/value_constraints.go
pkg/dao/repository_test.go
pkg/dao/suite_test.go
pkg/handler/api.go
pkg/handler/repository_parameters.go
pkg/handler/repository_parameters_test.go
pkg/handler/repository_test.go
pkg/models/base.go
pkg/models/repository_configuration.go
pkg/models/repository_configuration_test.go
pkg/models/suite_test.go
pkg/seeds/seeds.go
pkg/seeds/suite_test.go

* App api /repository_parameters to return a list of versions and arches
* Validate repository_configurations are saved with a valid version and arch

Fixes 95: preset arches and versions

---

api/docs.go
api/openapi.json
pkg/api/repository_rpm.go
pkg/dao/interfaces.go
pkg/dao/rpm.go
pkg/dao/rpm_test.go
pkg/handler/api.go
pkg/handler/repository_rpm.go
pkg/models/repository.go
pkg/models/rpm.go
pkg/seeds/seeds.go

- Add `Public` column with `false` as default value.
- Add handler for the `/rpms/names` route.
- Implement the logic to list the suggested packages given a query and a list of urls.
- Add unit tests.

Fixes 103: add search for packages

---

pr_check.sh

testing GHPRB integration/triggers

Refs 105: Rename pr_checks

---

pkg/config/config.go
pkg/config/config_test.go
pkg/config/test_files/cert.crt
pkg/external_repos/introspect.go

Fixes 142: support cert via env variable

---

deployments/deployment.yaml

This introspects a single repositroy at startup such that
QE can better test integration points
This repo would get introspected once a day as it is

Refs 121: introspect one public repo on startup

---

mk/variables.mk

- Update mk/variables.mk logic for reading DATABASE_ vars from config.yaml.
- Clean-up informative message block from mk/variables.mk

Fixes 167: fix mk/variables.mk config loading

---

deployments/deployment.yaml

match app name, its off for stage deployments.

Refs 104: Update clowdapp database name

---

api/docs.go
api/openapi.json
pkg/handler/repositories.go

Check terminal after delete and there will be no error message anymore

Fixes 154: Send empty body on delete response

---

deployments/deployment.yaml

This is needed for stage/prod, example here:   https://github.com/RedHatInsights/entitlements-api-go/blob/master/deployment/deploy.yml#L152-L172

Refs 173: define internal service

---

api/docs.go
api/openapi.json
db/migrations/20220512132042_create_repository_configurations_table.up.sql
db/migrations/20220921110120_add_gpg_key_to_repository_configurations.down.sql
db/migrations/20220921110120_add_gpg_key_to_repository_configurations.up.sql
pkg/api/repository.go
pkg/dao/repository_config.go
pkg/dao/repository_config_test.go
pkg/dao/suite_test.go
pkg/handler/repositories_test.go
pkg/models/repository_configuration.go
pkg/models/repository_configuration_test.go

Adds `gpg_key` text and `metadata_verification` boolean fields to repository CRUD.

Fixes 75: Add gpg key and metadata verify to repo crud

---

pr_check.sh

only run tests marked for API in the pr_checks

Refs 183: Add iqe marker expression

---

pkg/external_repos/introspect.go
pkg/external_repos/introspect_test.go

- update Introspect to pass dao.Repository by reference, and update callers.
> Sorry, I didn't realize about this during the pr reviews
TODO:

Fixes 227: package_count=0 after introspect

---

build/Dockerfile

Fixes 209: update base container image

---

pkg/external_repos/external_repos.json
pkg/external_repos/image_builder.go
pkg/external_repos/image_builder_test.go

Refs 262: add rhel 8.7 repos

---

api/docs.go
api/openapi.go
api/openapi.json
cmd/swagger2openapi/main.go
pkg/api/popular_repositories.go
pkg/config/value_constraints.go
pkg/dao/repository_configs.go
pkg/event/adapter/introspect.go
pkg/event/adapter/kafka.go
pkg/event/message/headers.go
pkg/event/producer/introspect_request.go
pkg/event/producer/producer.go
pkg/event/schema/schemas.go
pkg/external_repos/introspect_test.go
pkg/handler/api.go
pkg/handler/api_test.go
pkg/handler/popular_repositories.go
pkg/handler/popular_repositories.json
pkg/handler/popular_repositories_test.go
pkg/handler/repositories_test.go
pkg/handler/repository_parameters_test.go

Adds the "/common_repositories/" endpoint with 4 repositories in the common_repositories.cfg for now.

Fixes 276: Add "Popular repositories" endpoint

---

db/migrations/20221130134116_move_revision_to_checksum.down.sql
db/migrations/20221130134116_move_revision_to_checksum.up.sql
pkg/dao/repositories.go
pkg/dao/repositories_test.go
pkg/external_repos/introspect.go
pkg/external_repos/introspect_test.go
pkg/models/repository.go

to determine if a repo was updated.

Fixes 280: switch to using repomd checksum

---

pkg/config/config.go
pkg/config/logging.go

also added some logging for better debugging

Refs 292: use hostname for default stream

---

deployments/testing.yaml

restrict testing to api marked cases
Apologies for churn, can't really recreate the cluster pipeline to validate this CJI change.

Refs 322: Try stage for testing CJI

---

deployments/testing.yaml

Updating iqe plugin config and sticking with original dynaconf env

Refs 322: back to stage_post_deploy

---

deployments/testing.yaml

Reverts content-services/content-sources-backend#176
Don't have access to utilize this debug mode.

Refs 322: Revert  "Set debug for testing CJI template"

---

configs/config.yaml.example
mk/db.mk
mk/variables.mk

this will allow us to use the existing docker compose for spinning up a pulp server

Refs 328: change dev pgsql container name & port

---

deployments/dashboards/grafana-dashboard-content-sources.configmap.yaml

This should fix the issue where the graphs aren't showing anything

Refs 268: make grafana datasources env variable

---

deployments/dashboards/grafana-dashboard-content-sources.configmap.yaml

improve the look of the latency graph,
add counts for repos and repo configs
look at graph and rejoice in it:

Refs 268: adjust dashboard

---

mk/docker.mk

Fixes 377: Remove unused makefile vars

---

.github/workflows/content-sources-actions.yml
.github/workflows/qe-approval-label.yml
.github/workflows/qe-approval.yml

Refs 1176: fixes for actions

---

.github/workflows/qe-approval.yml

Refs 1176: use org read secret to read teams

---

.github/workflows/qe-approval.yml

Refs 1176: use qe list of variables

---

.github/workflows/qe-approval.yml

Refs 1176: switch to vars

---

.github/workflows/qe-approval.yml

This will have to be merged to test

Refs 1176: use org read token

---

.github/workflows/qe-approval.yml

Refs 1176: use pull_request_target for action

---

.github/workflows/qe-approval-label.yml

Refs 1176: run label check after assigning

---

.github/workflows/qe-approval-label.yml
.github/workflows/qe-approval.yml

Refs 1176: use pull_request_target for action (#198)

---

deployments/testing-job.yaml

Add a selenium container to the spec for IQE Job

Refs 1104: Update iqe image tag, add selenium container

---

deployments/testing-job.yaml

qontract-reconcile checks gave me the very helpful error message of `metadata`, so I'm making some adjustments here.

Refs 1104: Update testing job metadata

---

deployments/testing-job.yaml

Refs 1104: Update testing job spec2

---

.rhcicd/build_deploy.sh
.rhcicd/pr_check.sh

Copying these files into a .rhcicd directory, will remove the previous ones once ci is updated.

Refs 1249: start move of rhcicd files

---

.rhcicd/build_deploy.sh
.rhcicd/pr_check.sh
.rhcicd/sonarqube.sh

Fixes 1249: Add sonarQube scanning

---

go.mod
go.sum

by pulling in a newer yummy
Force add a bad repository via the api
see the error message returned in the error tooltip
It should now include what file errored (404)

Fixes 1251: better error msgs

---

deployments/dashboards/grafana-dashboard-content-sources.configmap.yaml

This includes all metrics except for content_sources_kafka_message_result_total which does not seem to be working correctly

Refs 1203: Initial grafana update for new metrics

---

deployments/dashboards/grafana-dashboard-content-sources.configmap.yaml

Refs 1203: add last grafana dashboards

---

pkg/event/producer/producer.go

Refs 1507: do not set security proto if not set

---

deployments/testing-integration.yaml

This PR adds a template for stage post-deploy integration tests.
No testing steps required.

Add job template for post-deploy integration tests

---

deployments/testing-integration.yaml

This PR updates the integration testing job template to use the correct image tag.

Fix image tag used by integration testing job

---

deployments/testing-integration.yaml

Update the e2e test template to use the beta stage UI.

Update e2e test template to use beta stage UI

---

pkg/external_repos/external_repos.json

Fixes 1759: add 9.2 repos

---

go.mod
go.sum

updating yummy to add this feature: https://github.com/content-services/yummy/pull/14

Fixes 1693: update yummy to v1.0.5

---

go.mod
pkg/notifications/client.go

Fixes incorrect method type and error handling

Fixes 602: Fixes incorrect method type and error handling

---

pkg/notifications/client.go

Fixes 602: Fix defer close

---

pkg/notifications/client.go

Fixes 602: Update call method and kafka version

---

pkg/config/config.go
pkg/notifications/client.go

Fixes 602: Add client to config

---

pkg/notifications/client.go

Fixes 602: Test Warn log in staging

---

pkg/config/config.go

Fixes 602: Move NotificationsClient out of viper

---

pkg/config/config.go
pkg/notifications/client.go

Fixes 602: Add Logging

---

go.mod
go.sum
pkg/config/config.go

Fixes 602: Add SSL configuration

---

pkg/config/config.go

Fixes 602: Add SSL/SASL authentication

---

pkg/notifications/client.go

Fixes 602: Update error to better return result

---

pkg/config/config.go

Fixes 602: Identify KafkaServers

---

cmd/content-sources/main.go
configs/config.yaml.example
pkg/config/config.go
pkg/handler/api.go
pkg/tasks/client/client.go
pkg/tasks/introspect.go
pkg/tasks/queue/mock_queue.go
pkg/tasks/queue/pgqueue.go
pkg/tasks/queue/pgqueue_test.go
pkg/tasks/queue/queue.go
pkg/tasks/worker/worker.go
pkg/tasks/worker/worker_pool.go
pkg/tasks/worker/worker_pool_test.go

* moves some config values to the config parsing
* fixes heartbeat timer
* moves to a single heartbeat value
* passes queue to tasks, for future payload updating
* Adds a queue method for payload updating
Ensure introspection still works

Refs 1471: tasking fixes

---

pkg/config/config.go
pkg/event/topics.go

Fixes 602: Map topic requestedName to Name in clowder

---

pkg/config/config.go

Fixes 602: Fix logic typo

---

pkg/client/rbac_test.go

Fixes 1845: fix TearDownTest capitalization

---

deployments/deployment.yaml

This is to turn on the new tasking system in stage.
Still trying to figure out how to completely test this in ephemeral. Can see the env var set to "true", but that's it so far. Logging doesn't seem to work and I need to somehow create a user to trigger introspect.
Should be able to see this change in ephemeral.

Refs 1470: turn on new tasking system in stage

---

deployments/deployment.yaml

So we can see more information.
tests pass

Fixes 1989: set debug for ephemeral

---

pkg/notifications/client.go

Fixes a potential issue of sending un-needed noitifications

Fixes 2065: Fix potential empty notification

---

deployments/deployment.yaml

as it was changed as part of https://github.com/pulp/pulp-clowder-deployments/pull/67
Tests pass

Refs 1471: fix pulp deployment url

---

deployments/deployment.yaml

Refs 1947: update pulp pwd secret

---

cmd/content-sources/main.go

Refs 2315: Debug s3 issue in stage

---

deployments/deployment.yaml

do not go through the web container
Tests pass?
If you want to further test, test a snapshot in ephemeral and verify the task doesn't fail with this deployment.yaml

Fixes 2367: talk to pulp api directly

---

deployments/testing-integration.yaml

This way SAAS reconcile creates jobs that can be differentiated
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/77262

Refs 2344: Use the name stub in the template name

---

deployments/testing.yaml

Replaced with ENV_FOR_DYNACONF
New parameter was added here: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/77262

Refs 2344: Remove IQE_ENV

---

pkg/handler/repositories_test.go
pkg/pulp_client/domains.go
pkg/tasks/delete_repository_snapshots.go
pkg/tasks/delete_repository_snapshots_test.go

Ongoing PR to fix nil ref in prod

Fixes 2398: PulpPropFix

---

deployments/deployment.yaml

Refs 645: move securityContext

---

deployments/deployment.yaml

adds a parameter for the nightly cron job to allow for easy overriding

Fixes 2449: parameterize cron job

---

.github/dependabot.yml
go.mod
go.sum

Update deps, and setup automatic update PRs from dependabot

dependency update and add dependabot updates

---

pkg/config/config.go

debugs the s3 connection info in stage

Refs 2631: debug s3 connection

---

api/docs.go
api/openapi.json
pkg/handler/api.go
pkg/handler/features.go
pkg/handler/popular_repositories.go
pkg/handler/public_repositories.go
pkg/handler/repositories.go
pkg/handler/repository_parameters.go
pkg/handler/repository_rpms.go
pkg/handler/snapshots.go
pkg/handler/task_info.go

We are adding the missing descriptions for some endpoints. Along with this, we have also reworded them with the purpose of ongoing enhancements in API docs.

Refs 2669: add/modify descriptions for operations

---

.github/dependabot.yml

Build: fix depndabot grouping

---

pkg/tasks/queue/pgqueue.go

Adding debugs logs to see if register listener is hanging

Refs 1581: debug register listener

---

db/migrations/20231006121354_longer_task_errors.up.sql

When setting a limit on the error field, trim existing contents.
tests pass

Refs 2425: trim error on update

---

pkg/dao/repositories_test.go
pkg/models/base.go
pkg/models/repository.go

This trims the introspection error to 255 characters
I'm not sure how to reproduce the error, but i've added a unit test to cover it.

Fixes 2832: trim introspection error

---

compose_files/pulp/docker-compose.yml

Update the compose for a new pulp image

Build: update compose for newer pulp

---

deployments/testing-integration.yaml

Adding _JAVA_OPTIONS paramter for the selenium container.

Refs 2361: Update integration-testing template parameters

---

go.mod
go.sum
pkg/config/config.go
pkg/config/event.go
pkg/event/scram_client.go

based on  https://github.com/RedHatInsights/insights-results-aggregator/pull/1864/files
We may need to just merge to stage to verify this works.

Fixes 2738: support SCRAM-SHA-512 sasl mech for kafka

---

pkg/tasks/queue/pgqueue_test.go

This uses a parent context to send the cancel notification for this test.  I suspect the ordering of things executing was causing the cancel trigger to have its context triggered prior to it finishing
Tests pass

Fixes 2918: use parent context for cancel test

---

.github/workflows/content-sources-actions.yml
deployments/deployment.yaml
deployments/docker-compose.yml

Upgrade to Postgres 15
tests pass?

Refs 2711: upgrade to postgres 15

---

deployments/testing-integration.yaml

HMS-3020
Relates to https://github.com/RHEnVision/provisioning-backend/pull/751 , https://github.com/osbuild/image-builder/pull/901

Fixes 3020: Adding VNC geometry

---

deployments/jobs.yaml

we saw some errors during the previous repair, so we want to try it again

Refs 3053: rerun repair

---

deployments/jobs.yaml

Run the pulp repair again
none

Refs 3053: repair again

---

deployments/deployment.yaml

forgot to rename it in our code

Refs 3372: switch to new s3 bucket name

---

pkg/config/config.go

Refs 3372: fix s3 bucket name in code

---

deployments/deployment.yaml

Build: move pulp to optional dep

---

pkg/config/tasks.go
pkg/tasks/worker/worker_pool.go

Fixes 3533: Add DeleteTemplatesTask to RequeueFailedTasks

---

.rhcicd/pr_check.sh

https://issues.redhat.com/browse/HMS-3773
pr_check pass

Fixes 3773: Disable rbac testing

---

deployments/testing-integration.yaml

Fixes 3845: Disable parallel testing in hms-integration

---

pkg/dao/rpms.go

Improve performance of rpms search query
I wasn't fully able to reproduce the ~20 seconds we are seeing in stage, but i could reproduce ~200 ms.
1.  I would turn off snapshotting to make it easier, edit config.yaml, turn the snapshotting feature off
2. ```make repos-import```
3. ```go run cmd/external-repos/main.go nightly-jobs```
4.  run this to create 10,000 'instances' of the repo:
```
for i in `seq 1 10000`; do curl -X POST  http://localhost:8000/api/content-sources/v1.0/repositories/ -H "`./scripts/header.sh $RANDOM$RANDOM`" -H "Content-Type: application/json" -d '{"name":"FOO", "url": "https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/"}'; done
```
5.  Run this request:
```
####
POST http://localhost:8000/api/content-sources/v1.0/rpms/names
x-rh-identity: …
```

Refs 3857: improve performance of rpms search query

---

.gitignore
.vscode/launch.json
KubernetesLocalProcessConfig.example.yaml

Build: Add support for bridge to kubernetes

---

.dockerignore

Build: ignore directories on container build

---

go.mod
go.sum

Fixes 4015: Bump tang to 0.0.6

---

deployments/dashboards/grafana-dashboard-content-sources.configmap.yaml

Updates dashboard for new metrics

Refs 2422: Add pending tasks grafana

---

deployments/testing-integration.yaml

Name update from hms-integration to insights-experiences.

Fixes 3962: Update Integration test image for IQE

---

pkg/candlepin_client/candlepin_client_mock.go
pkg/candlepin_client/content.go
pkg/candlepin_client/interface.go
pkg/config/config.go
pkg/dao/snapshots_mock.go
pkg/dao/task_info_mock.go
pkg/dao/templates_mock.go
pkg/tasks/delete_repository_snapshots.go
pkg/tasks/delete_repository_snapshots_test.go
test/integration/snapshot_test.go

Fixes 3600: delete distributions and env on template delete

---

pkg/pulp_client/client.go

Hello, I noticed this small detail - a new transport is created for each zest client, this effectively means that no HTTP connection pooling can be done. Here is an example of the [DefaultTransport](https://cs.opensource.google/go/go/+/refs/tags/go1.22.3:src/net/http/transport.go) from the standard library that is supposed to be reused - it is thread safe.
Easy help, this patch just extracts the variable into the package scope so it can be reused on every new client. In case you are wondering, all those timeouts are coming from the `DefaultTransport` from the standard library plus the `ResponseHeaderTimeout` that was already defined here.
_Edit: I was trying out github.dev, did not go well, force pushed the correct version._

Fixes 4249: Reuse HTTP zest transport

---

.rhcicd/pr_check.sh

This will deploy the apps using whatever is in stage which is where PRs are deployed after being merged.

Build: pr_check, use insights-stage as ref-env

---

README.md
docs/workflows/introspection.md
docs/workflows/snapshotting.md

Point out anything that isn't clear, is missing, or needs words to be fixed up real gud

Fixes 4090: add workflow docs

---

.rhcicd/pr_check.sh
deployments/deployment.yaml

Build: suspend cron for pr checks

---

deployments/deployment.yaml

Build: fix deployment bool

---

deployments/deployment.yaml

Build: update pulp url for ephemeral

---

mk/go-rules.mk

pr_check test run passes AND build test passing.

Refs 4294: fix db migration test

---

.github/pull_request_template.md

Build: Remove checklist from PR template

---

pkg/tasks/queue/pgqueue.go

Refs 4478: release connection on Cancel

---

pkg/handler/templates.go
pkg/handler/templates_test.go

Fixes 4540: cancel template update tasks on delete

---

pkg/config/tasks.go

Somehow this didn't make it to the cancel list
Create a repository and grab the UUID,
run this, replacing 8f84b19e-675a-4af2-83c2-b2597f16ae8c with the repo uuid :
```
UUID=`curl -X POST --location "http://localhost:8000/api/content-sources/v1.0/templates/"     -H "x-rh-identity: eyJpZGVudGl0eSI6eyJvcmdfaWQiOiI5IiwgInR5cGUiOiJVc2VyIiwidXNlciI6eyJ1c2VybmFtZSI6ImZvbyJ9LCJhY2NvdW50X251bWJlciI6ImZvbyIsImludGVybmFsIjp7Im9yZ19pZCI6IjkifX19Cg=="     -H "Content-Type: application/json"     -d "{
\"name\":\"test-$RANDOM\",
\"arch\": \"x86_64\",
\"version\": \"9\",
\"repository_uuids\": [\"8f84b19e-675a-4af2-83c2-b2597f16ae8c\"],
\"date\": \"2024-08-09T14:04:05Z\"
}"  | jq .uuid`
curl -X DELETE --location "http://localhost:8000/api/content-sources/v1.0/templates/$UUID"     -H "x-rh-identity: …
```

Refs 4540: add update template task to cancel list

---

compose_files/pulp/docker-compose.yml
pkg/config/config.go
pkg/dao/repository_configs.go
pkg/dao/snapshots_test.go

Associated ticket [here](https://issues.redhat.com/browse/HMS-4426). 
This removes the NewRepositoryFiltering feature option. 
- Call the features API, the NewRepositoryFiltering variable should no longer appear.

Fixes 4426: Remove NewRepositoryFiltering feature

---

api/openapi.json
go.mod
go.sum

Build: use kin-openapi with order fix

---

.air.toml
.gitignore
README.md

This is just a DX improvement for speeding up local development by adding an optional live reload server setup. I set this up for myself, but I think it would be a great addition to the project and is useful to everyone, try it out if you like it/find it useful we could add it to the repo. 😁😇

Build: add optional live reloading server setup

---

cmd/external-repos/main.go

Confirmed this was the only usage of GetRpmRemoteList

Refs 4745: lookup domain on init containers

---

docs/register_client.md

When setting up a testing RHEL VM for the first time, the command in the docs for configuring subscription-manager didn't work, but a one I found in our chat did, so it should be updated. 😄

Build: update subman config command in register client doc

---

pkg/dao/task_info.go

- Changed task cleanup to not delete tasks if they are the last task that updated a template
1. Create a custom repo, RH repo, let them snapshot, and create a template with those repos
2. Update the task that just updated the template to a date at least 20 days prior
```
UPDATE tasks
SET queued_at = '2024-09-08 15:24:52.793340 +00:00', started_at = '2024-09-09 15:24:52.793340 +00:00', finished_at = '2024-09-10 15:24:52.793340 +00:00'
WHERE id = '<task id>';
```
3. Run `go run cmd/external-repos/main.go nightly-jobs`
4. The `update-template-content` task that just updated the template should not have been cleaned up. And in the UI, the status of the template should still be valid

Fixes 4792: template tasks deleted causing invalid status

---

pkg/dao/snapshots.go
pkg/dao/snapshots_test.go

Previously this function was written to return snapshots closest to the date, which isn't what we want.  We want it to return the newest snapshot prior to that date if it exists, if not the oldest snapshots after that date.
It might work best to test this on a fresh/clean db
1.  Create a repository and let it snapshot:
```
####
POST http://localhost:8000/api/content-sources/v1.0/repositories/
//x-Rh-Insights-Request-Id: 9d229d34-7219-405d-ba3d-8f99cf7c36ae
{
"name": "test57",
"url": "http://jlsherrill.fedorapeople.org/fake-repos/needed-errata/",
"gpg_key": "",
"snapshot": true
}
```
2. …

Fixes 4740: select correct snapshots for date selection

---

pkg/pulp_client/rpm_distributions.go
pkg/pulp_client/rpm_remote.go
pkg/pulp_client/status.go
pkg/pulp_client/task.go
pkg/pulp_client/uploads.go
pkg/tasks/snapshot_helper.go

I could not reproduce the original issue, but this adds checks to places I believe could cause a panic under the right conditions.

Fixes 4762: Add missing nil checks for pulp methods

---

deployments/dashboards/grafana-dashboard-content-sources.configmap.yaml

This PR adds a new Grafana visualization for a newly added metric ([PR](https://github.com/content-services/content-sources-backend/pull/833)) and adjust sizes of neighboring visualizations.

Refs 4739: adding new grafana visualization

---

.github/workflows/content-sources-actions.yml
compose_files/pulp/docker-compose.yml
deployments/docker-compose.yml

Postgres version was just updated in AppSRE for stage
tests pass

Build: Update postgres version

---

pkg/dao/domains.go

add cs prefix to domain name
and use better random hex generation
Tests pass

Refs 4822: add cs prefix to domain name

---

renovate.json

Build: update konflux on mondays

---

pkg/tasks/queue/pgqueue.go
pkg/tasks/queue/pgqueue_test.go

The "template not found" error is still showing up because of an edge case where a task is failed before it is canceled
I missed this case in the discussion [here](https://github.com/content-services/content-sources-backend/pull/875#discussion_r1831462633
). Bryttanie had it right. :)
I could not reproduce this locally, but the unit test is able to test this scenario
To reproduce this locally, you could try running the following as a script, while also modifying that update-template-content task to fail. But this did not work for me.
```
UUID=$(curl -s -X POST --location "http://localhost:8000/api/content-sources/v1.0/templates/"     -H "x-rh-identity: eyJpZGVudGl0eSI6eyJvcmdfaWQiOiIxNzc5MTU2MCIsICJ0eXBlIjoiVXNlciIsInVzZXIiOnsidXNlcm5hbWUiOiJzbmFwVXNlciJ9LCJhY2NvdW50X251bWJlciI6IjE3NzkxNTY …
```

Fixes 5058: separate set cancel from set cancel_attempted

---

pkg/tasks/queue/pgqueue.go

This fixes the nightly job failure by checking if the context was canceled before closing the pool. Here I added back a separate context for the listener, there might be a better way to do this without that though 🤔 
1. Start the server and run `make repos-import-rhel9 && go run cmd/external-repos/main.go nightly-jobs`
2. Should not panic and RH repos should be snapshotted

Fixes 5144: nightly job failing

---

.github/workflows/title.yml

Adjusts title check to look for  "HMS-123,HMS-456: Title"

Build: enforce full jira ticket

---

pkg/tasks/worker/worker.go

This will make sure a running task requeues  on server exit, rather than possibly failing before having the chance to requeue
1. You can apply this patch to help recreate the conditions of the bug
```
diff --git a/pkg/tasks/queue/queue.go b/pkg/tasks/queue/queue.go
index cbf0105..b97c5bd 100644
--- a/pkg/tasks/queue/queue.go
+++ b/pkg/tasks/queue/queue.go
@@ -11,7 +11,7 @@ import (
"github.com/google/uuid"
)
-const MaxTaskRetries = 3 // Maximum number of times a task can be retried before failing
+const MaxTaskRetries = 100 // Maximum number of times a task can be retried before failing
type Task struct {
Typename     string
diff --git a/pkg/tasks/worker/worker.go b/pkg/tasks/worker/worker.go
index 3fac3e8..f8754f4 100644
--- a/pkg/tasks/worker/worker.go
+++ b/pkg/tasks/worker/worker.go …
```

HMS-5127: force task requeue on server exit

---

go.mod

Build: update to 1.22.9

---

deployments/deployment.yaml

Build: remove feature service CA from deployment

---

deployments/deployment.yaml

Build: add feature filter to service deployment

---

.github/workflows/title.yml

Build: allow for prs with Test prefix

---

deployments/deployment.yaml

some small fixes to the deployment.yaml

Build: deployment fixes for cloudwatch

---

deployments/deployment.yaml

Build: use CLIENTS for cfg prefix

---

.github/workflows/playwright-actions.yml

Build: fix playwright nightly job

---

deployments/deployment.yaml

change secret name, previous secret was using the wrong account

Build: use different secret for log access

---

deployments/deployment.yaml

Build: swap access/secret keys for log parser

---

deployments/deployment.yaml

Build: switch process logging back to daily

---

pkg/jobs/transform_pulp_logs.go
pkg/jobs/transform_pulp_logs_test.go

Pulp added the request org id from the identity header, this adds it to our log gathering
also fixes a zero timestamp we were seeing
just a code review

HMS-5527: add request org_id to log parse

---

_playwright-tests/tests/API/TemplateCRUD.spec.ts
_playwright-tests/tests/API/helpers/apiHelpers.tsx
_playwright-tests/tests/API/helpers/deleteRepositories.tsx
_playwright-tests/tests/API/helpers/repoHelpers.tsx

[API - Playwright POC - Templating](https://issues.redhat.com/browse/HMS-5432)
This PR was blocked by https://github.com/content-services/content-sources-backend/pull/977

HMS-5432: API - Playwright POC - Templating

---

_playwright-tests/tests/API/Repositories.spec.ts

This PR adds a new PW test (migrates it from IQE) which tests the `/repository_parameters/validate/` API endpoint.
- All tests pass as expected.
- The new migrated test verifies the same functionality as the one in IQE.

HMS-5595: Add test for repo parameters validation api

---

.github/workflows/playwright-actions.yml

Test: revert pulling secrets from gh

---

.github/workflows/playwright-actions.yml
_playwright-tests/tests/API/TemplateCRUD.spec.ts
_playwright-tests/tests/API/helpers/apiHelpers.tsx
_playwright-tests/tests/API/helpers/repoHelpers.tsx
_playwright-tests/yarn.lock

Chore: Update CI

---

.github/workflows/playwright-actions.yml

Test: replacing one more secret for currents

---

.github/workflows/playwright-actions.yml

Test: fix setting of CURRENTS_RECORD_KEY

---

.tekton/content-sources-backend-pull-request.yaml
.tekton/content-sources-backend-push.yaml

Required tasks by April 1st.
Sorry unsure about commit message format 🤔

Build: add required SAST tasks to Konflux pipelines

---

pkg/tasks/update_template_content.go

This PR had an issue that was missed by the tests for some reason: https://github.com/content-services/content-sources-backend/pull/1046

HMS-5565: fix linting error

---

_playwright-tests/tests/API/Repositories.spec.ts

This adds a new PW test (migrates it from IQE) which tests that repository creation will ignore duplicate distribution versions.
- All tests pass as expected.
- The new migrated test verifies the same functionality as the one in IQE.

HMS-5600: Add test for duplicated distro versions

---

pkg/dao/rpms.go
pkg/dao/rpms_test.go

Previously modules were being returned with only one stream per module.  In reality we want all the stream but only 1 version per stream.  
```
make repos-import-rhel9
go cmd/external-repos/main.go snapshot https://cdn.redhat.com/content/dist/rhel9/9/x86_64/appstream/os/
```
run this query:
```
POST http://localhost:8000/api/content-sources/v1.0/rpms/names
{
"urls": ["https://cdn.redhat.com/content/dist/rhel9/9/x86_64/appstream/os/"],
"search": "nginx",
"include_package_sources": true
}
```
with this change:
```
{
"package_name": "nginx",
"summary": "A high performance web server and …
```

HMS-5998: return multiple streams for each module

---

.github/workflows/playwright-actions.yml
_playwright-tests/package.json
_playwright-tests/yarn.lock

This PR changes the playwright action to use a new custom testing proxy, which should make tests faster and more stable.
Also increases the instance size and parallelizes the different long
running setups.
Playwright test should pass without loading errors.

HMS-8563: change to testing proxy for PW tests in actions

---

pkg/clients/pulp_client/interfaces.go
pkg/clients/pulp_client/pulp_client_mock.go
pkg/clients/pulp_client/rpm_distributions.go
pkg/tasks/delete_snapshots.go
pkg/tasks/delete_snapshots_test.go

Build: debug snapshot deletion

---

pkg/handler/repositories_test.go

This unit test broke with the introduction of unified EPEL
Tests pass

Test: Fix broken PartialUpdate unit test

---

_playwright-tests/tests/API/Repositories.spec.ts

Added a new test case to verify the bulk import functionality for repositories. The test ensures that repositories are imported correctly, their statuses are updated to 'Valid'.

HMS-8635: Add bulk import repositories test

---

_playwright-tests/tests/API/Repositories.spec.ts

migrating this iqe test https://gitlab.cee.redhat.com/insights-qe/iqe-content-sources-plugin/-/blob/master/iqe_content_sources/tests/test_repository_api_only.py?ref_type=heads#L1756

HMS-8774: Test to verify bulkExportRepositories api

---

docs/upload-rpm.py

Userfacing python script for uploading rpms, supports chunk uploads
Create an upload repository, grab the UUID, upload an rpm:
```
USERNAME=<USERNAME> PASSWORD='<PASSWORD>' python docs/upload-rpm.py  f287a13b-7985-4282-b53e-f9e9b8008b33  ~/rpms/google-chrome-unstable-128.0.6601.2-1.x86_64.rpm
```

HMS-8936: add userfacing upload script

---

_playwright-tests/tests/API/Repositories.spec.ts

migrate - https://gitlab.cee.redhat.com/insights-qe/iqe-content-sources-plugin/-/blob/master/iqe_content_sources/tests/test_repository_api_only.py?ref_type=heads#L1387

HMS-8897: Test to fetch and verify repository configuration file

---

.github/workflows/playwright-actions.yml
_playwright-tests/tests/API/PopularRepos.spec.ts

migrate 
https://gitlab.cee.redhat.com/insights-qe/iqe-content-sources-plugin/-/blob/master/iqe_content_sources/tests/test_repository_api_only.py?ref_type=heads#L1510
peer review

HMS-8894: Test to search rpm in non added popular repo

---

_playwright-tests/tests/API/PopularRepos.spec.ts
configs/config.yaml.example

Build: enable community_repos for playwright tests

---

deployments/deployment.yaml

Fixes a couple of issues with the deployment.yaml, preventing kessel from being used

HMS-8568: fix kessel variable in deployment.yaml

---

pkg/dao/repository_configs.go

- Includes the community and Red Hat orgs when exporting and importing repos
1. Import and snapshot a community, Red Hat, and custom repo
2. Use the bulk export API to export all these repos:
```
POST /repositories/bulk_export/
{
"repository_uuids": [
"<community_repo_uuid>", "<redhat_repo_uuid>", "<custom_repo_uuid>" 
]
}
```
You should see no errors and a response similar to this:
```
[
{
"name": "EPEL 10 Everything x86_64",
"url": "https://dl.fedoraproject.org/pub/epel/10/Everything/x86_64/",
"origin": "community",
"distribution_versions": [
"10"
],
"distribution_arch": "x86_64",
"gpg_key": "-----BEGIN PGP PUBLIC KEY BLOCK-----\n...\n=mhQZ\n-----END PGP PUBLIC KEY BLOCK-----",
"metadata_verification": false,
"module_hotfixes": false,
"snapshot": true
},
{
"name": "Red Hat CodeReady …
```

HMS-9214: bulk export/import should include community and rh repos

---

_playwright-tests/tests/API/Repositories.spec.ts

Add check for API endpoints related to introspection time
tests pass

Test: Add check introspection time

---

pkg/clients/pulp_client/domains.go
pkg/clients/pulp_client/rpm_remote.go
test/integration/snapshot_test.go

**Pulp update calls now return 200 with no task**
Previously pulp always created an internal pulp task and returned the task href,
when there had been triggered an update call to domains or remote, irrespective if
the update was changing anything or not. 
From now on, when an update call to
- domain (UpdateDomainIfNeeded) or 
- remote (UpdateRmpRemote) does not change anything,
pulp does not create a task. 
This is indicated by 200 status code. 
If there is an actual change, pulp sends 202 with taskHref back. 
This commit updates the parts of code
that deal with these pulp functions to take this pulp api change into account.
Note that Pulp team has been waiting on content-sources to be updated first,
before they update Pulp. This means that zest client is still expecting to receive
a task …

HMS-9072: fix update calls to pulp to handle 204 with no task

---

_playwright-tests/tests/API/Repositories.spec.ts

[HMS-8886  migrate test_CRUD_honours_org_id](https://issues.redhat.com/browse/HMS-8886)
tests pass

Test: Add test CRUD honours OrgID

---

_playwright-tests/tests/API/SnapshotDeletion.spec.ts

[HMS-8861: migrate test_snapshot_deletion](https://issues.redhat.com/browse/HMS-8861)
tests pass

HMS-8861: migrate test_snapshot_deletion
